### ISSUE TITLE
Add teamredminer support for Linux & Windows

### ISSUE THREAD

**Issue by Kartereo** [vertcoin-project/one-click-miner-vnext#10]
I would love the ability to have a couple different miners for both AMD & Nvidia. I believe that this would have many benefits for the community. We could also put descriptions, specifications and official links for them somewhere in the options.

**Comment by gertjaap** [comment]
Fixed in https://github.com/vertcoin-project/one-click-miner-vnext/commit/013f47b5e913b229151878df98682dbbfd8d8344 (released as https://github.com/vertcoin-project/one-click-miner-vnext/releases/tag/0.1-alpha23)
