### ISSUE TITLE
Miner doesnt work on my laptop says Could not find compatible miner binaries

### ISSUE THREAD

**Issue by sharthoot** [vertcoin-project/one-click-miner-vnext#100]

**Comment by robjvan** [comment]
Same issue, here is the debug.log:

[debug.log](https://github.com/vertcoin-project/one-click-miner-vnext/files/5897790/debug.log)

**Comment by robjvan** [comment]
Digging into the log, looks like this might be the issue: 

2021/01/30 13:17:16.507641 [DEBUG] [VerthashMiner] [2021-01-30 13:17:16] ERROR Verthash data file name is invalid

Have updated to 2.0 RC3 then deleted the appdata/roaming ocm folder - still experiencing the same problem.

**Comment by marrtincho** [comment]
I have the same error

**Comment by robjvan** [comment]
As per the discussions in the Discord channel, the workaround for now seems to be copying the verthash.dat file from your wallet directory to the ocm directory.  

I *think* the error is caused by the newer releases not generating the dat file.

**Comment by robjvan** [comment]
> I have the same error

As per the discussions in the Discord channel, the workaround for now seems to be copying the verthash.dat file from your wallet directory to the ocm directory.  

I *think* the error is caused by the newer releases not generating the dat file.

**Comment by vertiond** [comment]
@sharthoot @marrtincho Please make sure the program is excluded from your antivirus / firewall and that you have the latest drivers installed for your GPU.

**Comment by marrtincho** [comment]
@vertiond Thank you, I didi it and everything started correctly, but now apparently is woring only with the integrated grafics, not with the nvidia card, mine is a little outdated, is a GTX960m I know it is not the best option but I want to give a try. And when I disable the intel integrated graphics, Easy Miner shows: Failure to configure VertHashMiner.exe status 3221225477. 
IDK what I am doing wrong

**Comment by vertiond** [comment]
This could be an issue with VerthashMiner using a default WorkSize that is too large for your GPU.  

https://github.com/CryptoGraphics/VerthashMiner/issues/6

**Comment by vertiond** [comment]
Solved for GTX960m by lowering WorkSize in https://github.com/vertcoin-project/one-click-miner-vnext/issues/128#issuecomment-775069917 
This issue is related to VerthashMiner

**Comment by tgz666123** [comment]
我也有同样的问题
Could not find compatible miner binaries
