### ISSUE TITLE
Checks failed exit status 3221225781

### ISSUE THREAD

**Issue by DrGonorrhea** [vertcoin-project/one-click-miner-vnext#106]
Not sure

Checks failed: Failure to configure VerthashMiner.exe: exit status 3221225781

It happens automatically when I launch the program

OCMv2.0-rc4-3001e5d downloaded from the Vertcoin website

Windows 10

Installation crashed and has been happening since.

**Comment by vertiond** [comment]
Exclude it from your antivirus.
