### ISSUE TITLE
special characters in windows verthash.dat path

### ISSUE THREAD

**Issue by ac0uk** [vertcoin-project/one-click-miner-vnext#109]
On windows, if the users name contains special characters, verthash miner can not find verthash.dat

Possible fix maybe to set the path to %APPDATA% instead of hardcode it in verthash-miner.conf

**Comment by ac0uk** [comment]
https://github.com/CryptoGraphics/VerthashMiner/issues/4

**Comment by gertjaap** [comment]
This should be fixed, even without an OCM update since it's fixed in the upstream VerthashMiner that all OCM versions will now use.
