### ISSUE TITLE
Not estimating exptected 24hr earnings

### ISSUE THREAD

**Issue by Thatmanontheright** [vertcoin-project/one-click-miner-vnext#11]
There was no display of the expected earnings. The screen was stuck on estimating. OCM was mining correctly.

Reproducable

Github release 0.21

Windows 10 / GTX 1050

Gertjaap defined the issue likely being relating to hashrate being reported in kh/s

**Comment by gertjaap** [comment]
Fixed in https://github.com/vertcoin-project/one-click-miner-vnext/commit/c26a9c2bc9ed85df6b2eebb91e6039f44aeb1093
