### ISSUE TITLE
updated to latest version and now all i get is no comatible miner binaries error

### ISSUE THREAD

**Issue by babablacksheep7** [vertcoin-project/one-click-miner-vnext#112]

**Comment by vertiond** [comment]
@babablacksheep7 Please make sure the program is excluded from your antivirus / firewall and that you have the latest drivers installed for your GPU.

**Comment by gertjaap** [comment]
@babablacksheep7 Can you retry with RC6 and reopen the issue if the problem remains? Thanks.

**Comment by babablacksheep7** [comment]
Yes this morning I installed RC7. And have the latest drivers for my video cards installed. The only problem now is on my 6 card rig 1660 ti's they dont run steady constant intermittenly turning on and of cards randomly instead of running steady , drivers say no problems.

Sent from ProtonMail mobile

-------- Original Message --------
