### ISSUE TITLE
Spend balance not increasing from 0.0000000

### ISSUE THREAD

**Issue by DrBob52** [vertcoin-project/one-click-miner-vnext#113]
I have a 6.42 VTC/24hr expected earnings value but I have had the miner running without seeing an increase in my spendable balance. Been running almost 2 hours now. After restarting the application my expected earnings is also stuck at 0.00 VTC. My task manager is showing that the miner is still using a significant amount of memory. Refresh button hasn't changed anything.

I expected the value to be up about .25 vertcoin every hour or so

![Screenshot_5](https://user-images.githubusercontent.com/43355009/106526875-5a7d8b00-64b4-11eb-8639-16818075edd8.png)
![Screenshot_6](https://user-images.githubusercontent.com/43355009/106529325-4c316e00-64b8-11eb-9ef7-83b36e5db41b.png)

not sure

using v2.0-rc5d4ce239

windows

**Comment by DrBob52** [comment]
After restarting the application, my expected earnings is also stuck at 0.00 VTC. My task manager is showing that the miner is still using a significant amount of memory.

**Comment by Mous3ledge** [comment]
I am also experiencing this problem. Downloaded the 2.0-rc5-windows-x64.zip file. Zero values for hashrate, but task manger shows it's using large portion of memory. Drivers are updated, and restarted the computer. No change. Some help would be great.

**Comment by nonius3d** [comment]
same here, on all devices.

**Comment by gertjaap** [comment]
RC5 and previous were mining on p2pool. Especially for lower hashrate miners it's hard to find a share on p2pool, and thus it can take a long time before you see a payout.

RC6 mines on a PPLNS pool with 1% fee, you might see increase faster. Also OCM will report a pending balance for this pool, so you'll see progress much quicker.

Regardless, it's not a problem in the OCM. The OCM just reports what the pools / blocks say is your balance.

If you still feel something's wrong here, feel free to reopen.
