### ISSUE TITLE
my spend balance isn't increasing from 0.00000000

### ISSUE THREAD

**Issue by Antapro** [vertcoin-project/one-click-miner-vnext#116]
i was hoping after a few hours of mining it would go up it mined for about 4 hours yesterday and my balence still didnt go up

![2021-02-01 (8)](https://user-images.githubusercontent.com/78413227/106581704-15e90280-653b-11eb-99c6-2a1f29332a46.png)

im using rc5 downloaded from github

1660 super windows 10

![2021-02-02 (2)](https://user-images.githubusercontent.com/78413227/106581923-50eb3600-653b-11eb-9e72-7acf792f7776.png)
![2021-02-02 (3)](https://user-images.githubusercontent.com/78413227/106584348-fbfcef00-653d-11eb-8115-acc237c89213.png)
it says its updated the balence but on ocm its still o.oooooooo

%APPDATA%\vertcoin-ocm on Windows
$HOME/.vertcoin-ocm on Linux

-->

**Comment by nonius3d** [comment]
+1

**Comment by gertjaap** [comment]
RC5 and previous were mining on p2pool. Especially for lower hashrate miners it's hard to find a share on p2pool, and thus it can take a long time before you see a payout.

RC6 mines on a PPLNS pool with 1% fee, you might see increase faster. Also OCM will report a pending balance for this pool, so you'll see progress much quicker. 

Regardless, it's not a problem in the OCM. The  OCM just reports what the pools / blocks say is your balance.

If you still feel something's wrong here, feel free to reopen.

**Comment by nonius3d** [comment]
rc running since you released, vtc still at 00000000

gr


s
