### ISSUE TITLE
Feature request:  add progress bar while verthash.dat is being generated

### ISSUE THREAD

**Issue by burley01** [vertcoin-project/one-click-miner-vnext#117]
Generating this file can take a while, and could be perceived that the program has frozen.  Some type of activity graphics/progress bar/percent complete indicator while this file is being generated would be helpful to the user to let them know the program is working ok.

**Comment by gertjaap** [comment]
This is a good suggestion. It requires overhaul to the underlying verthash-go code, but I think it'd be a good addition.

**Comment by M3G4THEKING** [comment]
@burley01 2hrs stuck at  checks.verthash. I whant to try this but they need to improve alot this software.
