### ISSUE TITLE
checks failed Failure to configure Verthashminer: exit status 127

### ISSUE THREAD

**Issue by Rj4050** [vertcoin-project/one-click-miner-vnext#119]

**Comment by gertjaap** [comment]
Please enable  debug logging under the settings tab, retry, and then post `%APPDATA%\vertcoin-ocm\debug.log` here for analysis

**Comment by theobaldfr** [comment]
Same error here.
Can you tell me the log path on Debian ? I'll post it here.
For information I use a laptop with integrated graphics + Nvidia graphic card. Might be related ?

**Comment by vertiond** [comment]
@theobaldfr '~/.vertcoin-ocm/debug.log`

**Comment by theobaldfr** [comment]
@vertiond Thanks,

Here is the debug.log

2021/02/12 18:17:27.626572 OCM v2.0-rc12-e88c4e4 Started up
2021/02/12 18:17:28.307789 [INFO] Error reading keyfile: open /home/jeff/.vertcoin-ocm/keyfile.hex: no such file or directory
2021/02/12 18:17:29.133743 [INFO] User IETF is fr-FR
2021/02/12 18:17:29.133814 [INFO] Matched tag is fr-u-rg-frzzzz
2021/02/12 18:17:29.133827 [INFO] Returning locale fr
2021/02/12 18:17:29.201243 [INFO] Checking wallet..
2021/02/12 18:17:29.201316 [INFO] Error reading keyfile: open /home/jeff/.vertcoin-ocm/keyfile.hex: no such file or directory
2021/02/12 18:17:29.201333 [INFO] Error reading keyfile: open /home/jeff/.vertcoin-ocm/keyfile.hex: no such file or directory
2021/02/12 18:17:29.201486 [INFO] Initializing wallet VrSwsBBq6TgsAyy8YQdes4wxxxxxxxxxx
2021/02/12 18:17:29.201760 [INFO] Wallet initialized: 0
2021/02/12 18:17:34.186839 [INFO] Error reading keyfile: open /home/jeff/.vertcoin-ocm/keyfile.hex: no such file or directory
2021/02/12 18:17:39.189334 [INFO] Error reading keyfile: open /home/jeff/.vertcoin-ocm/keyfile.hex: no such file or directory
2021/02/12 18:17:39.980598 [INFO] Checking wallet..
2021/02/12 18:17:39.980686 [INFO] Initializing wallet VxCJ9zDG1w7uzegw2yhzzzzzzzzzzzzzz
2021/02/12 18:17:39.980734 [INFO] Wallet initialized: 1
2021/02/12 18:17:40.003774 [DEBUG] GPU [Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)] matched regex [.*Intel.*]
2021/02/12 18:17:40.003834 [DEBUG] GPU [NVIDIA Corporation GF108M [GeForce GT 630M] (rev a1)] matched regex [.*NVIDIA.*]
2021/02/12 18:17:40.455873 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false) (Block height 1499999 - -1 - match: false)
2021/02/12 18:17:40.455919 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false) (Block height 1499999 - -1 - match: false)
2021/02/12 18:17:40.455933 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false) (Block height 1499999 - -1 - match: false)
2021/02/12 18:17:40.455944 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false) (Block height 1499999 - -1 - match: false)
2021/02/12 18:17:40.455956 [DEBUG] Found compatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/02/12 18:17:40.455972 [DEBUG] Not adding already present multi-gpu binary [VerthashMiner] again
2021/02/12 18:17:40.455983 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false) (Block height 0 - 0 - match: false)
2021/02/12 18:17:40.455993 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false) (Block height 0 - 0 - match: false)
2021/02/12 18:17:40.456002 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false) (Block height 0 - 0 - match: false)
2021/02/12 18:17:40.456018 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false) (Block height 0 - 0 - match: false)
2021/02/12 18:17:40.456029 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false) (Block height 0 - 0 - match: false)
2021/02/12 18:17:40.456040 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false) (Block height 0 - 0 - match: false)
2021/02/12 18:17:40.456193 [DEBUG] [Miner linux/3]Binary not found, downloading...
2021/02/12 18:17:42.092216 [DEBUG] [Miner linux/3]Daemon file downloaded
2021/02/12 18:17:42.112467 [DEBUG] [Miner linux/3]Daemon file is available and correct
2021/02/12 18:17:42.112527 [DEBUG] [Miner linux/3](Re)creating unpack directory
2021/02/12 18:22:58.321106 [DEBUG] Launching /home/jeff/.vertcoin-ocm/miners/unpacked-a629cf6f229760df342a29829ccf7ca9f717640a50a9eeeddf16bcc7f16b9aba/VerthashMiner-0.6.2-CUDA11-linux/VerthashMiner [--gen-conf /home/jeff/.vertcoin-ocm/verthash-miner-tmpl.conf]
2021/02/12 18:22:58.321979 [DEBUG] [VerthashMiner] /home/jeff/.vertcoin-ocm/miners/unpacked-a629cf6f229760df342a29829ccf7ca9f717640a50a9eeeddf16bcc7f16b9aba/VerthashMiner-0.6.2-CUDA11-linux/VerthashMiner: error while loading shared libraries: libOpenCL.so.1: cannot open shared object file: No such file or directory
2021/02/12 18:23:32.305588 [INFO] Stopping mining process...
2021/02/12 18:23:33.272355 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false) (Block height 1499999 - -1 - match: false)
2021/02/12 18:23:33.272481 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false) (Block height 1499999 - -1 - match: false)
2021/02/12 18:23:33.272550 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false) (Block height 1499999 - -1 - match: false)
2021/02/12 18:23:33.272599 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false) (Block height 1499999 - -1 - match: false)
2021/02/12 18:23:33.272659 [DEBUG] Found compatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/02/12 18:23:33.272734 [DEBUG] Not adding already present multi-gpu binary [VerthashMiner] again
2021/02/12 18:23:33.272819 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false) (Block height 0 - 0 - match: false)
2021/02/12 18:23:33.272889 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false) (Block height 0 - 0 - match: false)
2021/02/12 18:23:33.272949 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false) (Block height 0 - 0 - match: false)
2021/02/12 18:23:33.273014 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false) (Block height 0 - 0 - match: false)
2021/02/12 18:23:33.273055 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false) (Block height 0 - 0 - match: false)
2021/02/12 18:23:33.273086 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false) (Block height 0 - 0 - match: false)
2021/02/12 18:23:33.273149 [DEBUG] [Miner linux/3]Daemon file already exists
2021/02/12 18:23:33.295587 [DEBUG] [Miner linux/3]Daemon file is available and correct
2021/02/12 18:23:33.295636 [DEBUG] [Miner linux/3]Removing unpack directory
2021/02/12 18:23:33.296575 [DEBUG] [Miner linux/3](Re)creating unpack directory
2021/02/12 18:23:40.957497 [DEBUG] Launching /home/jeff/.vertcoin-ocm/miners/unpacked-a629cf6f229760df342a29829ccf7ca9f717640a50a9eeeddf16bcc7f16b9aba/VerthashMiner-0.6.2-CUDA11-linux/VerthashMiner [--gen-conf /home/jeff/.vertcoin-ocm/verthash-miner-tmpl.conf]
2021/02/12 18:23:40.958116 [DEBUG] [VerthashMiner] /home/jeff/.vertcoin-ocm/miners/unpacked-a629cf6f229760df342a29829ccf7ca9f717640a50a9eeeddf16bcc7f16b9aba/VerthashMiner-0.6.2-CUDA11-linux/VerthashMiner: error while loading shared libraries: libOpenCL.so.1: cannot open shared object file: No such file or directory

**Comment by vertiond** [comment]
@theobaldfr This would be a bug to report in https://github.com/CryptoGraphics/VerthashMiner/issues
