### ISSUE TITLE
Limiting GPU usage possible?

### ISSUE THREAD

**Issue by csrn** [vertcoin-project/one-click-miner-vnext#122]
Hi, 

The One Click Miner seems to claim 100% of the GPU's resources which makes my computer literally unusable (nearly frozen window operations, slowing down of mouse or keyboard input, etc.). 

As an improvement, I would like to have a slider of some sort to adjust the max resource allocation of the hashing process to make the program more useful on weaker desktop systems. 

Specs:
Arch Linux, Core i7, 16 GB RAM, an old GeForce GTX 970 with prop. drivers, awesome wm

**Comment by gertjaap** [comment]
OCM is just a wrapper around miner binaries from https://github.com/CryptoGraphics/VerthashMiner. If VerthashMiner supports a setting to allow this, it might be done in OCM but it doesnt.

Also i want to limit the number of knobs and dials on OCM. OCM stands for One Click Miner. Knobs and dials are all extra clicks confusing users. If you want advanced stuff, run the VerthashMiner using a batch file and set it up to your liking.

**Comment by csrn** [comment]
Thank you for your quick and informative response, Gert!
