### ISSUE TITLE
Stuck at "checks.verthash.."

### ISSUE THREAD

**Issue by MR-creations** [vertcoin-project/one-click-miner-vnext#124]
Issue: Got stuck on "checks.verthash.." when running the vertcoin-ocm.exe file

Expected behavior: According to the video on Youtube, I expected it to move along this point in just seconds

![image](https://user-images.githubusercontent.com/59884670/106712074-bd783a80-65f8-11eb-9a11-6cafa376d33f.png)

Version: rc6

OS: Windows
GPU: NVIDIA GeForce GTX 1050 Ti with Max-Q Design

**Comment by gertjaap** [comment]
Yeah this step can take a while depending on your hardware (specifically CPU/disk).

There's an issue #117 that  will help follow what's happening and how long it'll take. But I can't make it faster or skip the step.
