### ISSUE TITLE
Ability to manually select what gpu/gpus to use with multi gpu config

### ISSUE THREAD

**Issue by RedMatterGG** [vertcoin-project/one-click-miner-vnext#125]
Gui miner doesnt have an option to select which gpu can/cant mine on demand

The ability to toggle on/off the gpus i want to mine vertcoin

Miner starts mining on all gpus automatically.

Using Windows 10

Is there any other command line miner that supports vertcoin algo that i can use till you manage to implement a gpu selection tab,right now if you have 4 gpus and you want to mine different coins on them you cant do that(Well you can but it will mine vert and the other coin and obliterate boths algos hashrates)

**Comment by gertjaap** [comment]
I don't think this has a place in the OCM. If you have multiple GPUs and want to mine different coins, you're not the target audience for  OCM. You should just use Verthashminer from the console which allows you to tweak which GPUs you want to use and which you don't.

Adding more settings to the OCM is not what I want - it's supposed to remain as simple as possible.
