### ISSUE TITLE
miner software reported no compatible GPU

### ISSUE THREAD

**Issue by musictop100** [vertcoin-project/one-click-miner-vnext#126]

**Comment by vertiond** [comment]
What is your GPU?

Please make sure that your GPU meets specifications found here: https://github.com/CryptoGraphics/VerthashMiner#supported-hardware

**Comment by mirbaagheri** [comment]
I have same problem on ASUS GTX 1060 6GB
Windows 10 X64 20H2 Build 19042.685 

[Display]
Operating System:	Windows 10 Enterprise, 64-bit
DirectX version:	12.0 
GPU processor:		GeForce GTX 1060 6GB
Driver version:		441.66
Driver Type:		DCH
Direct3D API version:	12
Direct3D feature level:	12_1
CUDA Cores:		1280 
Core clock:		1506 MHz 
Memory data rate:	8.01 Gbps
Memory interface:	192-bit 
Memory bandwidth:	192.19 GB/s
Total available graphics memory:	14302 MB
Dedicated video memory:	6144 MB GDDR5
System video memory:	0 MB
Shared system memory:	8158 MB
Video BIOS version:	86.06.63.00.A5
IRQ:			Not used
Bus:			PCI Express x16 Gen3
Device Id:		10DE 1C03 85A41043
Part Number:		G410 0030

[Components]

nvui.dll		8.17.14.4166		NVIDIA User Experience Driver Component
nvxdplcy.dll		8.17.14.4166		NVIDIA User Experience Driver Component
nvxdbat.dll		8.17.14.4166		NVIDIA User Experience Driver Component
nvxdapix.dll		8.17.14.4166		NVIDIA User Experience Driver Component
NVCPL.DLL		8.17.14.4166		NVIDIA User Experience Driver Component
nvCplUIR.dll		8.1.940.0		NVIDIA Control Panel
nvCplUI.exe		8.1.940.0		NVIDIA Control Panel
nvWSSR.dll		26.21.14.4166		NVIDIA Workstation Server
nvWSS.dll		26.21.14.4166		NVIDIA Workstation Server
nvViTvSR.dll		26.21.14.4166		NVIDIA Video Server
nvViTvS.dll		26.21.14.4166		NVIDIA Video Server
nvLicensingS.dll		6.14.14.4166		NVIDIA Licensing Server
nvDevToolS.dll		26.21.14.4166		NVIDIA 3D Settings Server
nvDispSR.dll		26.21.14.4166		NVIDIA Display Server
nvDispS.dll		26.21.14.4166		NVIDIA Display Server
PhysX		09.19.0218		NVIDIA PhysX
NVCUDA.DLL		26.21.14.4166		NVIDIA CUDA 10.2.108 driver
nvGameSR.dll		26.21.14.4166		NVIDIA 3D Settings Server
nvGameS.dll		26.21.14.4166		NVIDIA 3D Settings Server

**Comment by Lauwy222** [comment]
Same problem, Running on a MSI 1060 6GB

**Comment by vertiond** [comment]
@Lauwy222 @mirbaagheri You may also have to manually make an exclusion for OCM.  I am assuming your drivers are up to date as well.

**Comment by mirbaagheri** [comment]
How to?

**Comment by vertiond** [comment]
There is a video that details the process here: https://youtu.be/V2uqtXBeKgM
