### ISSUE TITLE
Feature request: add ability to change language

### ISSUE THREAD

**Issue by Pluppo** [vertcoin-project/one-click-miner-vnext#127]
I would like to have the UI in English rather than the language One Click Miner thinks I have.

Please add an option to change the language.

**Comment by gertjaap** [comment]
It detects the language from the OS. I am not in favor of adding more settings to OCM. It's supposed to be as little configuring as possible

**Comment by Pluppo** [comment]
Do you know what it uses for detection? I have these settings in Windows, but One Click Miner is showing up in Danish:
![image](https://user-images.githubusercontent.com/43924988/106809847-762b9180-666c-11eb-8901-212b5a833f76.png)

**Comment by Pluppo** [comment]
This isn't really a feature request anymore, but a bug. So I'll close this issue and open a new one with a better description.
