### ISSUE TITLE
OCM is always failing to create verthash data buffer, then says device not responding and the miner restarts this happens in a loop.

### ISSUE THREAD

**Issue by cryptopeach** [vertcoin-project/one-click-miner-vnext#128]
My GPU is a GTX 960m 4 GB VRAM.

Here is a part of the debug file when that happens:

2021/02/03 19:10:49.246711 [DEBUG] [VerthashMiner] [2021-02-03 19:10:49] WARN  Skipping CL platform (index: 0, NVIDIA Corporation)
2021/02/03 19:10:49.247711 [DEBUG] [VerthashMiner] [2021-02-03 19:10:49] INFO  Found 1 OpenCL devices.
2021/02/03 19:10:49.269696 [DEBUG] [VerthashMiner] [2021-02-03 19:10:49] INFO  Found 1 CUDA devices
2021/02/03 19:10:49.269696 [DEBUG] [VerthashMiner] [2021-02-03 19:10:49] INFO  Using a configuration file (C:\Users\Pedro Xavier\AppData\Roaming\vertcoin-ocm\verthash-miner.conf)
2021/02/03 19:10:49.269696 [DEBUG] [VerthashMiner] [2021-02-03 19:10:49] INFO  Loading verthash data file...
2021/02/03 19:10:49.852379 [DEBUG] [VerthashMiner] [2021-02-03 19:10:49] INFO  Verthash data file has been loaded succesfully!
2021/02/03 19:10:49.853362 [DEBUG] [VerthashMiner] [2021-02-03 19:10:49] INFO  Verifying verthash data file...
2021/02/03 19:10:58.367263 [DEBUG] [VerthashMiner] [2021-02-03 19:10:58] INFO  Verthash data file has been verified succesfully!
2021/02/03 19:10:58.367263 [DEBUG] [VerthashMiner] [2021-02-03 19:10:58] INFO  Using protocol: Stratum.
2021/02/03 19:10:58.367263 [DEBUG] [VerthashMiner] [2021-02-03 19:10:58] WARN  Failed to get a "CoinbaseAddress" option inside "Connection" section. Setting to ""
2021/02/03 19:10:58.367263 [DEBUG] [VerthashMiner] [2021-02-03 19:10:58] WARN  Failed to get a "CoinbaseSignature" option inside "Connection" section. Setting to ""
2021/02/03 19:10:58.368263 [DEBUG] [VerthashMiner] [2021-02-03 19:10:58] WARN  Failed to get a "SSLCertificateFileName" option inside "Connection" section. Setting to ""
2021/02/03 19:10:58.368263 [DEBUG] [VerthashMiner] [2021-02-03 19:10:58] WARN  Failed to get a "Proxy" option inside "Connection" section. Setting to ""
2021/02/03 19:10:58.368263 [DEBUG] [VerthashMiner] [2021-02-03 19:10:58] WARN  Failed to get a "Redirect" option inside "Connection" section. Setting to "true"
2021/02/03 19:10:58.369261 [DEBUG] [VerthashMiner] [2021-02-03 19:10:58] WARN  Failed to get a "LongPoll" option inside "Connection" section. Setting to "true"
2021/02/03 19:10:58.369261 [DEBUG] [VerthashMiner] [2021-02-03 19:10:58] WARN  Failed to get a "LongPollTimeout" option inside "Connection" section. Setting to "0"
2021/02/03 19:10:58.369261 [DEBUG] [VerthashMiner] [2021-02-03 19:10:58] WARN  Failed to get a "Scantime" option inside "Connection" section. Setting to "5"
2021/02/03 19:10:58.370260 [DEBUG] [VerthashMiner] [2021-02-03 19:10:58] WARN  Failed to get a "Retries" option inside "Connection" section. Setting to "-1"
2021/02/03 19:10:58.370260 [DEBUG] [VerthashMiner] [2021-02-03 19:10:58] WARN  Failed to get a "RetryPause" option inside "Connection" section. Setting to "5"
2021/02/03 19:10:58.370260 [DEBUG] [VerthashMiner] [2021-02-03 19:10:58] WARN  Failed to get a "ProtocolDump" option inside "Connection" section. Setting to "false"
2021/02/03 19:10:58.371259 [DEBUG] [VerthashMiner] [2021-02-03 19:10:58] INFO  Miner has been successfully configured! (Errors: 0, Warnings: 11)
2021/02/03 19:10:58.371259 [DEBUG] [VerthashMiner] [2021-02-03 19:10:58] INFO  Configured 1(CL) and 1(CUDA) workers
2021/02/03 19:10:58.376258 [DEBUG] [VerthashMiner] [2021-02-03 19:10:58] INFO  2 miner threads started, using Verthash algorithm.
**2021/02/03 19:10:58.376258 [DEBUG] [VerthashMiner] [2021-02-03 19:10:58] INFO  Starting Stratum on stratum+tcp://vtc.suprnova.cc:1776
2021/02/03 19:10:58.393247 [DEBUG] [VerthashMiner] [2021-02-03 19:10:58] ERROR cl_device(0):Failed to create verthash data buffer.
2021/02/03 19:10:58.393247 [DEBUG] [VerthashMiner] [2021-02-03 19:10:58] INFO  cl_device(0):Exiting worker thread id(0)...
2021/02/03 19:10:58.566358 [DEBUG] [VerthashMiner] [2021-02-03 19:10:58] INFO  Stratum difficulty set to 1
2021/02/03 19:10:59.070522 [DEBUG] [VerthashMiner] [2021-02-03 19:10:59] INFO  cu_device(0): WorkSize has been set to: 131072
2021/02/03 19:11:02.088912 [DEBUG] [VerthashMiner] [2021-02-03 19:11:02] ERROR cu_device(0):Device not responding. error code: 719. Terminaning worker...**
2021/02/03 19:11:02.088912 [DEBUG] [VerthashMiner] [2021-02-03 19:11:02] INFO  Exiting worker thread id(1)...
2021/02/03 19:11:02.088912 [DEBUG] [VerthashMiner] [2021-02-03 19:11:02] INFO  All worker threads have been exited.
2021/02/03 19:11:02.088912 [DEBUG] [VerthashMiner] [2021-02-03 19:11:02] INFO  WorkIO thread has been finished.
2021/02/03 19:11:02.088912 [DEBUG] [VerthashMiner] [2021-02-03 19:11:02] INFO  Waiting for worker threads to exit...
2021/02/03 19:11:02.088912 [DEBUG] [VerthashMiner] [2021-02-03 19:11:02] ERROR Stratum connection interrupted
2021/02/03 19:11:02.089910 [DEBUG] [VerthashMiner] [2021-02-03 19:11:02] DEBUG Stratum thread exit
2021/02/03 19:11:02.089910 [DEBUG] [VerthashMiner] [2021-02-03 19:11:02] INFO  Waiting for stratum thread to exit...
2021/02/03 19:11:02.089910 [DEBUG] [VerthashMiner] [2021-02-03 19:11:02] INFO  Freeing allocated memory...
2021/02/03 19:11:02.200864 [DEBUG] [VerthashMiner] [2021-02-03 19:11:02] INFO  Application has been exited gracefully.
2021/02/03 19:11:03.187295 [INFO] Miner [VerthashMiner.exe] stopped running.
2021/02/03 19:11:03.187295 [INFO] Restarting miner [VerthashMiner.exe]

Update: The new OCM RC8 doesn´t even start in my PC.

Update 2: OCM RC9 doesn´t open too.

Update 3: The OCM RC12 now opens but the problem in the debug persists, it might be something with verthash miner because i tried to use it and the config was done correctly and it doesn't work either, opens the window and immediately closes down.

**Comment by vertiond** [comment]
It seems that VerthashMiner is not able to properly create the verthash data buffer on your integrated graphics.  You would have to run VerthashMiner directly, generate a configuration file and comment out the line with your integrated graphics.  An enhancement to OCM would be the ability to enable/disable mining with integrated graphics.

**Comment by cryptopeach** [comment]
> It seems that VerthashMiner is not able to properly create the verthash data buffer on your integrated graphics. You would have to run VerthashMiner directly, generate a configuration file and comment out the line with your integrated graphics. An enhancement to OCM would be the ability to enable/disable mining with integrated graphics.

Everything is working now by doing what you said and i had to put a custom worksize, after this verthashminer is working perfect, thank you very much.
