### ISSUE TITLE
will not complete loading up 

### ISSUE THREAD

**Issue by zimmaj6** [vertcoin-project/one-click-miner-vnext#129]

**Comment by vertiond** [comment]
Could you elaborate?  If it reads something about verthash, please allow for a data file to be generated.  This can take up to 30 minutes or more depending on your PC specifications.

**Comment by zimmaj6** [comment]
Sorry for the delay. The page reads. Checks Failed: Failure to configure VerthashMiner.exe: fork/exec C\Users\billy\AppDate

**Comment by vertiond** [comment]
You may need to add an exclusion for One Click Miner to Windows Defender / antivirus.
