### ISSUE TITLE
Mining GPU P106-100 not detected

### ISSUE THREAD

**Issue by SalvorinFex** [vertcoin-project/one-click-miner-vnext#13]
I just tried the Alpha 23 release, on my Windows 10 64bit system, but rright after I create a password, it pops up with a screen saying that no GPUs were detected.

[debug.log](https://github.com/vertcoin-project/one-click-miner-vnext/files/3380230/debug.log)

This card does work with the regular release of OCM.

**Comment by gertjaap** [comment]
Fixed in https://github.com/vertcoin-project/one-click-miner-vnext/commit/4915d3d5b22512727c652b7c40cdaa2b3813ac36 , released in [Alpha 24](https://github.com/vertcoin-project/one-click-miner-vnext/releases/tag/0.1-alpha24)
