### ISSUE TITLE
Stuck fast

### ISSUE THREAD

**Issue by enorym** [vertcoin-project/one-click-miner-vnext#130]
installed and ran this is the result
![image](https://user-images.githubusercontent.com/32758728/106843337-a8cc8e80-665a-11eb-9565-e4b2879a0e91.png)

to actually work?

not that im aware of

install and launch

I got the last two versions which produced the same result

win10 asrock amd 5700 xt

N/A

**Comment by vertiond** [comment]
Please allow for a data file to be generated. This can take up to 30 minutes or more depending on your PC specifications.
