### ISSUE TITLE
The miner doesn't start properly

### ISSUE THREAD

**Issue by Ezylryb77** [vertcoin-project/one-click-miner-vnext#132]
When I start the miner, it asks for the password and then stays at 

                                  checks.verthash...

and nothing happens.

Is that normal and it just takes over half an hour to start?

I can reproduce the issue pretty reliably by just starting the program.

Version : OCM v2.0-rc9-5e22840

OS: Windows 10      GPU: Nvidia quadro K4200

**Comment by gertjaap** [comment]
@Ezylryb77 the verthash step can take a while depending on your CPU and disk speed. Half hour is not uncommon. [RC10](https://github.com/vertcoin-project/one-click-miner-vnext/releases/tag/2.0-rc10) adds a progress bar so you can follow it along. If you still have issues after trying that release, feel free to reopen the issue.
