### ISSUE TITLE
Checks failed: Failure to configure VerthashMiner.exe: exit status 3221225781

### ISSUE THREAD

**Issue by jasonhe54** [vertcoin-project/one-click-miner-vnext#135]
Checks failed: Failure to configure VerthashMiner.exe: exit status 3221225781

For it to work correctly so I can begin to mine

showed me an error message, image: https://prnt.sc/yk7x23

For me, every single time, in RC12 and in RC5.

v2.0-RC5 and RC12

Windows 10, Intel Integrated Graphics, cpu: i3 2310m, dual core 2.1ghz base.

-

-

debug.log pastebin: https://pastebin.com/MrjXe78Z
password to access: debug.log

**Comment by vertiond** [comment]
Intel HD Graphics are not supported.  Looks like this made it past that check.
