### ISSUE TITLE
Cannot Withdraw

### ISSUE THREAD

**Issue by entrepreneur916** [vertcoin-project/one-click-miner-vnext#136]
Cannot withdraw from miner

to be able to withdraw

Failed to send your coins
wallet password is required

Everytime I withdraw

OCM v2.0-rc8-21f1510

Windows 10/2080ti

**Comment by juyse** [comment]
The user solved the issue on discord using correct password for OCM. But I also had same error **even with correct password**, it showed same error as above, the transaction still sent successfully though. Maybe confusing to user.

**Comment by vertiond** [comment]
Coins are being sent with the correct address although the UI has an error.

**Comment by jk9898** [comment]
I had the same issue briefly. On a second try it seemed to resolve itself.

**Comment by vertiond** [comment]
This seems to be an issue with the response time of Insight.

**Comment by vertiond** [comment]
Backend being updated in RC14 should solve these issues.
