### ISSUE TITLE
Observations on "Spendable Balance" and sending coins

### ISSUE THREAD

**Issue by burley01** [vertcoin-project/one-click-miner-vnext#137]
Hard to prove this as a bug, but just observations from mining a while:
1.  Saved up over 50 VTC in "Spendable Balance"
2.  Sent coins to different address.  But only about 49 were sent.  (bug?)
3.  "Spendable Balance" now reads 0.
4.  Blockchain explorer show about 5 VTC balance (presumably from maturing coins still)

**Comment by vertiond** [comment]
Which pool was configured as your default during this?

**Comment by burley01** [comment]
P2pool.  But I think the p2pool link has changed at least once since early RC's

**Comment by gertjaap** [comment]
> Sent coins to different address. But only about 49 were sent. (bug?)

Network fees. Assuming you have been mining for a while and got a collection of tiny outputs, you have to pay network fees to send them. Can you link to the transaction that was sent?

OCM gets its balance from https://insight.vertcoin.org/. If you mine on p2pool the coins can indeed still need maturing - but that'd be visible in OCM too.

**Comment by burley01** [comment]
Hi Gertjapp,
Here is the link on Insight:  https://insight.vertcoin.org/address/VjyGghfxdtXo9Kck9rcDCxeFeXoqnNwf8t

Insight shows ~6.9 VTC balance, but other blockchain explorers (bitinfocharts, cryptoid) show the correct value of ~35 VTC.

Insight also shows a negative "Unconfirmed Txs Balance" for a while.  If the OCM wallet is reading from Insight, I wonder if this is really an Insight bug?

**Comment by burley01** [comment]
I chatted with James, and agrees that this could be some kind of Insight issue/bug.  There's no intention of this being fixed, so I just moved all the funds off the old wallet and will continue using OCM with the new one.  Closing this issue.

**Comment by burley01** [comment]
I know the issue is closed, but just wanted to add that this problem seems to be fixed after I deleted the wallet-testnet.db file and let the OCM regenerate it.  (after restarting the miner).  Thanks to the suggestion in discord to try this.
