### ISSUE TITLE
Linux client fatal error

### ISSUE THREAD

**Issue by tsdtsdtsd** [vertcoin-project/one-click-miner-vnext#142]
I got a fatal error twice in the last 12h or so, running _2.0-rc12 Linux binary_.
`fatal error: non-Go code set up signal handler without SA_ONSTACK flag`

Full trace: https://pastebin.com/UtPu14sH

PopOS 20.10
RTX 2070 Super

**Comment by vertiond** [comment]
In the meanwhile, I believe that compiling this on your own system should solve this error.
