### ISSUE TITLE
Checks failed

### ISSUE THREAD

**Issue by Gawnoster** [vertcoin-project/one-click-miner-vnext#144]
hello , now when i startup my miner it says Checks failed : remove C// .... Access is denied

please help

**Comment by Gawnoster** [comment]
Issue fixed thanks

**Comment by starbuck93** [comment]
I'm also getting this error with v2.0-RC12. Looks like the GUI crashes because VerthashMiner.exe is still running in the background. Killing the process with Task Manager and reopening OCM fixes it but I don't know why OCM crashes in the first place.
