### ISSUE TITLE
Failure to configure VerthashMiner: exit status 1

### ISSUE THREAD

**Issue by alexandrecastro1969** [vertcoin-project/one-click-miner-vnext#145]
Failure to configure VerthashMiner: exit status 1
 
![Captura de tela de 2021-02-07 13-13-15](https://user-images.githubusercontent.com/37750385/107633818-618c6200-6c47-11eb-87ab-fc0a6e703415.png)

 Every time I run the software

**Comment by vertiond** [comment]
You may need to add an exclusion to your antivirus / Windows Defender.

**Comment by alexandrecastro1969** [comment]
My OS is Linux Mint

**Comment by CryptoBeginner421** [comment]
having same issue on windows even after disabling virus software

**Comment by vertiond** [comment]
@alexandrecastro1969  Please paste your debug.log from %appdata%\vertcoin-ocm

**Comment by blanelegant** [comment]
Here is the output from running it from console, using KDE Neon 5.20:

`
$ ./vertcoin-ocm
2021/02/17 14:21:40.221242 OCM v2.0-rc13-d5f7a98-dirty Started up
2021/02/17 14:21:41.105410 [INFO] User IETF is en-US
2021/02/17 14:21:41.105493 [INFO] Matched tag is en-u-rg-uszzzz
2021/02/17 14:21:41.105504 [INFO] Returning locale en
2021/02/17 14:21:41.148406 [INFO] Checking wallet..
2021/02/17 14:21:41.148533 [INFO] Initializing wallet VneQkhQG9QoHMK2rhJVgyPR5iXKrdJYyqg
2021/02/17 14:21:41.148630 [INFO] Wallet initialized: 1
2021/02/17 14:21:42.948390 [DEBUG] GPU [Intel Corporation UHD Graphics 630 (Mobile)] matched regex [.*Intel.*]
2021/02/17 14:21:42.948412 [DEBUG] GPU [NVIDIA Corporation GP107M [GeForce GTX 1050 Ti Mobile] (rev a1)] matched regex [.*NVIDIA.*]
2021/02/17 14:21:42.994249 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/02/17 14:21:42.994322 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/02/17 14:21:42.994367 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/02/17 14:21:42.994390 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/02/17 14:21:42.994412 [DEBUG] Found compatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/02/17 14:21:42.994438 [DEBUG] Not adding already present multi-gpu binary [VerthashMiner] again
2021/02/17 14:21:42.994455 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/02/17 14:21:42.994469 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/02/17 14:21:42.994486 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/02/17 14:21:42.994504 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/02/17 14:21:42.994521 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/02/17 14:21:42.994538 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/02/17 14:21:42.994594 [DEBUG] [Miner linux/3]Daemon file already exists
2021/02/17 14:21:43.017652 [DEBUG] [Miner linux/3]Daemon file is available and correct
2021/02/17 14:21:43.017674 [DEBUG] [Miner linux/3]Removing unpack directory
2021/02/17 14:21:43.018595 [DEBUG] [Miner linux/3](Re)creating unpack directory
2021/02/17 14:24:10.327117 [DEBUG] Launching /root/.vertcoin-ocm/miners/unpacked-a629cf6f229760df342a29829ccf7ca9f717640a50a9eeeddf16bcc7f16b9aba/VerthashMiner-0.6.2-CUDA11-linux/VerthashMiner [--gen-conf /root/.vertcoin-ocm/verthash-miner-tmpl.conf]
2021/02/17 14:24:10.334403 [DEBUG] [VerthashMiner] [2021-02-17 14:24:10] WARN  Failed to find any OpenCL platforms.
2021/02/17 14:24:10.334824 [DEBUG] [VerthashMiner] [2021-02-17 14:24:10] WARN  Failed to initialize CUDA. error code: 35
2021/02/17 14:24:10.334836 [DEBUG] [VerthashMiner] [2021-02-17 14:24:10] WARN  Both OpenCL and CUDA modules are not available! Exiting...
`

![Screenshot_20210217_143601](https://user-images.githubusercontent.com/9562125/108258003-8f811300-712d-11eb-8a95-6ae7485c2068.png)

**Comment by vertiond** [comment]
@blanelegant You may need to add an exclusion to your antivirus / Windows Defender.

**Comment by ramz33** [comment]
i have latest Linux Mint 20 and i have same error 1, try to enable Secure Boot in BIOS, install drivers with opencl and it should work:)
