### ISSUE TITLE
Failure check at 99%

### ISSUE THREAD

**Issue by LectrononGG** [vertcoin-project/one-click-miner-vnext#146]
"Failure to configurate VerthashMiner.exe: fork/exec C:\Users\solo1\... : Insufficient system resources exist to complete the requested service"

I dont why it says that. I have Nvidia Gforce 2070 RTX, 16 GB.

![image](https://user-images.githubusercontent.com/74851480/107698485-3a9b5380-6c7a-11eb-8180-8193d7e64dd0.png)
![image](https://user-images.githubusercontent.com/74851480/107698510-4424bb80-6c7a-11eb-88f9-70cf66e8b944.png)

**Comment by vertiond** [comment]
You may need to add an exclusion to your antivirus / Windows Defender.
