### ISSUE TITLE
OCM not mining

### ISSUE THREAD

**Issue by YahyaMurad** [vertcoin-project/one-click-miner-vnext#147]
So I downloaded OCM, and when I opened the interface it showed me my balance and hashrate, both were at 0,
I tried pointing it to another pool but nothing worked, I tried re-installing as well.

I downloaded the latest version (2.0) from github, and turned off my antivirus before doing so.

I have windows, and an RTX 2070.

There is a screenshot provided
![Screenshot 2021-02-12 124704](https://user-images.githubusercontent.com/59206482/107747134-6bd65b00-6d30-11eb-8972-37ce600d82f7.png)

**Comment by vertiond** [comment]
Please paste your debug.log from %appdata%\vertcoin-ocm

This may also be an issue with your network / router settings.

**Comment by YahyaMurad** [comment]
nevermind vertiond I solved the issue, it was a problem with my network and a friend helped me fix it, I will now proceed to close the issue
