### ISSUE TITLE
Miner does not show GPU as compatable 

### ISSUE THREAD

**Issue by amygith** [vertcoin-project/one-click-miner-vnext#148]
I have downloaded the miner and tried to use it, but it says that the GPU is not compatible. I am using a geforce 1060 6g, which should be compatible. 

I have gone into the appdata and cleared the setting for my Vertcoin miner, but it still shows that I have no compatible GPU. What can  I do to resolve this issue and run my 1060 6g GPU?

**Comment by cschar** [comment]
same here:

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:12:52_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.243

nvidia-smi
Sat Feb 13 08:35:46 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 441.12       Driver Version: 441.12       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070   WDDM  | 00000000:01:00.0  On |                  N/A |
| 29%   29C    P8    23W / 225W |    757MiB /  8192MiB |     33%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by vertiond** [comment]
In the meanwhile, you could try running VerthashMiner directly.

https://github.com/CryptoGraphics/VerthashMiner/

**Comment by vertiond** [comment]
Please make sure your drivers are up to date.  Similar issue here: https://github.com/vertcoin-project/one-click-miner-vnext/issues/111
Closing in lieu of that issue tracker which notes the same issue with a geforce 1060 6gb.
