### ISSUE TITLE
Unable to get the mining value

### ISSUE THREAD

**Issue by sreerajklm10** [vertcoin-project/one-click-miner-vnext#151]
Currently my system is mining at 55khs and the balance is not getting updated
Expected result is it should show the mining value

the mining balance is showing as 000000 from last 2 days 
![image](https://user-images.githubusercontent.com/79042735/107874371-3328b400-6edf-11eb-98e0-f556507b4086.png)

Open one click miner, it starts mining automatically and the balance shows 0

From the vertcoin.org site, which re directed to github- Version is OCM v2.0-rc12-e88c4e4

windows 10, pro version, amd radeon r7 graphic card

**Comment by vertiond** [comment]
That hash rate is probably too low to find a share in the P2Pool sharechain.  It is recommended that you use the default pool, Hashalot, or Suprnova with a hash rate of less than 100 kH/s.
