### ISSUE TITLE
miner works for a bit then crashes gives error.

### ISSUE THREAD

**Issue by civicchump** [vertcoin-project/one-click-miner-vnext#155]
it worked for about a few days then now works for a few hours then does this i dunno if the images are working. rc12 version gtx 680.

![Untitled](https://user-images.githubusercontent.com/79075286/107912735-ee6b4000-6f13-11eb-9010-c5346236aa13.png)
![Untitled1](https://user-images.githubusercontent.com/79075286/107912760-f5924e00-6f13-11eb-8643-a0435cc55cb5.png)
![Untitled2](https://user-images.githubusercontent.com/79075286/107912762-f75c1180-6f13-11eb-845e-e0d35235e2e4.png)
![Untitled3](https://user-images.githubusercontent.com/79075286/107912770-faef9880-6f13-11eb-9244-36713656f236.png)

**Comment by ac0uk** [comment]
@civicchump The miner is still running, open task manager and end VerthashMiner.exe then restart One Click Miner

**Comment by vertiond** [comment]
It seems that the VerthashMiner process doesn't always finish upon close.
