### ISSUE TITLE
Send to OCM wallet address

### ISSUE THREAD

**Issue by goddardnet** [vertcoin-project/one-click-miner-vnext#157]
I am a NOOB and I accidentally cut-and-paste my ocm wallet address into 'send coins'

I would expect OCM to not allow the transfer?

My balance ratcheted up x 2 ?

Now my legit 'send coin' transfers are displaying in Insight but not in mainnet but not confirmed - not sure if this is related???

v0.12-rc12
Win10

**Comment by vertiond** [comment]
OCM will allow the transfer and your balance will stay the same minus the default transaction fee.  Your balance will be updated eventually as Insight refreshes.  The Insight server has been overloaded with requests and may take some time to update.  Your balance on another explorer such as https://chainz.cryptoid.info/vtc/ will accurately reflect your balance.

**Comment by goddardnet** [comment]
Insight is not sending to the main blockchain? 
My private wallet address says 10 vtc - the same address on Insight says 14 which includes the 4 vtc mined with ocm? 

Is there a delay in posting to the main blockchain and if so do you know how long ?
