### ISSUE TITLE
OCM GUI displayed in Danish when Windows display language is English

### ISSUE THREAD

**Issue by Pluppo** [vertcoin-project/one-click-miner-vnext#158]
### Describe the issue
OCM is using Danish language

### What behavior did you expect?
My Windows display language is set to English (United States), although I have Norwegian (Bokmål) as Regional format.
I was hoping to see OCM in English, or at least in Norwegian. It should not pick Danish.

### What was the actual behavior (provide screenshots if the issue is GUI-related)?
![image](https://user-images.githubusercontent.com/43924988/107999226-36a76280-6fe7-11eb-8f87-86b93f235f40.png)
![image](https://user-images.githubusercontent.com/43924988/107999245-4161f780-6fe7-11eb-9328-f3521d7fde7a.png)

### How reliably can you reproduce the issue, what are the steps to do so?
Issue has been here since I started using OCM RC5, still the same issue on current RC13

### What version of the One Click Miner are you using, where did you get it (website, self-compiled, etc)?
vertcoin-ocm-2.0-rc13-windows-x64, from GitHub

### What type of machine are you observing the error on (OS/GPU type)?
Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎25.‎10.‎2020
OS build	19042.804
Experience	Windows Feature Experience Pack 120.2212.551.0

### Any extra information that might be useful in the debugging process.
C:\WINDOWS\system32>dism /online /get-intl

Deployment Image Servicing and Management tool
Version: 10.0.19041.746

Image Version: 10.0.19042.804

Reporting online international settings.

Default system UI language : en-US
System locale : en-US
Default time zone : W. Europe Standard Time
Active keyboard(s) : 0414:00000414, 0409:00000409
Keyboard layered driver : PC/AT Enhanced Keyboard (101/102-Key)

Installed language(s): en-US
  Type : Fully localized language.
Installed language(s): nb-NO
  Type : Partially localized language, MUI type.
  Fallback Languages en-US

The operation completed successfully.

**Comment by RandomVersion** [comment]
same, wrong language

**Comment by GuardianLiarus** [comment]
A dev told me that Vertcoin OCM's language is based off your Keyboard Layount, it's common for neighbhoring countries to have the same keyboard layouts, as an exemple, Belgians use a french keyboard layout, and hence will have OCM in french even if they don't speak it.

**Comment by vertiond** [comment]
This is expected behavior of the program currently and will be resolved by https://github.com/vertcoin-project/one-click-miner-vnext/issues/433
Closing this in lieu of the feature request.
