### ISSUE TITLE
High hash rate (2 plus GH/s)

### ISSUE THREAD

**Issue by runawaycyborg** [vertcoin-project/one-click-miner-vnext#159]
Expected Earnings is extremely high. It's stating that I'm mining 2-5 GH/s of VTC and the spendable amount is 0 VTC after a couple of hours of running OCM.

 

 
![Untitled](https://user-images.githubusercontent.com/79121031/108005383-93deec00-6fc6-11eb-9070-c47715b390cb.png)

 https://vertcoin.org/mining-setup/ - One Click Miner vNext 2.0-rc13

 Windows 10/geforce gtx 770

-->

**Comment by Alleco87** [comment]
Same here

**Comment by vertiond** [comment]
You can try running https://github.com/CryptoGraphics/VerthashMiner directly and modifying the WorkSize but other than that, it doesn't seem these cards are compatible even though they technically meet the specifications found in the VerthashMiner README.  This would be an issue with the upstream VerthashMiner.
