### ISSUE TITLE
GPU driver crash after overclocking

### ISSUE THREAD

**Issue by Kangaxx1** [vertcoin-project/one-click-miner-vnext#16]
**<-- Describe the issue -->**
After extreme overclocking of the GPU core clock causing the driver/miner to crash and reload OCM continues to show the last reported hash-rate but the miner is no longer running

**<--- What behaviour did you expect? -->**
An error on the OCM GUI or automatic restart of the miner

**<--- How reliably can you reproduce the issue, what are the steps to do so? -->**
Reproducible results by overclocking the GPU core clock too high. 

**<-- What version of the One Click Miner are you using, where did you get it (website, self-compiled, etc)? -->**
0.1-alpha25 pre-compiled downloaded direct from Github with Cryptodredge enabled

**<-- What type of machine are you observing the error on (OS/GPU type)? -->**
Windows 10
1060 3gb x 2

**<-- For the GUI-related issue on Linux provide names and versions of a distro, a desktop environment and a graphical shell (if relevant). -->**
N/A

**<-- Any extra information that might be useful in the debugging process. -->**
Clicking the 'stop mining' GUI button and starting mining again reverted 
The below line repeats every few minutes with an updated timestamp. No indication that the 
`2019/07/18 18:27:12.324748 [INFO] Updating balance...`

**Comment by gertjaap** [comment]
Thanks for reporting this. The process monitoring of the miner process (and restarting it, checking for rapid fails, etc) is something that can use work. I'll be sure to tackle this.

**Comment by gertjaap** [comment]
Fixed this in https://github.com/vertcoin-project/one-click-miner-vnext/commit/f3a98dfef967e0148f1f2b88820b87f851f6d1dc
