### ISSUE TITLE
missing transaction receipt

### ISSUE THREAD

**Issue by sgreen2020** [vertcoin-project/one-click-miner-vnext#161]
When sending my balance to a remote wallet, the one click miner fails to provide a transaction receipt and hangs. The coin is sent without a transaction receipt which is required at the other end of the transaction>
Previously, the program didn't hang when sending the coin balance and provided the transaction receipt

No screenshots were taken but the process of transferring the wallet balance hangs without confirming the process was completed

This has happened twice on two separate pc;s within 10 minutes of each transaction

OCM v2.0-rc1d5f7a98

Windows 10 64 bit nvidia rtx 3090

 NA

**Comment by vertiond** [comment]
Please update to the latest version of OCM
