### ISSUE TITLE
Could not find compatible miner binaries

### ISSUE THREAD

**Issue by tgz666123** [vertcoin-project/one-click-miner-vnext#162]
Could not find compatible miner binaries
Could not find compatible miner binaries
Could not find compatible miner binaries

**Comment by vertiond** [comment]
What is your GPU?

**Comment by tgz666123** [comment]
> 您的GPU是什么？
I have two computer, the system is win10, and one GPU is 1080ti. A GPU is 1050ti, which is the same problem,

**Comment by vertiond** [comment]
Are the latest drivers installed for your GPUs?

**Comment by tgz666123** [comment]
是最新的，用你们现在最新的版本也报错
It's the latest version. It's wrong to use your latest version
