### ISSUE TITLE
Vtc Missing

### ISSUE THREAD

**Issue by heaven2598** [vertcoin-project/one-click-miner-vnext#163]
Vtc was pending from pool, closed the app, when reopened no vtc was available (neither pending from pool)

to get the expected vtc that was pending from pool

Vtc is missing as in now it shows 0.0000000

I don`t know and i don`t wanna find out since it seems that mining is obsolete then?

vertcoin.org -> github (version is OCM v2.0-rc13-d5f7a98)

Win 10, Gpu gtx 1660 4gb

**Comment by vertiond** [comment]
Which pool?  Pending payout is specific to each pool so if the pool happened to switch then that would be an expected result.

**Comment by vertiond** [comment]
The backend Insight server which fetches Spendable Balance and Expected Earnings (24h) has been having stability issues.  It is back up now and the backend has been updated in RC14.
