### ISSUE TITLE
One-click-miner

### ISSUE THREAD

**Issue by secinv** [vertcoin-project/one-click-miner-vnext#168]
"Failure to configure VerthashMiner: exit status 127" - how to solve the issue

**Comment by vertiond** [comment]
You may need to add an exclusion to your antivirus / Windows Defender.

**Comment by secinv** [comment]
Thanks, but I use UBUNTU 20.04

**Comment by secinv** [comment]
In fact, the problem arose after I reinstalled Ubunto. Initially, the system worked normally, but after I reinstalled the OS, this problem appeared. I guess it has to do with the fact that I already have  a VTC wallet and my GPU has already mining.

**Comment by vertiond** [comment]
Please paste your debug.log from `~/.vertcoin-ocm`

**Comment by secinv** [comment]
Thanks, but I'm not sure I figured out exactly how to proceed. Can you explain in more detail, please. Thank you again

**Comment by vertiond** [comment]
`cd ~/.vertcoin-ocm`
`cat debug.log`
Copy and paste as much here as you can

**Comment by martin-kubik** [comment]
Hi, the same problem here. Log and screenshot are attached.

System:
Ubuntu Ubuntu 20.04.1 LTS
GeForce GTX 780 (3 GB)

[debug.log](https://github.com/vertcoin-project/one-click-miner-vnext/files/6055043/debug.log)

![Screenshot from 2021-02-27 18-59-18](https://user-images.githubusercontent.com/3786527/109395716-1f913a80-792e-11eb-9237-42897acbca83.png)

**Comment by P0pMan20** [comment]
The way I solved this issue on my Arch system was by installing the OpenCL ICD loader and the appropriate OpenCL runtime for my GPU as per [this](https://wiki.archlinux.org/index.php/GPGPU). See these for potential Ubuntu instructions [http://manpages.ubuntu.com/manpages/xenial/man7/libOpenCL.7.html](http://manpages.ubuntu.com/manpages/xenial/man7/libOpenCL.7.html) [https://askubuntu.com/questions/1032430/opencl-with-nvidia-390-on-ubuntu-18-04](https://askubuntu.com/questions/1032430/opencl-with-nvidia-390-on-ubuntu-18-04)

**Comment by martin-kubik** [comment]
Thank you @P0pMan20. In my case, update to OCM 2.0 Final Release solved the problem.
