### ISSUE TITLE
Cannot Move Spendable to Paper Wallet

### ISSUE THREAD

**Issue by SnakerZ** [vertcoin-project/one-click-miner-vnext#171]
I went to cash out my 'spendable balance' from Vertcoin. It said error and the amound totally vanished. 
I was cashing out from the one-click miner to a paper wallet. All details were correct.

The amount to appear in my paper wallet. 

There was an error that is now in my debug files.

Straight from sources.

Windows 10 - Nvidia, Geforce Windforce 980XT

**Comment by vertiond** [comment]
This is an issue with the Insight server which fetches balances.  Try clicking the refresh button to the left of Spendable Balance.

**Comment by SnakerZ** [comment]
Previously it updated and reappeared.
Not this time.

**Comment by vertiond** [comment]
The backend Insight server which fetches Spendable Balance and Expected Earnings (24h) was down briefly yesterday.  It is back up now and the backend has been updated in RC14.
