### ISSUE TITLE
checks failed message for one-click-miner

### ISSUE THREAD

**Issue by slyhog** [vertcoin-project/one-click-miner-vnext#172]
when I go to run the program I get a red error message that says ..."one or more of your miner bianaries is showing rapid failures" I click the debug, same message.
I expected it to start running

it happens every time

the most recent downloaded from the GIT hub

ASUS intelcore i7-4790, integrated graphics

]

**Comment by gertjaap** [comment]
Integrated graphics are not good enough to mine Verthash on. Some IGs work, others don't have enough video ram to work properly (Verthash requires ~2GB). So this is not something that can be fixed. You need a better GPU.
