### ISSUE TITLE
What's behind checks.verthash

### ISSUE THREAD

**Issue by DrPaprikaa** [vertcoin-project/one-click-miner-vnext#174]
When first setting up the miner, the 'check.verthash' progress bar can take a long time to complete (2 hours on my machine and not finished), but the user is left in the dark about what is processed. Is it a download ? What files are generated and where on my computer ?
I could not find info on what is going on in the backend, would you be so kind as to enlightening me please ?

**Comment by gertjaap** [comment]
It's generating the Verthash datafile. Unfortunately, not all localizations are updated, so for some languages it shows placeholders.

**Comment by DrPaprikaa** [comment]
Thank you for your answer. Can you elaborate on what this file is ?
