### ISSUE TITLE
Available amount different from suprnova available amount (app language is portuguese)

### ISSUE THREAD

**Issue by Intuiti0n** [vertcoin-project/one-click-miner-vnext#175]
![vtc](https://user-images.githubusercontent.com/26116287/108339170-01f5ff80-71cf-11eb-8aa9-82f6248d476c.png)

After checking with some people on discord who told me to insert address to check pool stats of suprnova, i realised that there is .59 available but on the OCM app still shows zero, after day and half of mining 

I expected the available amount to be equal to the one on the pool

![vtc2](https://user-images.githubusercontent.com/26116287/108339495-6618c380-71cf-11eb-872d-a3e3a4f100af.png)

vertcoin-ocm-2.0-rc13-windows-x64

Windows 10 Home SO compilation 19042.804 , GPU is Sapphire AMD RX 580 8GB

[debug.log](https://github.com/vertcoin-project/one-click-miner-vnext/files/6001872/debug.log)
![vtc](https://user-images.githubusercontent.com/26116287/108339805-c9a2f100-71cf-11eb-98f6-74415cf2664d.png)
![vtc2](https://user-images.githubusercontent.com/26116287/108339808-ca3b8780-71cf-11eb-8df2-9512b1798900.png)

**Comment by luckiesjohnny** [comment]
I can confirm this issue.
I started mining with One Click Miner (RC13) today, 6 hrs ago.
Hashalot.net show my confirmed balance, but the one click miner gui does not update the confirmed balance after hours.
ppl in reddit reported more than 2 days no update on confirmed balance.

**Comment by luckiesjohnny** [comment]
> I can confirm this issue.
> I started mining with One Click Miner (RC13) today, 6 hrs ago.
> Hashalot.net show my confirmed balance, but the one click miner gui does not update the confirmed balance after hours.
> ppl in reddit reported more than 2 days no update on confirmed balance.

It is working now.
