### ISSUE TITLE
Lost Vertcoins

### ISSUE THREAD

**Issue by kevthedm** [vertcoin-project/one-click-miner-vnext#180]
While using the Vertcoin One-Click Miner, I went into settings and changed the mining pool from Hashalot to Supernova. When I saved and restarted, all of my Vertcoins (about 3.8) had vanished. Is there anything I can do to get them back?

 OCM v2.0 rc13 downloaded from github.com

 Windows 10, GTX 2060

**Comment by DNA64** [comment]
Copy your wallet address from OCM and paste it into this site to see your wallet balance.
https://chainz.cryptoid.info/vtc/

There is a bug causing your wallet to show a balance of 0 (You also can't send coins, at least till your balance increases I assume).

**Comment by vertiond** [comment]
The backend Insight server which fetches Spendable Balance and Expected Earnings (24h) was down briefly yesterday.  It is back up now and the backend has been updated in RC14.
