### ISSUE TITLE
~+inf VTC and 0.00000VTC balance

### ISSUE THREAD

**Issue by Darthreign** [vertcoin-project/one-click-miner-vnext#181]
Benefits are no more shown and account balance is at 0 and I have VTC on it :
VuSToSQaexxSWtvGWEampTMvDdnLSi3nn8
![image](https://user-images.githubusercontent.com/1765485/108415827-4bc20280-722e-11eb-9ef1-c504c3075182.png)
![image](https://user-images.githubusercontent.com/1765485/108415949-6a27fe00-722e-11eb-8843-b3fb9e0164a1.png)
[debug.log](https://github.com/vertcoin-project/one-click-miner-vnext/files/6005639/debug.log)

debug.log is attached 👍

**Comment by ricedana** [comment]
what is the fix for this issue

**Comment by byteofreality** [comment]
I am getting the same issues. My rc12 would not load after crash, so I downloaded rc13. Now I am getting what you are getting. **If this should be a new thread, let me know.** 

~+Inf VTC (230.97 kH/s) is what the GUI is showing. No VTC earned but I should have a balance earned. 

I am showing VerthashMiner is running. 

2021/02/18 18:21:42.040266 [DEBUG] [VerthashMiner] [2021-02-18 18:21:42] INFO  cu_device(0): hashrate: 229.48 kH/s
2021/02/18 18:21:42.040266 [DEBUG] Device IDX: 0
2021/02/18 18:21:46.601031 [DEBUG] [VerthashMiner] [2021-02-18 18:21:46] INFO  cu_device(0): hashrate: 231.04 kH/s
2021/02/18 18:21:46.601031 [DEBUG] Device IDX: 0
2021/02/18 18:21:51.134062 [DEBUG] [VerthashMiner] [2021-02-18 18:21:51] INFO  cu_device(0): hashrate: 231.31 kH/s
2021/02/18 18:21:51.134062 [DEBUG] Device IDX: 0
2021/02/18 18:21:55.253087 [DEBUG] [VerthashMiner] [2021-02-18 18:21:55] INFO  cu_device(0): hashrate: 229.22 kH/s
2021/02/18 18:21:55.253087 [DEBUG] Device IDX: 0
2021/02/18 18:21:59.825261 [DEBUG] [VerthashMiner] [2021-02-18 18:21:59] INFO  cu_device(0): hashrate: 228.58 kH/s
2021/02/18 18:21:59.825261 [DEBUG] Device IDX: 0
2021/02/18 18:22:04.360016 [DEBUG] [VerthashMiner] [2021-02-18 18:22:04] INFO  cu_device(0): hashrate: 228.89 kH/s
2021/02/18 18:22:04.360016 [DEBUG] Device IDX: 0
2021/02/18 18:22:08.886070 [DEBUG] [VerthashMiner] [2021-02-18 18:22:08] INFO  cu_device(0): hashrate: 228.87 kH/s
2021/02/18 18:22:08.886070 [DEBUG] Device IDX: 0
2021/02/18 18:22:13.406314 [DEBUG] [VerthashMiner] [2021-02-18 18:22:13] INFO  cu_device(0): hashrate: 231.05 kH/s
2021/02/18 18:22:13.406314 [DEBUG] Device IDX: 0
2021/02/18 18:22:17.949365 [DEBUG] [VerthashMiner] [2021-02-18 18:22:17] INFO  cu_device(0): hashrate: 231.42 kH/s
2021/02/18 18:22:17.949365 [DEBUG] Device IDX: 0

**Comment by vertiond** [comment]
The backend Insight server which fetches Spendable Balance and Expected Earnings (24h) was down briefly yesterday.
