### ISSUE TITLE
OCM Dies and upon restart says Access is Denied

### ISSUE THREAD

**Issue by TackyBrad** [vertcoin-project/one-click-miner-vnext#182]
Hi guys. My OCM won't stay alive for more than a few hours, at most 8-10, before randomly ending itself (or otherwise being ended by my PC) and upon trying to restart the .exe, it tells me "access is denied" and fails the check (path of failed check is the appdata folder ending at the .exe there). The only remedy is to fully restart the PC.

The issue is reliably replicated every few hours, however there is nothing I know to do to cause it. Typically no one is using the PC when it happens.

This is on the latest version of OCM, release rc13.

The PC is running Windows 10 Pro (unlicensed directly from windows), Nvidia 3080 (Gigabyte Gaming OC)

From the discord, people have told me this is an antivirus issue. Here are steps I have taken:
Checked for any running vertcoin process in taskmanager (none found)

Anti-virus overview: This is a fresh PC build. The only anti-virus is Windows Defender.

1) I have allowed both apps through the firewall
2) I have excluded the appdata->roaming->vertcoin-OCM folder from defender (as well as pretty much every sub folder just to be thorough)
3) I have fully excluded the entire folder found in the place I extracted the download.
4) In discord there is a pin for excluding the folder using a command line in windows powershell, I have also completed this step

Here is a paste of what appears to be the death error:

```
2021/02/18 16:02:15.466000 [ERROR] runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0xf56a40, 0xc00033a000, 0x442)
	c:/go/src/runtime/debug/stack.go:24 +0xa5
main.main.func1()
	C:/src/one-click-miner-vnext/main.go:29 +0x18b
panic(0xc60940, 0xbe1f50)
	c:/go/src/runtime/panic.go:969 +0x1c7
github.com/wailsapp/wails/lib/renderer/webview._webviewDispatchGoCallback(0x9318)
	C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview/webview.go:356 +0xc1
github.com/wailsapp/wails/lib/renderer/webview._cgoexpwrap_d1ad623198bc__webviewDispatchGoCallback(0x9318)
	_cgo_gotypes.go:301 +0x32
github.com/wailsapp/wails/lib/renderer/webview._Cfunc_CgoWebViewLoop(0x1a41b5d7260, 0x1a400000001, 0x0)
	_cgo_gotypes.go:174 +0x54
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Loop.func1(0xc000006090, 0xc000000001, 0x0)
	C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview/webview.go:279 +0x65
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Loop(0xc000006090, 0x1, 0x1)
	C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview/webview.go:279 +0x3b
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Run(0xc000006090)
	C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview/webview.go:283 +0x37
github.com/wailsapp/wails/lib/renderer.(*WebView).Run(0xc00007c240, 0xf66640, 0xc00007c240)
	C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview.go:232 +0x1ce
github.com/wailsapp/wails.(*App).start(0xc00014c180, 0x0, 0x0)
	C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/app.go:145 +0x5ab
github.com/wailsapp/wails.(*App).Run(0xc00014c180, 0xcde9a0, 0xc00024a000)
	C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/app.go:93 +0xba
main.main()
	C:/src/one-click-miner-vnext/main.go:90 +0x6ae

```

Thank you

**Comment by vertiond** [comment]
I think this is related to having a previous running instance of VerthashMiner.exe running.  It seems that the VerthashMiner process doesn't always finish upon close and has been marked as a bug.
Same issue as https://github.com/vertcoin-project/one-click-miner-vnext/issues/141
