### ISSUE TITLE
keyfile.hex not found

### ISSUE THREAD

**Issue by Hypertyz** [vertcoin-project/one-click-miner-vnext#195]
2021/02/22 01:17:24.368330 OCM v2.0-rc15-84ddd32 Started up
2021/02/22 01:17:24.370330 [INFO] Error reading keyfile: open C:\Users\User_Name\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2021/02/22 01:17:24.370330 [INFO] Error reading keyfile: open C:\Users\User_Name\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.

**Comment by vertiond** [comment]
You may need to add an exclusion to your antivirus / Windows Defender.

**Comment by gertjaap** [comment]
Are you actually noticing problems? On first startup this error is expected, since the wallet still has to be created.

**Comment by Hypertyz** [comment]
I have already excluded the .exe file from antivirus / Windows Defender. The problem still persists. When I open `vertcoin-ocm.exe`, the GUI is just blank and nothing happens. The log file just says the same error every time I close and open the file. 

![image](https://user-images.githubusercontent.com/56047053/108697020-98ddf700-7502-11eb-9411-0f686b3d7481.png)

**Comment by vertiond** [comment]
What OS are you running?

**Comment by Hypertyz** [comment]
![image](https://user-images.githubusercontent.com/56047053/108747987-5d611e00-753e-11eb-906a-2631671b5de2.png)

**Comment by PatNorSoft** [comment]
I have the same error except i have this comment on screen

![error_ocm](https://user-images.githubusercontent.com/8276384/109051499-9b7a5100-76a8-11eb-88a6-a08c25b0fcb0.png)

inside i have the keyfile.hex not found here also my folder content
![foldercontent](https://user-images.githubusercontent.com/8276384/109051770-daa8a200-76a8-11eb-94f5-a57916483ab4.png)

r

**Comment by Hypertyz** [comment]
there is no keyfile.hex for my case

**Comment by vzeller** [comment]
+1 for the original error .. no keyfile.hex no content on black background

**Comment by vertiond** [comment]
Please paste your debug.log from %appdata%\vertcoin-ocm @vzeller 
@Hypertyz do you have any additional 3rd-party antivirus?

**Comment by rickgroen** [comment]
Hi, I am having the same issue on Ubuntu 18.04, and I can reproduce the issue on 20.04 also.
In terms of the output of the debug.log: It is the exact same as the orginal post from @Hypertyz, and the log hangs from there. One additional comment is that one-click-miner does expend resources according htop. The screen remains black though.
Let me know if I can provide more information.

**Comment by JacobHin2** [comment]
Have you tried running as admin sometimes the app just can't access the location or something idk. I just installed the stable release

**Comment by dannythunder** [comment]
> Are you actually noticing problems? On first startup this error is expected, since the wallet still has to be created.

Maby add information on screen instead of white screen? I got the same issue as TS, but my wallet is being synced. So hopefully that will fix it.

**Comment by edmorbius** [comment]
Ah.  I am havng this same issue on Arch Linux.  Blank screen in the GUI and an error in the log saying the keyfile.hex cannot be found.  This is a first launch of the OCM.  The keyfile.hex is missing from ~/.vertcoin-ocm.

**Comment by AdverseMiller** [comment]
> Ah. I am havng this same issue on Arch Linux. Blank screen in the GUI and an error in the log saying the keyfile.hex cannot be found. This is a first launch of the OCM. The keyfile.hex is missing from ~/.vertcoin-ocm.

Same. I'm on Artix Linux and experiencing the same issue.

**Comment by vertiond** [comment]
Might be solved by https://github.com/vertcoin-project/one-click-miner-vnext/pull/298

**Comment by rickgroen** [comment]
#298 fixed my issue, I no longer get a blank screen.

**Comment by rickgroen** [comment]
#298 Fixed my problems. I no longer get a blank screen.

**Comment by Hypertyz** [comment]
I found the reason why ```vertcoin-ocm.exe``` GUI showed up blank. There is a feature on windows 10 that blocks JavaScript everywhere on your PC except for internet browers, it should be disable by default but for some reasons I turned it on. To disable it, just search for Internet Options, go to Security tab and click Custom levels, scroll down and you should see the Scripting option as seen in the picture below.

![image](https://user-images.githubusercontent.com/56047053/118474895-de7a1c80-b70b-11eb-9659-25b5b8785273.png)

**Comment by philm001** [comment]
I am on windows 10 and I am getting the same issue. I have the latest release version (non-beta) and ran under Admin. I am attaching a copy of my debug log. Can confirm that the keyfile.hex exists in my appdata folder. 

I also checked the scripting and it is enabled for me.

[debug.log](https://github.com/vertcoin-project/one-click-miner-vnext/files/6494478/debug.log)

**Comment by philm001** [comment]
Any update on this?

**Comment by nobodyatandnothing** [comment]
> > Ah. I am havng this same issue on Arch Linux. Blank screen in the GUI and an error in the log saying the keyfile.hex cannot be found. This is a first launch of the OCM. The keyfile.hex is missing from ~/.vertcoin-ocm.
> 
> Same. I'm on Artix Linux and experiencing the same issue.

same issue on Clear Linux 35210
```
$ vertcoin-ocm

2021/11/07 12:24:23.189722 OCM v2.0-218788a Started up
2021/11/07 12:24:23.189778 [INFO] Error reading keyfile: open /home/user_name/.vertcoin-ocm/keyfile.hex: no such file or directory
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
```
![Screenshot from 2021-11-07 11-24-35](https://user-images.githubusercontent.com/91722596/140639720-6d3a2eee-a675-4642-9ed8-8dd166c222fc.png)

**Comment by nobodyatandnothing** [comment]
> > > Ah. I am havng this same issue on Arch Linux. Blank screen in the GUI and an error in the log saying the keyfile.hex cannot be found. This is a first launch of the OCM. The keyfile.hex is missing from ~/.vertcoin-ocm.
> > 
> > 
> > Same. I'm on Artix Linux and experiencing the same issue.
> 
> same issue on Clear Linux 35210
> 
> ```
> $ vertcoin-ocm
> 
> 2021/11/07 12:24:23.189722 OCM v2.0-218788a Started up
> 2021/11/07 12:24:23.189778 [INFO] Error reading keyfile: open /home/user_name/.vertcoin-ocm/keyfile.hex: no such file or directory
> Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
> ```
> 
> ![Screenshot from 2021-11-07 11-24-35](https://user-images.githubusercontent.com/91722596/140639720-6d3a2eee-a675-4642-9ed8-8dd166c222fc.png)

no problem on 2.1-beta3

**Comment by vertiond** [comment]
This issue has to do with installing the proper version of webkit2gtk for your system.
