### ISSUE TITLE
Unable to change active pool

### ISSUE THREAD

**Issue by 01NicZA** [vertcoin-project/one-click-miner-vnext#196]
After clicking 'Save & Restart', expected OCM to restart with new Mining Pool active

OCM doesn't respond to 'Save & Restart' being clicked. Mining Pool remains on Hashalot

Occurs since updating to RC15, downloaded another copy from Github, same issue.

Github, Windows X64 no debug, V2.0-RC15-84ddd32

Win10 X64, GTX1070

**Comment by vertiond** [comment]
Use RC14 if you need to change pool.

Fixed in https://github.com/vertcoin-project/one-click-miner-vnext/pull/194/files#diff-217e01ddeafc29bf207dfe6a37873859276c5fdf5f89b83c7f8ec8cf37920ceeL112
