### ISSUE TITLE
Spendable balance never goes up above zero on version RC16

### ISSUE THREAD

**Issue by isaoyamasita** [vertcoin-project/one-click-miner-vnext#200]
Spendable balance never goes up above zero

Spendable balance goes up above zero

Consistently on every startup

Windows 10 Pro
GPU = NVidia RTX 2060-Max

**Comment by vertiond** [comment]
Which pool are you mining to?

**Comment by isaoyamasita** [comment]
Zergpool and hashalot

**Comment by gksegjr1** [comment]
I am having the same issue as well. I have a good balance in pending payout but it never goes to spendable balance. I am also using Zergpool.

**Comment by joshfedo** [comment]
Same issue for me with Zergpool

**Comment by isaoyamasita** [comment]
I am having the same issue. I am now reached 4.5 VTC pending payout with Zerg pool. If it's a setting issue, what should be the setting ? My spendable balance was working with previous OCM releases until RC15.

**Comment by isaoyamasita** [comment]
I am now trying with RC17 with Supernova and it works, albeit very slow to accumulate the spendable balance.
