### ISSUE TITLE
Unable to send spendable balance to my Coinomi wallet with RC16

### ISSUE THREAD

**Issue by isaoyamasita** [vertcoin-project/one-click-miner-vnext#202]
Unable to send spendable balance to my Coinomi wallet with RC16, even though I get the message saying "successfully completed". After waiting for 15 minutes or more, when I check my Coinomi wallet, my balance is not increased.
I'm mainly using Zergpool now, but the same applies for Hashalot pool.

Vertcoin balance on my Coinomi wallet should increase, as it did with RC12 through RC14 release.

Consistently every time when I send my balance.

github, RC16, unarchived .zip file

Windows 10 Pro / Nvidia RTX 2060-Max

**Comment by vertiond** [comment]
Please check your transaction on a block explorer and go through Coinomi support channels.
