### ISSUE TITLE
App Icon should be something of a Vertcoin logo

### ISSUE THREAD

**Issue by gertjaap** [vertcoin-project/one-click-miner-vnext#21]

**Comment by gertjaap** [comment]
This seems stuck on https://github.com/wailsapp/wails/issues/2 - since there's no packager for Linux yet. Will monitor and migrate when appropriate.

**Comment by vertiond** [comment]
I dug into this a bit and it seems that wails itself has no plans anymore for supporting packagers.  This would be resolved by https://github.com/vertcoin-project/one-click-miner-vnext/issues/327
