### ISSUE TITLE
issues with Zergpool payout

### ISSUE THREAD

**Issue by ILLUMINATIPIZZA** [vertcoin-project/one-click-miner-vnext#212]
im having an issue recieving my payout from zergpool 
i was under the assumption of information givin that at most i would need to attain 8vtc before payout yet i am at over 10vtc in pending that will not pay out. 

all im doing is letting the ocm mine other than that i have no control of the issue at hand . 

ocm v2.0-rc16

1080ti mining

**Comment by isaoyamasita** [comment]
I am having the same issue. I am now reached 4.5 VTC pending payout with Zerg pool. If it's a setting issue, what should be the setting ? My spendable balance was working with previous OCM releases until RC15.

**Comment by alenalbrecht** [comment]
http://prntscr.com/106d93i
I have same issue with Zergpool, using latest miner. What should I do?
Br 
Alen

**Comment by vertiond** [comment]
Zergpool pays out when the 'Total Unpaid' amount as seen from https://zergpool.com/?address= reaches the equivalent of 0.0001 BTC or 0.00002 BTC on Sundays.

'Total Unpaid' is a sum of all Vertcoin mined that have received more than 500 confirmations.

**Comment by ILLUMINATIPIZZA** [comment]
I understand the pay out and I have seen the wallet however it says 8.4+
vtc has been paid but it was never delivered to my wallet
