### ISSUE TITLE
Balance spendable not updating!

### ISSUE THREAD

**Issue by alenalbrecht** [vertcoin-project/one-click-miner-vnext#214]

**Comment by vertiond** [comment]
Please elaborate.

**Comment by alenalbrecht** [comment]
Im mining from Zergpool!
http://prntscr.com/106ru64
Total unpaid didnt moved from yesterday! Thought it was pool problem, P2Pool same issue! It was fine up until yesterday! Was it one clink miner or ?
Im doin something wrong?
Thanks

**Comment by alenalbrecht** [comment]
Still same, tried other versions of one click miner still same!
http://prntscr.com/106vina
What to do?

**Comment by alenalbrecht** [comment]
Balance fot updated but loads of coins didnt, how come?

http://prntscr.com/10734m3

**Comment by alenalbrecht** [comment]
http://prntscr.com/107pafg

This is still since morning hove come that I have so much unpaid balance from pool?

**Comment by vertiond** [comment]
Click copy address to the right of Spendable Balance and enter it here: https://zergpool.com/?address=

Zergpool pays out at the equivalent of 0.0001 BTC and 0.00002 BTC on Sunday evenings.
