### ISSUE TITLE
not paying out for 11 hours+

### ISSUE THREAD

**Issue by purge1** [vertcoin-project/one-click-miner-vnext#215]
Miner seems to be mining, altough it doesn't pay out anything since morning (in 11 hours zero payout) also VTC payout pending seems to go up and down
paying out every couple of hours like it used to

![image](https://user-images.githubusercontent.com/48549410/109198219-415bb780-779e-11eb-9546-d3d4398bf6f2.png)

 just turn on a miner and it don't payout

github, downloaded it two days ago.

none

**Comment by alenalbrecht** [comment]
Have same issue, tried other pools same, other versions, same!

**Comment by purge1** [comment]
it seems to just lag I got the payout.

**Comment by vertiond** [comment]
P2Pool does not pay out until it finds a block.  The reward then has to mature for 100 blocks (~4 hours) until it will reach Spendable Balance.
