### ISSUE TITLE
X

### ISSUE THREAD

**Issue by lamoza22** [vertcoin-project/one-click-miner-vnext#216]
checks filed No compatible GPUs detected GPUS found
 silly program

**Comment by vertiond** [comment]
Please ensure your GPU is supported: https://github.com/vertcoin-project/one-click-miner-vnext#which-gpus-are-supported

If it is and you are continuing to have issues, please paste your debug.log from `%appdata%\vertcoin-ocm`

**Comment by lamoza22** [comment]
I have GeForce GTX 1650 but it seems something happened with my video card
because don't want to work anymore  at kryptex application
