### ISSUE TITLE
Is this normal not updating  ? Mining Zergpool with GTX 1070 Msi Gaming X

### ISSUE THREAD

**Issue by alenalbrecht** [vertcoin-project/one-click-miner-vnext#219]
Not updating huge amount of  pending pool payment VTC?
 To update regularly 

http://prntscr.com/107udse

 r16

 Win 10 i7 7700k 1070 Gaming X

Thank you in advance!
Br 
Alen

**Comment by alenalbrecht** [comment]
Still not budging:

http://prntscr.com/108e6k5

**Comment by YirosPower** [comment]
I think this is a widespread issue. Some other users (myself included) reporting the same thing.

**Comment by vertiond** [comment]
Click copy address to the right of Spendable Balance and enter it here: https://zergpool.com/?address=

Zergpool pays out at the equivalent of 0.0001 BTC and 0.00002 BTC on Sunday evenings.
