### ISSUE TITLE
Mining status after switching tabs

### ISSUE THREAD

**Issue by Kangaxx1** [vertcoin-project/one-click-miner-vnext#22]
**<-- Describe the issue -->**
After clicking the stop mining button and switching to another tab (send coins or settings) then switching back to the wallet tab OCM reports that mining is occurring but the user hasn't clicked start mining, there is text output saying "waiting for miner to start" and the mining process isn't running

**<--- What behaviour did you expect? -->**
OCM to not report mining is occurring until after the user has instructed it to do so 

**<--- How reliably can you reproduce the issue, what are the steps to do so? -->**
Reproducible every time by switching tabs

**<-- What version of the One Click Miner are you using, where did you get it (website, self-compiled, etc)? -->**
0.1-alpha26 pre-compiled downloaded direct from Github with Cryptodredge enabled

**<-- What type of machine are you observing the error on (OS/GPU type)? -->**
Windows 10 Pro with 1060 3gb x 2

![Capture](https://user-images.githubusercontent.com/33814004/61556278-4f414680-aa59-11e9-9ae0-2154fea1a189.PNG)

**Comment by gertjaap** [comment]
Thanks for reporting. Will be pushing a fix for this in a few.
