### ISSUE TITLE
not receiving  earnings

### ISSUE THREAD

**Issue by fuzzy85** [vertcoin-project/one-click-miner-vnext#233]
it's been over 24 hours and I haven't received any earnings could you help me please thank you

**Comment by mv1gaming12** [comment]
I also have the same issue.
Mining on Zergpool server.
6 VTC Pending Pool Payout been over 24 Hours?

**Comment by YirosPower** [comment]
I have the same issue, 7.8 VTC pending pool payout.

**Comment by vertiond** [comment]
Click copy address to the right of Spendable Balance and enter it here: https://zergpool.com/?address=

Zergpool pays out at the equivalent of 0.0001 BTC and 0.00002 BTC on Sunday evenings.
