### ISSUE TITLE
pending VTC reset

### ISSUE THREAD

**Issue by Dabemuc** [vertcoin-project/one-click-miner-vnext#234]
After about two hours of mining i've had about 0.22 VTC and I was just waiting  for it to show up in my wallet balance in the Vertcoin OCM. one hour later my balance was still zero but the Vertcoins which i should be receiving reset to around 0.0065 VTC and stay there without getting more.
 I expected to get coins instead of losing them

 Described above

 I cant

 OCM v2.0-218788a from the official website

 Windows 10. AMD rx580 8gb

**Comment by vertiond** [comment]
Pending payout is specific to the pool selected in settings.

**Comment by Dabemuc** [comment]
> Pending payout is specific to the pool selected in settings.

I didnt change that. Its set to Hashalot.net by default. But why does it reset?

**Comment by steveocrypto** [comment]
I'm currently debugging cases where orphaned block rewards were not subtracted from the pending estimations.  In the meantime, pending will just show the confirmed balance at Hashalot.net.

A block confirms after 100 confirmations (a bit over 4 hours).

**Comment by steveocrypto** [comment]
@Dabemuc Pending balances have returned, but are now only available on the Hashalot.net dashboard.  

The pending balance in the one-click miner will continue to show your **confirmed** balance that is pending a payout from the pool.  Blocks require 100 confirmations before they are confirmed.
