### ISSUE TITLE
took my coins and says no gpu available 

### ISSUE THREAD

**Issue by oakman420** [vertcoin-project/one-click-miner-vnext#243]
it to turn on it took all my coins on both my computers 

![Capturevertcoin222](https://user-images.githubusercontent.com/80180068/110230178-09522400-7ec4-11eb-93c3-648af45fcf58.PNG)

 every time i log in says no available gpu 

 2.0 i believe

**Comment by vertiond** [comment]
Same as https://github.com/vertcoin-project/one-click-miner-vnext/issues/246
