### ISSUE TITLE
still says no gpu 

### ISSUE THREAD

**Issue by oakman420** [vertcoin-project/one-click-miner-vnext#245]
![Capturevertcoin222](https://user-images.githubusercontent.com/80180068/110235044-c489b580-7ee2-11eb-8b92-730725ddd61b.PNG)  PLEASE HELP i did get my coin though happy for that

**Comment by oakman420** [comment]
how can i reinstall vertcoin i try to delete it i gave working gpu

**Comment by vertiond** [comment]
Same as https://github.com/vertcoin-project/one-click-miner-vnext/issues/246

Please only open one issue for each problem.
