### ISSUE TITLE
no gpu but i have gpu and was working yesterday ???????

### ISSUE THREAD

**Issue by oakman420** [vertcoin-project/one-click-miner-vnext#246]
![Capturevertcoin222](https://user-images.githubusercontent.com/80180068/110248052-14d53780-7f24-11eb-8fe6-90a87e1cdbb3.PNG)

**Comment by vertiond** [comment]
You may need to add an exclusion for the program to your antivirus / Windows Defender.

**Comment by IIReDeeMeRII** [comment]
Same error here.. Turned entire antivirus off still no luck. RTX 3060 here.

**Comment by oakman420** [comment]
Me to Deleted a whole program and re-download it same thing they sent me something saying about my IP address and will be fixed but it could take a few days there is a work around it but I didn’t understand it I can email it to you and hopefully you can understand it and help me out to please message me back

Sent from my iPhone

On Mar 8, 2021, at 1:37 PM, IIReDeeMeRII <notifications@github.com> wrote:

﻿

Same error here.. Turned entire antivirus off still no luck. RTX 3060 here.

**Comment by vertiond** [comment]
What is your GPU?

**Comment by oakman420** [comment]
1050 ti 4 gigs
