### ISSUE TITLE
kaspersky keeps creating problems and causing the miner to stop with errors.. 

### ISSUE THREAD

**Issue by drxian** [vertcoin-project/one-click-miner-vnext#247]
pc 64 bit windows 10 latest release

**Comment by vertiond** [comment]
There are known issues with 3rd-party antivirus such as Kaspersky.  Most users end up uninstalling their 3rd-party antivirus and resort to only Windows Defender which if you ask me is sufficient.  Otherwise, this is an issue with Kaspersky and I would suggest you go through their support channels.

**Comment by drxian** [comment]
Good suggestion
