### ISSUE TITLE
COULD NOT FIND COMPATIBLE MINRE BINARIES help please fix 

### ISSUE THREAD

**Issue by oakman420** [vertcoin-project/one-click-miner-vnext#253]
![help](https://user-images.githubusercontent.com/80180068/110984502-12a61b00-8320-11eb-8cd5-3c82fc885015.PNG)

**Comment by Macracanthus** [comment]
I had this issue, resolved by updating my nVidia drivers.

**Comment by oakman420** [comment]
Thanks I’ll try that

Sent from my iPhone

On Mar 12, 2021, at 1:42 PM, Macracanthus ***@***.***> wrote:

﻿

I had this issue, resolved by updating my nVidia drivers.

**Comment by oakman420** [comment]
Nope did not work

Sent from my iPhone

On Mar 12, 2021, at 2:38 PM, Nicholas Oakman ***@***.***> wrote:

﻿ Thanks I’ll try that

Sent from my iPhone

On Mar 12, 2021, at 1:42 PM, Macracanthus ***@***.***> wrote:

﻿

I had this issue, resolved by updating my nVidia drivers.

**Comment by vertiond** [comment]
Please only open one issue per problem.
https://github.com/vertcoin-project/one-click-miner-vnext/issues/246
