### ISSUE TITLE
GPU Idling coin not showing

### ISSUE THREAD

**Issue by StephanCoetzee1986** [vertcoin-project/one-click-miner-vnext#257]
My GPU (2080ti) is just idling even tho miner is running + coin not showing (please wait for pending payout information)
 I expect my Gpu to run at a  rather high performance output and the minned coins to show in my Spendable balance

<img width="615" alt="Capture" src="https://user-images.githubusercontent.com/80705248/111186124-5ff1e900-85bb-11eb-9d6c-4460766f704a.PNG">

Its there thewhole time

2.0 final

nvidia 2080ti

**Comment by vertiond** [comment]
This is the expected amount of hash rate and CUDA will show 100% usage in Task Manager.  Click 'Copy Address' to the right of Spendable Balance and input it here to see the poolside dashboard: https://hashalot.net/vtc

**Comment by StephanCoetzee1986** [comment]
Myne cleared up all the issues after the wallet was fully up to date. But
die Gpu is still running on 0 percent

**Comment by mney2** [comment]
Hmm... interesting.  I'll look at the wallet, but I don't get the idle GPU thing.

**Comment by vertiond** [comment]
@mney2 https://www.youtube.com/watch?v=6MYUihUZgMc&t=94s
