### ISSUE TITLE
WTF IS GOING ON!!!!

### ISSUE THREAD

**Issue by TheseImpressions** [vertcoin-project/one-click-miner-vnext#258]
I found the main problem with vertcoin refusing to work. It was not because of AV/Defender it was because VerthashMiner REFUSES to open. Idk why PLEASE FIX THIS!!!  (RTX 2070)
![Screenshot (125)](https://user-images.githubusercontent.com/80651646/111231792-17303500-85a7-11eb-96b8-716a4e318983.png)

![Screenshot (123)](https://user-images.githubusercontent.com/80651646/111231570-bdc80600-85a6-11eb-8c39-8b29969cf74d.png)

**Comment by vertiond** [comment]
Check for a previous running instance of VerthashMiner.exe running in Task Manager and kill it. Alternatively, restart your computer.

**Comment by thctlo** [comment]
windows still has its default restrictions on path lenghts.. 
i would suggest you change the hash in the foldername to a less longer one. 
just a tip.

**Comment by vertiond** [comment]
@thctlo Could you provide an error message or similar that you have found relating to this?

**Comment by scottjoyner** [comment]
2021/03/17 00:16:29.365331 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/03/17 00:16:29.365331 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/03/17 00:16:29.366330 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/03/17 00:16:29.366330 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/03/17 00:16:29.366330 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/03/17 00:16:29.366330 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/03/17 00:16:29.367330 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/03/17 00:16:29.367330 [DEBUG] Not adding already present multi-gpu binary [VerthashMiner.exe] again
2021/03/17 00:16:29.368327 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/03/17 00:16:29.368327 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/03/17 00:16:29.368327 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/03/17 00:16:29.368327 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/03/17 00:16:29.368327 [DEBUG] [Miner windows/1]Daemon file already exists
2021/03/17 00:16:34.495505 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/03/17 00:16:34.495505 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/03/17 00:16:34.496513 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/03/17 00:16:34.496513 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/03/17 00:16:34.496513 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/03/17 00:16:34.498505 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/03/17 00:16:34.498505 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/03/17 00:16:34.499505 [DEBUG] Not adding already present multi-gpu binary [VerthashMiner.exe] again
2021/03/17 00:16:34.499505 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/03/17 00:16:34.499505 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/03/17 00:16:34.499505 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/03/17 00:16:34.500505 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/03/17 00:16:34.500505 [DEBUG] [Miner windows/1]Binary not found, downloading...
2021/03/17 00:16:34.558505 [DEBUG] [Miner windows/1]Daemon file downloaded
2021/03/17 00:16:36.934128 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/03/17 00:16:36.934128 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/03/17 00:16:36.934128 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/03/17 00:16:36.935122 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/03/17 00:16:36.935122 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/03/17 00:16:36.935122 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/03/17 00:16:36.935122 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/03/17 00:16:36.936122 [DEBUG] Not adding already present multi-gpu binary [VerthashMiner.exe] again
2021/03/17 00:16:36.936122 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/03/17 00:16:36.936122 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/03/17 00:16:36.936122 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/03/17 00:16:36.937122 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/03/17 00:16:36.937122 [DEBUG] [Miner windows/1]Daemon file already exists
2021/03/17 00:17:12.182663 [INFO] Setting closed source to [%!b(bool=false)]
2021/03/17 00:17:12.195476 [INFO] Setting debugging to [%!b(bool=true)]
2021/03/17 00:17:12.229060 [INFO] Calling WalletInitialized
2021/03/17 00:17:12.229060 [INFO] Checking wallet..
2021/03/17 00:17:12.229060 [INFO] Initializing wallet X5rP22xJqvDjrb6waJHByRsFw4XeQ2iMNS
2021/03/17 00:17:12.230058 [INFO] Wallet initialized: 1
2021/03/17 00:17:12.230058 [INFO] Done!
2021/03/17 00:17:12.245212 [INFO] Stopping mining process...
2021/03/17 00:17:12.272638 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/03/17 00:17:12.272638 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/03/17 00:17:12.272638 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/03/17 00:17:12.273639 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/03/17 00:17:12.273639 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/03/17 00:17:12.273639 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/03/17 00:17:12.273639 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/03/17 00:17:12.274655 [DEBUG] Not adding already present multi-gpu binary [VerthashMiner.exe] again
2021/03/17 00:17:12.275638 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/03/17 00:17:12.275638 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/03/17 00:17:12.275638 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/03/17 00:17:12.275638 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/03/17 00:17:12.276637 [DEBUG] [Miner windows/1]Daemon file already exists
2021/03/17 00:17:14.623612 [INFO] Stopping mining process...
2021/03/17 00:17:16.893016 OCM v2.0-218788a Started up
2021/03/17 00:17:17.236085 [INFO] User IETF is en-US
2021/03/17 00:17:17.236085 [INFO] Matched tag is en-u-rg-uszzzz
2021/03/17 00:17:17.236085 [INFO] Returning locale en
2021/03/17 00:17:17.301082 [INFO] Checking wallet..
2021/03/17 00:17:17.301082 [INFO] Initializing wallet X5rP22xJqvDjrb6waJHByRsFw4XeQ2iMNS
2021/03/17 00:17:17.302082 [INFO] Wallet initialized: 1
2021/03/17 00:17:17.395124 [DEBUG] GPU [AMD Radeon (TM) RX 480] matched regex [.*AMD.*]
2021/03/17 00:17:17.395124 [DEBUG] GPU [Intel(R) HD Graphics 630] matched regex [.*Intel.*]
2021/03/17 00:17:17.485187 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/03/17 00:17:17.485187 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/03/17 00:17:17.487151 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/03/17 00:17:17.487151 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/03/17 00:17:17.488158 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/03/17 00:17:17.488158 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/03/17 00:17:17.489148 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/03/17 00:17:17.489148 [DEBUG] Not adding already present multi-gpu binary [VerthashMiner.exe] again
2021/03/17 00:17:17.490148 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/03/17 00:17:17.490148 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/03/17 00:17:17.491145 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/03/17 00:17:17.492145 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/03/17 00:17:17.492145 [DEBUG] [Miner windows/1]Daemon file already exists
2021/03/17 00:19:35.408499 [INFO] Stopping mining process...
2021/03/17 00:19:42.185950 OCM v2.0-218788a Started up
2021/03/17 00:19:42.498079 [INFO] User IETF is en-US
2021/03/17 00:19:42.498079 [INFO] Matched tag is en-u-rg-uszzzz
2021/03/17 00:19:42.498079 [INFO] Returning locale en
2021/03/17 00:19:42.573081 [INFO] Checking wallet..
2021/03/17 00:19:42.573081 [INFO] Initializing wallet X5rP22xJqvDjrb6waJHByRsFw4XeQ2iMNS
2021/03/17 00:19:42.574082 [INFO] Wallet initialized: 1
2021/03/17 00:19:42.662288 [DEBUG] GPU [AMD Radeon (TM) RX 480] matched regex [.*AMD.*]
2021/03/17 00:19:42.662288 [DEBUG] GPU [Intel(R) HD Graphics 630] matched regex [.*Intel.*]
2021/03/17 00:19:42.746808 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/03/17 00:19:42.747808 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/03/17 00:19:42.747808 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/03/17 00:19:42.747808 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/03/17 00:19:42.748810 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/03/17 00:19:42.748810 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/03/17 00:19:42.748810 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/03/17 00:19:42.748810 [DEBUG] Not adding already present multi-gpu binary [VerthashMiner.exe] again
2021/03/17 00:19:42.749809 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/03/17 00:19:42.749809 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/03/17 00:19:42.749809 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/03/17 00:19:42.749809 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/03/17 00:19:42.749809 [DEBUG] [Miner windows/1]Daemon file already exists
2021/03/17 00:25:22.383806 [INFO] Setting closed source to [%!b(bool=false)]
2021/03/17 00:25:22.395254 [INFO] Setting debugging to [%!b(bool=true)]
2021/03/17 00:25:22.429744 [INFO] Setting testnet to [%!b(bool=false)]
2021/03/17 00:25:22.429744 [INFO] Setting network to testnet=%!b(bool=false)
2021/03/17 00:25:22.429744 [INFO] Calling WalletInitialized
2021/03/17 00:25:22.429744 [INFO] Checking wallet..
2021/03/17 00:25:22.430734 [INFO] Initializing wallet Vsqa4i4SiNq7QHggW3HEX43u3YkpLkbujG
2021/03/17 00:25:22.432732 [INFO] Wallet initialized: 1
2021/03/17 00:25:22.432732 [INFO] Done!
2021/03/17 00:25:22.466040 [INFO] Stopping mining process...
2021/03/17 00:25:22.563727 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/03/17 00:25:22.563727 [DEBUG] Not adding already present multi-gpu binary [VerthashMiner.exe] again
2021/03/17 00:25:22.563727 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/03/17 00:25:22.564720 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/03/17 00:25:22.564720 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/03/17 00:25:22.565720 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/03/17 00:25:22.565720 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/03/17 00:25:22.565720 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/03/17 00:25:22.565720 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/03/17 00:25:22.565720 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/03/17 00:25:22.566729 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/03/17 00:25:22.566729 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/03/17 00:25:22.566729 [DEBUG] [Miner windows/1]Daemon file already exists
2021/03/17 00:25:33.751492 [INFO] Stopping mining process...
2021/03/17 00:26:03.796143 OCM v2.0-218788a Started up
2021/03/17 00:26:04.071663 [INFO] User IETF is en-US
2021/03/17 00:26:04.071663 [INFO] Matched tag is en-u-rg-uszzzz
2021/03/17 00:26:04.072667 [INFO] Returning locale en
2021/03/17 00:26:04.145661 [INFO] Checking wallet..
2021/03/17 00:26:04.145661 [INFO] Initializing wallet Vsqa4i4SiNq7QHggW3HEX43u3YkpLkbujG
2021/03/17 00:26:04.146662 [INFO] Wallet initialized: 1
2021/03/17 00:26:04.247664 [DEBUG] GPU [AMD Radeon (TM) RX 480] matched regex [.*AMD.*]
2021/03/17 00:26:04.247664 [DEBUG] GPU [Intel(R) HD Graphics 630] matched regex [.*Intel.*]
2021/03/17 00:26:04.340042 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/03/17 00:26:04.340042 [DEBUG] Not adding already present multi-gpu binary [VerthashMiner.exe] again
2021/03/17 00:26:04.341044 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/03/17 00:26:04.341044 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/03/17 00:26:04.342051 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/03/17 00:26:04.342051 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/03/17 00:26:04.342051 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/03/17 00:26:04.342051 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/03/17 00:26:04.343059 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/03/17 00:26:04.343059 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/03/17 00:26:04.344059 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/03/17 00:26:04.345058 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/03/17 00:26:04.345058 [DEBUG] [Miner windows/1]Binary not found, downloading...
2021/03/17 00:26:04.688002 [DEBUG] [Miner windows/1]Daemon file downloaded
2021/03/17 00:26:18.467065 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/03/17 00:26:18.468026 [DEBUG] Not adding already present multi-gpu binary [VerthashMiner.exe] again
2021/03/17 00:26:18.468026 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/03/17 00:26:18.468026 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/03/17 00:26:18.469026 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/03/17 00:26:18.469026 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/03/17 00:26:18.469026 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/03/17 00:26:18.470025 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/03/17 00:26:18.470025 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/03/17 00:26:18.470025 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/03/17 00:26:18.470025 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/03/17 00:26:18.470025 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/03/17 00:26:18.471024 [DEBUG] [Miner windows/1]Binary not found, downloading...
2021/03/17 00:26:18.549919 [DEBUG] [Miner windows/1]Daemon file downloaded
2021/03/17 00:41:11.372542 OCM v2.0-218788a Started up
2021/03/17 00:41:11.653510 [INFO] User IETF is en-US
2021/03/17 00:41:11.654510 [INFO] Matched tag is en-u-rg-uszzzz
2021/03/17 00:41:11.655511 [INFO] Returning locale en
2021/03/17 00:41:11.747510 [INFO] Checking wallet..
2021/03/17 00:41:11.748510 [INFO] Initializing wallet Vsqa4i4SiNq7QHggW3HEX43u3YkpLkbujG
2021/03/17 00:41:11.750511 [INFO] Wallet initialized: 1
2021/03/17 00:41:11.903526 [DEBUG] GPU [AMD Radeon (TM) RX 480] matched regex [.*AMD.*]
2021/03/17 00:41:11.903526 [DEBUG] GPU [Intel(R) HD Graphics 630] matched regex [.*Intel.*]
2021/03/17 00:41:12.004886 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/03/17 00:41:12.004886 [DEBUG] Not adding already present multi-gpu binary [VerthashMiner.exe] again
2021/03/17 00:41:12.005924 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/03/17 00:41:12.005924 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/03/17 00:41:12.006906 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/03/17 00:41:12.006906 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/03/17 00:41:12.006906 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/03/17 00:41:12.007893 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/03/17 00:41:12.007893 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/03/17 00:41:12.007893 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/03/17 00:41:12.007893 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/03/17 00:41:12.007893 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/03/17 00:41:12.008893 [DEBUG] [Miner windows/1]Binary not found, downloading...
2021/03/17 00:41:12.350504 [DEBUG] [Miner windows/1]Daemon file downloaded
2021/03/17 00:41:12.376523 [DEBUG] [Miner windows/1]Daemon file is available and correct
2021/03/17 00:41:12.376523 [DEBUG] [Miner windows/1](Re)creating unpack directory
2021/03/17 00:41:24.265753 [DEBUG] Launching C:\Users\blksc\AppData\Roaming\vertcoin-ocm\miners\unpacked-9be5d3855c45af1077ee2e8bcc5cb688c55688dcfde5327e70f7554098ecd35d\VerthashMiner-0.7.0-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\blksc\AppData\Roaming\vertcoin-ocm\verthash-miner-tmpl.conf]

**Comment by TheseImpressions** [comment]
The problem still proceeds with my verthashminer.exe. I reinstalled, changed the permissions to only me, WHAT SHOULD I DO!!!!

**Comment by thctlo** [comment]
> @thctlo Could you provide an error message or similar that you have found relating to this?

no, sorry i cant, i not running it atm, but https://betanews.com/2016/05/29/long-paths-windows-10/
does how how to enable this.

**Comment by troler36** [comment]
You can try dual booting
Use Linux for mining while use Windows for gaming and every day work

**Comment by thctlo** [comment]
> You can try dual booting
> Use Linux for mining while use Windows for gaming and every day work

Ps.  Linux Mint removed the need for windows gaming completely.. 
SteamOS works great and sofar all my windows games work great in Linux Mint, most even have more FPS. :-) 

if there is one thing that im trying to avoid these days, its windows..

**Comment by JacobHin2** [comment]
Maybe try running as admin?

**Comment by JacobHin2** [comment]
Or try running the latest stable release?

**Comment by gertjaap** [comment]
Closed due to inactivity
