### ISSUE TITLE
Vertcoin One Click Miner not working

### ISSUE THREAD

**Issue by CryptoMiner1234** [vertcoin-project/one-click-miner-vnext#259]
One Click Miner (latest version) for Vertcoin doesn't work right after installation, immidietly after starting to mine. Insttaled on Windows 10 x64 with Intel integrated graphics card HD 2500 only. Is my graphics card the cause of this problem or is it something else? Is there anything i can do to make it work? It gets me this message on the screen:
![Capture](https://user-images.githubusercontent.com/80750904/111311389-79983c80-865e-11eb-94bc-cd9822743f46.PNG)

**Comment by vertiond** [comment]
Intel integrated graphics are not supported.  Please refer to this list of supported hardware: https://github.com/CryptoGraphics/VerthashMiner#supported-hardware
