### ISSUE TITLE
need to reset passwork or account.

### ISSUE THREAD

**Issue by coreycz713** [vertcoin-project/one-click-miner-vnext#260]
i forgot my password do i just need to reset the miner or is there a way to recover it?

%APPDATA%\vertcoin-ocm on Windows
$HOME/.vertcoin-ocm on Linux

-->

**Comment by vertiond** [comment]
There is no way to recovery a wallet without the password.  Backup your `keyfile.hex` from `%appdata%\vertcoin-ocm in case you remember it.  Delete `keyfile.hex` and restart vertcoin-ocm in order to generate a new wallet.
