### ISSUE TITLE
Miner software reported no compatible GPUs no Quardo 4000M

### ISSUE THREAD

**Issue by dr-crx** [vertcoin-project/one-click-miner-vnext#261]
it says no GPU as i am using Quardo 4000M GPU.
which GPUs are compatible with this Miner?

**Comment by vertiond** [comment]
NVIDIA Quadro 4000M is a mobile graphics chip that uses CUDA 2.1
The minimum CUDA required by VerthashMiner within OCM is 3.0
https://github.com/CryptoGraphics/VerthashMiner#supported-hardware
