### ISSUE TITLE
Vertcoin one click miner issue

### ISSUE THREAD

**Issue by chumamakasi** [vertcoin-project/one-click-miner-vnext#264]
The vertcoin one click miner keeps returning the following error each time I launch the exe file, 'Checks failed: One or more of your miner binaries are showing rapid failures (immediately stop after starting). Please enable debugging under the Settings tab and then Save & Restart. Use the debug.log to learn more about what might be going on.' (see screenshots)
![VTC OCM 1](https://user-images.githubusercontent.com/46252804/111916332-4dbbf300-8a72-11eb-9c35-4f9704095cab.jpg)
![VTC OCM 2](https://user-images.githubusercontent.com/46252804/111916333-4e548980-8a72-11eb-8c7e-91ea4adf1d99.jpg)
![VTC OCM 3](https://user-images.githubusercontent.com/46252804/111916334-4eed2000-8a72-11eb-8d0c-a34fde6335ec.jpg)

 Launch the miner after verification.

 

 see screenshots

 version 2.0 gotten from https://vertcoin.org/mining-setup/

 Win 10 Intel core i7 (see screenshot) 
![Machine details](https://user-images.githubusercontent.com/46252804/111916305-2d8c3400-8a72-11eb-8d5a-97011333b3f0.jpg)

**Comment by vertiond** [comment]
What is your GPU?  Please make sure it is supported: https://github.com/vertcoin-project/one-click-miner-vnext#which-gpus-are-supported

**Comment by chumamakasi** [comment]
> What is your GPU? Please make sure it is supported: https://github.com/vertcoin-project/one-click-miner-vnext#which-gpus-are-supported

See my GPU specs here, could it be the reason for the problem?
![GPU 1](https://user-images.githubusercontent.com/46252804/111958365-0d498d00-8ae5-11eb-848c-e7810c58df39.jpg)
![GPU 2](https://user-images.githubusercontent.com/46252804/111958371-10447d80-8ae5-11eb-8efd-e310bbbca0a8.jpg)

**Comment by vertiond** [comment]
Yes, the NVIDIA NVS 5200M uses OpenCL 1.1 and CUDA 2.1 which do not meet specifications.
