### ISSUE TITLE
Installation of Vertcoin "One Click Miner" failed

### ISSUE THREAD

**Issue by Gert1969** [vertcoin-project/one-click-miner-vnext#267]
I tried to install the Miner using vertcoin-ocm-2.0-windows-x64.zip from your website and got the below error message:

![image](https://user-images.githubusercontent.com/81288114/112270604-2b94c180-8c7a-11eb-86be-f23a0a57d955.png)

After activating the debugging, I still get the same error message.

Will it work with the Intel(R) UHD Graphics 630?

**Comment by vertiond** [comment]
Intel UDH Graphics 630 are not supported.
