### ISSUE TITLE
is there a fix for this yet still no go on my gpu working 1050 ti 4 gigs 

### ISSUE THREAD

**Issue by oakman420** [vertcoin-project/one-click-miner-vnext#269]
![Capturenew1212121](https://user-images.githubusercontent.com/80180068/112380650-de7b1480-8ca6-11eb-9fd9-76e235eaf350.PNG)

**Comment by vertiond** [comment]
Please only open one issue: https://github.com/vertcoin-project/one-click-miner-vnext/issues/246

There appears to be an issue with the OCM on 1050 ti.  You may have to run VerthashMiner directly: https://github.com/CryptoGraphics/VerthashMiner

Please join the Vertcoin discord for further support.

**Comment by oakman420** [comment]
Thankfully a reply with a work around ty hope it works I love virtcoin just a small hickup cheers

Sent from my iPhone

On Mar 27, 2021, at 10:27 AM, vertion ***@***.***> wrote:

﻿

Please only open one issue: #246<https://github.com/vertcoin-project/one-click-miner-vnext/issues/246>

There appears to be an issue with the OCM on 1050 ti. You may have to run VerthashMiner directly: https://github.com/CryptoGraphics/VerthashMiner

Please join the Vertcoin discord for further support.
