### ISSUE TITLE
Check for OCM already running

### ISSUE THREAD

**Issue by adamcollier1** [vertcoin-project/one-click-miner-vnext#27]
When upgrading I had left the old version running also, may be cool to have a check on startup of the OCM and see if another instance of OCM is already running and display a little alert if so.

**Comment by gertjaap** [comment]
Thanks for noticing and yeah, good idea!

Op 24 jul. 2019 om 17:06 heeft Adam Collier <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


When upgrading I had left the old version running also, may be cool to have a check on startup of the OCM and see if another instance of OCM is already running and display a little alert if so.
