### ISSUE TITLE
OCM freezes, but gives wrong hashrates while not mining.

### ISSUE THREAD

**Issue by Abdelhafidkaldoun** [vertcoin-project/one-click-miner-vnext#270]
When I start OCM, It mines for 30min, then it stops mining. But the estimated hashrates are not dropping at all.
When checking to poolwebsite, it gives different values.

![Schermopname_14](https://user-images.githubusercontent.com/81370784/112485533-56b30a00-8d7b-11eb-8bfa-4eb332c128c1.png)
![unknown1](https://user-images.githubusercontent.com/81370784/112485556-59adfa80-8d7b-11eb-9a86-bd9e373f3536.png)

- 'Aggressive' OC/undervolt will trigger the issue

Version 1.2.3.0 by Zemrys.
https://github.com/vertcoin-project/One-Click-Miner/releases

Windows 10 version 20H2
CPU: Intel I9-10850K
GPU: Zotac twin edge rtx 3070 OC
RAM: 32GB 4x8 corsair vengeance RGB 3200mhz cl16
Storage: Crucial P1 1TB nvme ssd

**Comment by Sprogo** [comment]
I have the same problem, almost the same.

**Comment by Abdelhafidkaldoun** [comment]
> 
> 
> I have the same problem, almost the same.

I fixed it by setting my memclock to 1100 instead of 1200mhz in msi afterburner.
![Schermopname (16)](https://user-images.githubusercontent.com/81370784/112679103-13849400-8e6c-11eb-9b87-a8a94bb5f0bf.png)

**Comment by Sprogo** [comment]
Thanks a lot, it worked for me as well.
