### ISSUE TITLE
GUI starts with empty black window with webkit2gtk 2.32.0

### ISSUE THREAD

**Issue by malteo** [vertcoin-project/one-click-miner-vnext#271]
I cannot start one-click-miner-vnext anymore after a system upgrade.

Version is latest `master` built with `wails build` on Arch Linux (latest).

![image](https://user-images.githubusercontent.com/80266/112718702-fa73f580-8ef4-11eb-8720-28d57793798b.png)

`debug.log`:
```
2021/03/27 12:01:58.853942 OCM v0.0-alpha1 Started up
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
```

**The culprit is webkit2gtk version 2.32.0** which just arrived on arch repos, downgrading to 2.30.6 fixes the issue.

**Comment by gertjaap** [comment]
This is more likely than not a bug in Wails.
