### ISSUE TITLE
Very Low Hashrate GTX 1650

### ISSUE THREAD

**Issue by johnnydeka** [vertcoin-project/one-click-miner-vnext#274]
using vertcoin one click miner and the has rate is at 250 kH/s and i know this is very low tried everything to fix it but i cant, checked through the task manager and its not using the gpu or cpu but my memory is at 50%, Hopefully someone can help me

%APPDATA%\vertcoin-ocm on Windows
$HOME/.vertcoin-ocm on Linux

-->

**Comment by vertiond** [comment]
That hashrate is right in the ballpark of what is expected from the GTX 1650.  Please refer to this video to check CUDA utilization from Task Manager: https://www.youtube.com/watch?v=6MYUihUZgMc&t=94s
