### ISSUE TITLE
Not mining

### ISSUE THREAD

**Issue by lpalm22** [vertcoin-project/one-click-miner-vnext#286]
Havre been running the miner for 24 hours now, and it is not mining anything??

 2.1-beta1 from vertcoin-proje4ct

**Comment by vertiond** [comment]
Please paste your debug.log from %appdata%\vertcoin-ocm

**Comment by lpalm22** [comment]
[debug.log](https://github.com/vertcoin-project/one-click-miner-vnext/files/6307102/debug.log)

**Comment by vertiond** [comment]
NVIDIA GeForce GTX 1060 6GB

Is this a laptop?  There are known issues with such NVIDIA 1050/1060 systems.  Mining on laptops is ill advised regardless due to poor cooling capabilities.

**Comment by lpalm22** [comment]
Not a laptop, desktop

**Comment by vertiond** [comment]
Seems similar to https://github.com/vertcoin-project/one-click-miner-vnext/issues/111

You may have to run VerthashMiner directly and adjust the WorkSize parameter. https://github.com/CryptoGraphics/VerthashMiner

**Comment by gertjaap** [comment]
Closed due to inactivity
