### ISSUE TITLE
Can't send VTC

### ISSUE THREAD

**Issue by Allard-code-web** [vertcoin-project/one-click-miner-vnext#287]
When i try to send my coins i get: Could not sign transactions, check password

send coins normal

OCM v2.1-beta1-5200cc4

windows, gtx 1050

![image](https://user-images.githubusercontent.com/79313586/114154201-6ce6cb80-9920-11eb-971d-5ae8b2d5fcd8.png)

**Comment by vertiond** [comment]
Did you retry and have your coins been sent?  This sometimes is a graphical error.

**Comment by Allard-code-web** [comment]
I did retry a hundred times

**Comment by vertiond** [comment]
You are inputting a wrong password?

**Comment by Allard-code-web** [comment]
i put in the password of the exchange

**Comment by vertiond** [comment]
The password must be the one you set upon first start of the OCM.

**Comment by Allard-code-web** [comment]
Oooh, and what if i forgot that password?

**Comment by vertiond** [comment]
Your coins are lost if you do not have the password.  You can delete keyfile.hex in %appdata%\vertcoin-ocm to create a new wallet.
