### ISSUE TITLE
Vertcoin OCM starts with an error and a blank screen:  keyfile.hex: no such file or directory

### ISSUE THREAD

**Issue by edmorbius** [vertcoin-project/one-click-miner-vnext#291]
Vertcoin OCM starts with an error and a blank screen:  keyfile.hex: no such file or directory.

Some type of startup or welcome screen.

No screenshot is need because it  is a blank/blank window.

This occurs every time I start OCM.  I have deleted ~/.virtcoin-ocm and restarted as well with the same result.

I download the 64bit linux binary of v2.0 from github.

Archlinux with kernel 5.10.28-1-lts.  The video card is an AMD wx5100.

Archlinux with Plasma 

OpenCL 2.1 AMD-APP (3224.4)

2021/04/10 13:33:32.548504 OCM v2.0-218788a Started up
2021/04/10 13:33:32.548642 [INFO] Error reading keyfile: open /home/user/.vertcoin-ocm/keyfile.hex: no such file or directory
2021/04/10 13:33:32.548713 [INFO] Error reading keyfile: open /home/user/.vertcoin-ocm/keyfile.hex: no such file or directory
2021/04/10 13:48:55.634417 [INFO] Stopping mining process...
2021/04/10 13:50:07.812067 OCM v2.0-218788a Started up
2021/04/10 13:50:07.812272 [INFO] Keyfile had wrong length. Expected 129, got 0
2021/04/10 13:50:17.015002 [INFO] Stopping mining process...

**Comment by AdverseMiller** [comment]
I'm having the same issue. Only difference is I'm running a 2080 super.

**Comment by edmorbius** [comment]
Just to be complete, I tested the recent beta and it failed the same way.

**Comment by edmorbius** [comment]
OK.  More testing.
I ran as root and had the same issue.  So, I went to my son's Linux Lite 5.2 machine which is based on Ubuntu 20.04 LTS.  It ran fine with the same keyfile.hex error in the console.  The GUI allowed me to create a wallet (and a keyfile.hex).  I copied that file to my arch machine and I no longer get the keyfile.hex error but the GUI is still just a blank screen.  This is clearly a library version issue.

As I said, it finds the keyfile.hex but I get this at the console.

**2021/04/11 15:15:14.678115 OCM v2.0-218788a Started up
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal**

**Comment by edmorbius** [comment]
I think this has something to do with the error.
[https://github.com/wailsapp/wails/issues/658](url)

**Comment by edmorbius** [comment]
Sorry for the many additions but here is the solution.
[https://github.com/wailsapp/wails/pull/659](url)

**Comment by edmorbius** [comment]
OK.  I temporarily fixed the problem on my archlinux system.  I downgraded webkit2gtk 2.32.0-1 to 2.30.6-1 and it is mining fine.  I suspect this would fix the unbuntu issue as well since the links above suggest that changes to 2.32 caused the issues.

**Comment by edmorbius** [comment]
Hi

My wails version is 1.16.2 and it still fails.  This issue defined in the wails 659 issue.  Thanks for the great project.  I am up and running regardless.

```
/home/user/go/bin/wails -help
 _       __      _ __    
| |     / /___ _(_) /____
| | /| / / __ `/ / / ___/
| |/ |/ / /_/ / / (__  )  v1.16.2
|__/|__/\__,_/_/_/____/   https://wails.app
The lightweight framework for web-like apps

Available commands:

   setup     Setup the Wails environment [default]
   migrate   Migrate projects to latest Wails release 
   init      Initialises a new Wails project 
   build     Builds your Wails project 
   serve     Run your Wails project in bridge mode 
   update    Update to newer [pre]releases or specific versions 
   issue     Generates an issue in Github 

```

**Comment by vertiond** [comment]
@edmorbius Did you modify https://github.com/vertcoin-project/one-click-miner-vnext/blob/master/go.mod#L30

**Comment by edmorbius** [comment]
No, I didn't.  I will give that a "go" :-).   Thanks you.
