### ISSUE TITLE
Unconfirmed transactiions

### ISSUE THREAD

**Issue by xbrawn24** [vertcoin-project/one-click-miner-vnext#295]
Hi Team, tried to transfer some vert but states unconfirmed transactions.

expected to send to my exchange wallet but nothing happens

![image](https://user-images.githubusercontent.com/82481855/114637295-510e6b80-9d0c-11eb-88a3-1e6f0cc8ba08.png)

![image](https://user-images.githubusercontent.com/82481855/114637306-57044c80-9d0c-11eb-8510-eb4f09bcb271.png)

V2.0-rc13-d5f7a98

**Comment by eartd4** [comment]
Hey, get 0.03 BFIC tokens and spread great technology. It’s free, very easy, and powerful.

https://t.me/latoken_airdrops_bot?start=2kedkh94-airdrop_BFIC-source_wa

**Comment by magichippo01** [comment]
Alright Kobe

**Comment by vertiond** [comment]
Upgrade to the latest version.

**Comment by xbrawn24** [comment]
Thanks, upgraded to new version. Working successfully.
