### ISSUE TITLE
insufficient funds when setting up the wallet for withdrawal

### ISSUE THREAD

**Issue by ovvai** [vertcoin-project/one-click-miner-vnext#296]
in vertcoin miner I mined about 3 vtc in the Zergpool pool.
When I fill in the wallet address to try the transfer, the program tells me that there are not enough funds.
Is there a minimum transferable?

OCM v.2.0-218788a

**Comment by Sprogo** [comment]
Yes, the threshold is 0,0001 BTC equivalent of VTC plus some transferring fee.  So it was apprx. 8 VTC on Friday, but it is 3,88 VTC right now.

**Comment by eartd4** [comment]
No

**Comment by Sprogo** [comment]
No to what? Either "there is no minimum" or "no way"?

**Comment by vertiond** [comment]
@ovvai Is the 3 VTC in your Spendable Balance?  If so, did you try sending again and if the error persisted did you check on a block explorer to see if the funds moved?

**Comment by gertjaap** [comment]
Closed due to inactivity
