### ISSUE TITLE
Zergpool payment threshold on Sundays

### ISSUE THREAD

**Issue by Sprogo** [vertcoin-project/one-click-miner-vnext#297]
There is a different payment threshold of Zergpool on Sundays. 

Is there any chance to utilize this Sunday threshold while transferring coins?

**Comment by vertiond** [comment]
Could you please elaborate?  Zergpool would pay out VTC balances higher than the equivalent of 0.00002 BTC (0.59058 VTC currently) on Sundays.  They will go to your OCM wallet in which you may transfer them out.

**Comment by Sprogo** [comment]
Thank you for your reply. 

It was around midnight when I sent the message about Sundays' threshold.  But a few hours later I noticed "spendable balance" of OCM screen showing some coin balance which was 0 beforehand.  So I manually transferred my balance to bittrex.

I was very confused about "on Sunday late evening(CET)" phrase of Zergpool.

So OCM works well for payout balances over Zerpool's Sunday's threshold
.
