### ISSUE TITLE
unable to sent coin from one click miner to my wallet

### ISSUE THREAD

**Issue by caldeira1980** [vertcoin-project/one-click-miner-vnext#301]
![Captura de Ecrã (41)](https://user-images.githubusercontent.com/70705522/115253914-c622dc00-a124-11eb-9c50-47e2e7dbf355.png)

**Comment by caldeira1980** [comment]
i double check the password and i always have this message

**Comment by vertiond** [comment]
It seems like you are entering an incorrect password.  This is the password you set when you first started OCM.

**Comment by caldeira1980** [comment]
Thank you
