### ISSUE TITLE
Overriding existing handler error

### ISSUE THREAD

**Issue by BenTowali** [vertcoin-project/one-click-miner-vnext#302]
I just downloaded the latest version of the one-click-miner tarball on Github, extracted it and ran it. It does open up, but it doesn't start mining or show anything

Here's a picture of the error:
![2021-04-19_21-43](https://user-images.githubusercontent.com/77504809/115287099-6554cd00-a13f-11eb-89dd-dda33d0ab545.png)

And here's a picture of the OCM window:
![2021-04-19_21-47](https://user-images.githubusercontent.com/77504809/115287404-c41a4680-a13f-11eb-90a4-4a9ba566efb7.png)

**Comment by vertiond** [comment]
This user here downgraded webkit2gtk 2.32.0-1 to 2.30.6-1.
https://github.com/vertcoin-project/one-click-miner-vnext/issues/291#issuecomment-817370717

Issue tracker: https://github.com/vertcoin-project/one-click-miner-vnext/issues/294
PR: https://github.com/vertcoin-project/one-click-miner-vnext/pull/298
