### ISSUE TITLE
Error message during starting Vertocoin OCM

### ISSUE THREAD

**Issue by dvgelderen77** [vertcoin-project/one-click-miner-vnext#303]
download the software, start the software, installing software, message waiting for miners, than error message: one or more of your miner binaries are showing rapid failure (immediately stop after starting) ...............

![image](https://user-images.githubusercontent.com/82840144/115290444-d56d4e00-a153-11eb-987b-05c1f2969421.png)
[debug.log](https://github.com/vertcoin-project/one-click-miner-vnext/files/6338471/debug.log)

 several latest version, also the latest beta ocm2.1

 windows 10

**Comment by vertiond** [comment]
Please make sure your GPU is supported. https://github.com/vertcoin-project/one-click-miner-vnext#which-gpus-are-supported
