### ISSUE TITLE
Check Fa

### ISSUE THREAD

**Issue by westside8** [vertcoin-project/one-click-miner-vnext#304]

**Comment by westside8** [comment]
![Error](https://user-images.githubusercontent.com/82842868/115297910-bf976300-a12a-11eb-9be6-390962b9306e.JPG)

**Comment by vertiond** [comment]
Please make sure your GPU is supported. https://github.com/vertcoin-project/one-click-miner-vnext#which-gpus-are-supported

**Comment by gertjaap** [comment]
Closed due to inactivity
