### ISSUE TITLE
I sent all my vertcoins to coinbase app and all of them disappeared 

### ISSUE THREAD

**Issue by alainyaacoub** [vertcoin-project/one-click-miner-vnext#305]

**Comment by alainyaacoub** [comment]
I sent my vertcoins to coinbase app and all of them disappeared

**Comment by QW60** [comment]
I don't think Coinbase supports Vertcoins.
You're coins are now stuck in a network they don't support. **You can't ever get stuck coins back.**
Check if the coin is compatible with you're wallet next time.

**Comment by vertiond** [comment]
Contact Coinbase support.
