### ISSUE TITLE
How to adjust gpu settings on linux?

### ISSUE THREAD

**Issue by rickymedrano** [vertcoin-project/one-click-miner-vnext#310]
Is there a way I can adjust BatchTimeMs and OccupancyPct? OCM is causing too much lag on linux and I want to adjust these flags to try and get a more smooth experience.
Tried running 
`./vertcoin-ocm -help`
but it just says to run the -help command and doesn't show any other flags I can pass.

**Comment by vertiond** [comment]
You must run VerthashMiner directly to gain this functionality. https://github.com/CryptoGraphics/VerthashMiner
