### ISSUE TITLE
JSC_SIGNAL_FOR_GC and blank screen at start again.

### ISSUE THREAD

**Issue by edmorbius** [vertcoin-project/one-click-miner-vnext#311]
Hi

This is related to issue no #291.   Downgrading webkit2gtk was the answer but the newer version has become a requirement for other packages in Arch and, soon, its derivatives.   The error that is generated at the console when running vertcoin-ocm is:

`Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
`

As an attempt to solve the issue, I downloaded 2.1 beta and built it with wails 1.6.3 and I made that a requirement in go.mod.

```
altair ~/D/one-click-miner-vnext-2.1-beta1> grep wails go.mod 
	github.com/wailsapp/wails v1.16.3

```
 
The build was clean and running OCM with webkit2gtk 2.32.0-2 fails in the same way.  That is, a blank screen and the JSC_SIGNAL_FOR_GC.   Is there anything that I could try next?

Thanks

**Comment by vertiond** [comment]
https://github.com/vertcoin-project/one-click-miner-vnext/issues/195

**Comment by edmorbius** [comment]
Thanks.  I just built the new version on Archlinux and it works fine.  Problem solved.
