### ISSUE TITLE
Vertcoin core Wallet is paused and won't move

### ISSUE THREAD

**Issue by contactrewards** [vertcoin-project/one-click-miner-vnext#312]
After catching up a lot over a few days, suddenly paused and won't move. Interfaces says "calculating" Progress increase per hour, and is paused on "97% syncing headers"

**Comment by vertiond** [comment]
Make sure you are on the latest version, try deleting peers.dat, try reindexing.  Anyways, this issue belongs on the vertcoin-core repo, not OCM.
