### ISSUE TITLE
Debug not working

### ISSUE THREAD

**Issue by contactrewards** [vertcoin-project/one-click-miner-vnext#314]
Red notice pop-up in OCM says "One or more of your miner binaries are showing rapid failure (immediately stop after starting) Please enable Debugging in Settings then click Save And Restart." which I did but it just pops up again. plshelp...

**Comment by contactrewards** [comment]
Should it be assumed no one knows how to help with this?

**Comment by contactrewards** [comment]
https://prnt.sc/11wpo89

**Comment by contactrewards** [comment]
Is this seriously how things are running here? No one at all responding to a person wishing to mine Vert coin who can't due to a Vert coin fault? Wow. will let the word spread guys cheers.

**Comment by KforG** [comment]
Enabling debugging doesn't automatically fix your issues but it allows you to better see what's going on in the debug.log file. 
The rapid failure error usually happens when your GPU is not compatible, does your GPU live up to these [requirements](https://github.com/CryptoGraphics/VerthashMiner#supported-hardware)?

**Comment by contactrewards** [comment]
Thanks for helping out. Have downloaded all the requirements, though it seems the new version isn't loading as nothing happens when i select 'run as administrator'. Not sure if the special file is working as not sure how to add it through the back end.

In any case what i have now on start up is a shorter message saying "Cannot find compatible miner binaries". ... are we any closer?   

If someone was in Sydney who could pop over and help i'd be happy to pay a small consulting fee! 

Thanks in advance for helping this fresh noob understand more about this...

**Comment by KforG** [comment]
We might be closer. The debug file is located in `%appdata%\vertcoin-ocm` assuming you're on windows. 

It seems like it's your antivirus removing the miner, make sure to have added exceptions for your antivirus in the above mentioned folder.

**Comment by contactrewards** [comment]
Yes Windows it is. 

Hmm not sure. Don't have antivirus software that i know of. In any case I have that file open, do i just paste something in there to create such an extension? do u have something you can provide?

**Comment by contactrewards** [comment]
Btw Nvidia version is Directx runtime version 12.0. Driver version 388.73. if that helps.

**Comment by contactrewards** [comment]
[debug.log](https://github.com/vertcoin-project/one-click-miner-vnext/files/6391626/debug.log)

also here's the debug file. please look and lmk if u can see anything. If i shouldn't be putting this debug file up here pls lemme know so i can take it down. 

The warning says "see your debug file for more info on what's going on'

**Comment by contactrewards** [comment]
> We might be closer. The debug file is located in `%appdata%\vertcoin-ocm` assuming you're on windows.
> 
> It seems like it's your antivirus removing the miner, make sure to have added exceptions for your antivirus in the above mentioned folder.

btw just went into Defender and selected to allow all vertcoin stuff to go past the firewall, not sure if that'll help. this really is frustrating hey.

**Comment by KforG** [comment]
Everyone running windows have an inbuilt antivirus and firewall, windows defender (Just search up how to make an exception in a search engine). 

Have you recently updated your GPU drivers? You keep getting CUDA err 35 which means insufficient drivers. There's some issues with compatibilty with old laptop GPU's, if a driver update doesn't fix your issue there is a big chance it won't work at all. Your only chance then would be to try using Verthashminer(Click the link I posted earlier) directly to see if that works out better, I doubt it though.

**Comment by contactrewards** [comment]
Ok no worries. Probably not a good idea for a laptop anyways. In any case i really appreciate you taking the time to try and help. cheers.
