### ISSUE TITLE
Error when installing minor, would not install

### ISSUE THREAD

**Issue by jschweigert** [vertcoin-project/one-click-miner-vnext#316]
![image](https://user-images.githubusercontent.com/14873626/115788019-498c3980-a380-11eb-9e84-54dde5d0d731.png)
![vert](https://user-images.githubusercontent.com/14873626/115788077-60cb2700-a380-11eb-8e56-22116fcff7ed.JPG)

  Tried twiche and got it both times

  Windows 7

**Comment by KforG** [comment]
You need to add an exclusion for the program to your antivirus / Windows Defender. It looks like your antivirus is deleting the miner, the miner is located in `%appdata%\vertcoin-ocm`.
