### ISSUE TITLE
I have forgot my Password

### ISSUE THREAD

**Issue by julian-ibrishimov** [vertcoin-project/one-click-miner-vnext#318]
Is there any chance to change my password?

**Comment by KforG** [comment]
There is no way to reset your password if you forgot it, your only chance is to guess the password.

To create a new wallet, you will also lose all your previously mined coins, simply remove the `keyfile.hex` from `%appdata%\vertcoin-ocm`. I suggest keeping the old file so you're able to recover the coins if you remember the password in the future.
