### ISSUE TITLE
failed verifications on miner

### ISSUE THREAD

**Issue by sketchief** [vertcoin-project/one-click-miner-vnext#319]
hi, i have installed vertcoin one click miner, and the verifications failed.
![image](https://user-images.githubusercontent.com/83238281/116122293-7b233e80-a6b9-11eb-89de-b4898d83a2b3.png)

thers de debug.log
[debug.log](https://github.com/vertcoin-project/one-click-miner-vnext/files/6378842/debug.log)

hope you can help me, Thank you.

**Comment by KforG** [comment]
The rapid failure error usually happens when your GPU is not compatible, do you have another GPU other than Intel(R) HD Graphics 620 Intel(R)?

You can try turning on the "Mine on integrated graphics" setting if you haven't already, other than that I suggest looking into a driver update.

**Comment by sketchief** [comment]
yes, i have a GForce 920M

**Comment by eartd4** [comment]
No

**Comment by KforG** [comment]
This should be supported unless there is versions that I was unable to find data for. It might be one of the cases where it should be supported but won't work, it's usually the case of old and/or integrated/laptop GPU's like yours. 

You might be able to get it working by updating your drivers, if that doesn't work I would suggest trying with [Verthashminer ](https://github.com/CryptoGraphics/VerthashMiner) directly to see if will work with that. 

If you need help to set it up please join the Vertcoin discord for quicker support, or as an alternative use the /r/vertcoin subreddit.
