### ISSUE TITLE
vercoin.ocm başka bilgisayarda indirip kurduğumda aynı havuz adresinde nasıl kazdırabilirim baştan kurduğumda aynı havuzu seçsem bile farklı cüzdan kodu atıyor

### ISSUE THREAD

**Issue by wargokhan** [vertcoin-project/one-click-miner-vnext#322]

**Comment by KforG** [comment]
I used google translate for this, let me know if I missed something.

To use the same address on two different computers you can use the same `keyfile.hex`. The file is located in, if you're on windows, `%appdata%\vertcoin-ocm`.
