### ISSUE TITLE
Pools problem

### ISSUE THREAD

**Issue by peeeto111** [vertcoin-project/one-click-miner-vnext#323]
I cannot change pools in OCM! It is unfair to force us to use your pool...

**Comment by KforG** [comment]
You can change the pool choice under the settings tab. Vertcoinpool is not operated by the core developers either, the default pool is selected randomly (has recently been shut down as well).

**Comment by peeeto111** [comment]
Like really? I am not that stupid but there is nothing to choose from...
![16200298435452241073138249470459](https://user-images.githubusercontent.com/74729886/116854945-cb8a2700-abf8-11eb-972e-d18db47132fd.jpg)
