### ISSUE TITLE
Stuck @ 0 h/s 

### ISSUE THREAD

**Issue by frostiex** [vertcoin-project/one-click-miner-vnext#325]
STUCK in integrated graphics mining, I have a dedicated GFX, but no integrated.
stuck at mining @ 
0 h/s

![Capture](https://user-images.githubusercontent.com/76623493/116556245-21399900-a8b2-11eb-9ee1-3ed9d9ef31a6.PNG)

EVERYTIME, it was working fine before.

windows 10 pro, GTX 1060

I have tried deleting all the files in %appdata% and start building the hash snd settings from scratch.

**Comment by KforG** [comment]
Change the pool choice, Vertcoinpool recently shut down.

**Comment by gertjaap** [comment]
```STUCK in integrated graphics mining, I have a dedicated GFX, but no integrated.```

Then why is the checkbox "Mine on integrated graphics" enabled? Disabling it will most likely uncover the error that's causing you to not mine on actual graphics card.

Please also add the debug log from %APPDATA%\vertcoin-ocm if your problem persists.

**Comment by frostiex** [comment]
Looks like the pool close was the reason. Thx!
    	
    	Get Outlook for iOS
    
  
 From: Gert-Jaap Glasbergen ***@***.***>Sent: Monday, May 3, 2021 12:03 AMTo: vertcoin-project/one-click-miner-vnextCc: frostiex; AuthorSubject: Re: [vertcoin-project/one-click-miner-vnext] Stuck @ 0 h/s  (#325) 
STUCK in integrated graphics mining, I have a dedicated GFX, but no integrated.
Then why is the checkbox "Mine on integrated graphics" enabled? Disabling it will most likely uncover the error that's causing you to not mine on actual graphics card.
Please also add the debug log from %APPDATA%\vertcoin-ocm if your problem persists.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/vertcoin-project/one-click-miner-vnext/issues/325#issuecomment-831040897",
"url": "https://github.com/vertcoin-project/one-click-miner-vnext/issues/325#issuecomment-831040897",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
