### ISSUE TITLE
Auto start launches old version

### ISSUE THREAD

**Issue by adamcollier1** [vertcoin-project/one-click-miner-vnext#33]
After upgrading, the auto start on boot continues to launch the older version.

Windows 10

**Comment by gertjaap** [comment]
Fixed this by writing the full path we created the autostart for into the datadirectory. Once the OCM starts up, if it finds out that path is different from our current full executable path, it will disable autostart on the old one and re-enable it on the new one. 

Will not update autostarts that exist(ed) before fixing this problem, so those will have to be manually removed, or install the update on the same location and disable/enable autorestart. Then subsequent updates, if placed in a different folder, will migrate the autostart properly.
