### ISSUE TITLE
Hi, I started yesterday with the Vertcoin one-click miner. I see a hashrate of 26 kH/s and a expected income of 0.06 VTC in 24h. After 10 hours I still stay at zero. Is that normal?

### ISSUE THREAD

**Issue by Fluppert** [vertcoin-project/one-click-miner-vnext#330]

**Comment by Fluppert** [comment]
![vtc](https://user-images.githubusercontent.com/4161526/116682076-16fcc500-a9ae-11eb-921c-a7ce1aa1e397.jpg)

**Comment by KforG** [comment]
You haven't found a share yet on p2pool, this will take on average 24 hours with your hashrate. When you find one you will get paid continuously for multiple blocks until the share expires. This is not an issue just a matter of impatience.

You can change the pool under settings if you wish for a more stable payout.

**Comment by Fluppert** [comment]
Ok, but strange. It says 'active pool: P2Pool'
Thx for the comment tKforG.
Obviously I am a newbie

**Comment by gertjaap** [comment]
This is not an issue in OCM.

For such a low hashrate i would not recommend P2Pool, as it has a too high minimum difficulty. This could make it very hard for you to even find a single share, and thus never receiving a payout.

If you switch to one of the other pools, they will dial down the difficulty in order for your miner to find a lower difficulty share, which entitles you to a (tiny) payout. At least then you achieve some level of payout, which i doubt you'll ever do using P2Pool.
