### ISSUE TITLE
Heyy I EROR  Kontroller Başarısız Oldu Failded to configure VerthashMiner.exe exit statust 3221225781 

### ISSUE THREAD

**Issue by XcomCheast** [vertcoin-project/one-click-miner-vnext#331]
Plz Yardım Edin
![HATA](https://user-images.githubusercontent.com/83498644/116780733-1b48e100-aa87-11eb-9dea-a6c15d73a3a4.PNG)

**Comment by gertjaap** [comment]
Duplicate of #106 - Antivirus issue
