### ISSUE TITLE
vercoin.ocm ile kazdığım ve cüzdan numarasını bildiğim ve aynı şekilde aynı cüzdan numrası ile kazma yapmak istiyorum bu nasıl olur

### ISSUE THREAD

**Issue by wargokhan** [vertcoin-project/one-click-miner-vnext#334]

**Comment by vertiond** [comment]
`%appdata%\vertcoin-ocm\keyfile.hex`, cüzdan adresinizi içerir. Aynı adrese madencilik yapmak için `keyfile.hex`'i başka bir bilgisayara kopyalayın.
