### ISSUE TITLE
getting a failure to fonfigure verthashminer.exe exit status 3221225785

### ISSUE THREAD

**Issue by nellythe1th** [vertcoin-project/one-click-miner-vnext#337]
running windows 10 clean install 
down loaded to exempt file and ran from there and getting the following 
is my gmu too old?

thanks for your time 

2021/05/03 21:27:28.857668 OCM v2.0-218788a Started up
2021/05/03 21:27:29.737707 [INFO] User IETF is en-US
2021/05/03 21:27:29.737707 [INFO] Matched tag is en-u-rg-uszzzz
2021/05/03 21:27:29.738708 [INFO] Returning locale en
2021/05/03 21:27:29.935954 [INFO] Checking wallet..
2021/05/03 21:27:29.945948 [INFO] Initializing wallet VjUWdALw7pwnqD1EQsHCZgEJbfvmqJwKTF
2021/05/03 21:27:29.947947 [INFO] Wallet initialized: 1
2021/05/03 21:27:30.080000 [DEBUG] GPU [NVIDIA GeForce GTX 260] matched regex [.*NVIDIA.*]
2021/05/03 21:27:30.303776 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/05/03 21:27:30.303776 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/05/03 21:27:30.307772 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/05/03 21:27:30.309771 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/05/03 21:27:30.309771 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/05/03 21:27:30.311770 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/05/03 21:27:30.313769 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/05/03 21:27:30.315767 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/05/03 21:27:30.317771 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/05/03 21:27:30.319765 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/05/03 21:27:30.320764 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/05/03 21:27:30.322762 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/05/03 21:27:30.324762 [DEBUG] [Miner windows/2]Daemon file already exists
2021/05/03 21:27:30.338753 [DEBUG] [Miner windows/2]Daemon file is available and correct
2021/05/03 21:27:30.339768 [DEBUG] [Miner windows/2]Removing unpack directory
2021/05/03 21:27:31.348509 [DEBUG] [Miner windows/2](Re)creating unpack directory
2021/05/03 21:27:39.541156 [DEBUG] Launching C:\Users\JASON'S\AppData\Roaming\vertcoin-ocm\miners\unpacked-e5af5ab19154f6ee57db22645a43200336e8017865c71505ae669af19243449e\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\JASON'S\AppData\Roaming\vertcoin-ocm\verthash-miner-tmpl.conf]%APPDATA%\vertcoin-ocm on Windows
$HOME/.vertcoin-ocm on Linux

-->

**Comment by KforG** [comment]
> GPU [NVIDIA GeForce GTX 260]
While it's not the most common reason for that error, your GPU is most definitely too old. As is specified in the readme you need 2GB or more VRAM.

**Comment by nellythe1th** [comment]
i read the readme and found that the gtx 3 and above is required. so off to find a newer card. thank you for you help have a good day
