### ISSUE TITLE
Vertcoin.ocm: checks failed

### ISSUE THREAD

**Issue by massa12** [vertcoin-project/one-click-miner-vnext#340]
Please help me fix this problem ...

![image](https://user-images.githubusercontent.com/83688665/117099835-81c54c00-ad72-11eb-8ba5-fc744b4a3a8a.png)

debug.log

2021/05/05 06:56:26.679587 OCM v2.1-beta2-7f826b5 Started up
2021/05/05 06:56:26.966162 [INFO] User IETF is cs-CZ
2021/05/05 06:56:26.966162 [INFO] Matched tag is en-u-rg-czzzzz
2021/05/05 06:56:26.966162 [INFO] Returning locale en
2021/05/05 06:56:27.033061 [INFO] Checking wallet..
2021/05/05 06:56:27.033580 [INFO] Initializing wallet X3La18jQpMkas9TVXDBgZhPhfegfgAn53s
2021/05/05 06:56:27.034095 [INFO] Wallet initialized: 1
2021/05/05 06:56:27.307491 [DEBUG] GPU [NVIDIA GeForce GT 730M] matched regex [.*NVIDIA.*]
2021/05/05 06:56:27.307491 [DEBUG] GPU [Intel(R) HD Graphics Family] matched regex [.*Intel.*]
2021/05/05 06:56:27.363378 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/05/05 06:56:27.363378 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/05/05 06:56:27.363378 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/05/05 06:56:27.363378 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/05/05 06:56:27.363378 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/05/05 06:56:27.363378 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/05/05 06:56:27.363378 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/05/05 06:56:27.363378 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/05/05 06:56:27.363378 [DEBUG] Not adding already present multi-gpu binary [VerthashMiner.exe] again
2021/05/05 06:56:27.363378 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/05/05 06:56:27.363378 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/05/05 06:56:27.363378 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/05/05 06:56:27.363916 [DEBUG] [Miner windows/3]Daemon file already exists
2021/05/05 06:56:27.381550 [DEBUG] [Miner windows/3]Daemon file is available and correct
2021/05/05 06:56:27.382550 [DEBUG] [Miner windows/3]Removing unpack directory
2021/05/05 06:56:28.401253 [DEBUG] [Miner windows/3](Re)creating unpack directory
2021/05/05 06:56:34.110028 [DEBUG] Launching C:\Users\Petr\AppData\Roaming\vertcoin-ocm\miners\unpacked-e5af5ab19154f6ee57db22645a43200336e8017865c71505ae669af19243449e\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\Petr\AppData\Roaming\vertcoin-ocm\verthash-miner-tmpl.conf]
2021/05/05 06:56:34.625742 [DEBUG] [VerthashMiner] [2021-05-05 06:56:34] INFO  Found 1 OpenCL devices.
2021/05/05 06:56:34.626809 [DEBUG] [VerthashMiner] [2021-05-05 06:56:34] WARN  Failed to initialize CUDA. error code: 35
2021/05/05 06:56:34.626809 [DEBUG] [VerthashMiner] [2021-05-05 06:56:34] WARN  CUDA devices will be unavailable.
2021/05/05 06:56:34.628937 [DEBUG] [VerthashMiner] [2021-05-05 06:56:34] INFO  Configuration file: (C:\Users\Petr\AppData\Roaming\vertcoin-ocm\verthash-miner-tmpl.conf) has been generated.
2021/05/05 06:56:34.660009 [DEBUG]Entering device block
2021/05/05 06:56:34.660009 [DEBUG]Exiting device block
2021/05/05 06:56:34.660009 [DEBUG]{0  false Intel(R) HD Graphics 4400 Intel(R) Corporation}
2021/05/05 06:56:34.660009 [DEBUG]Intel disabled.
2021/05/05 06:56:34.660009 [DEBUG]Entering device block
2021/05/05 06:56:34.660009 [DEBUG]Exiting device block
2021/05/05 06:56:34.660009 [DEBUG]{0  false  }
2021/05/05 06:56:34.661052 [DEBUG] AvailableGPUs called
2021/05/05 06:56:34.663108 [DEBUG] Launching C:\Users\Petr\AppData\Roaming\vertcoin-ocm\miners\unpacked-e5af5ab19154f6ee57db22645a43200336e8017865c71505ae669af19243449e\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\Petr\AppData\Roaming\vertcoin-ocm\verthash-miner-tmp.conf]
2021/05/05 06:56:34.742574 [DEBUG] [VerthashMiner] [2021-05-05 06:56:34] INFO  Found 1 OpenCL devices.
2021/05/05 06:56:34.743651 [DEBUG] [VerthashMiner] [2021-05-05 06:56:34] WARN  Failed to initialize CUDA. error code: 35
2021/05/05 06:56:34.743651 [DEBUG] [VerthashMiner] [2021-05-05 06:56:34] WARN  CUDA devices will be unavailable.
2021/05/05 06:56:34.745764 [DEBUG] [VerthashMiner] [2021-05-05 06:56:34] INFO  Configuration file: (C:\Users\Petr\AppData\Roaming\vertcoin-ocm\verthash-miner-tmp.conf) has been generated.
2021/05/05 06:56:34.826019 [INFO] Starting mining process...
2021/05/05 06:56:34.826526 [DEBUG] Nethash: 0
2021/05/05 06:56:34.826526 [ERROR] Error fetching balance from backend: Get "balance/76a914a81e914aaea20b4b4d9476c084aea0e6d65ff7af88ac": unsupported protocol scheme ""
2021/05/05 06:56:34.826526 [INFO] Updating pending pool payout...
2021/05/05 06:56:34.826526 [DEBUG] [Miner windows/3]Daemon file already exists
2021/05/05 06:56:34.848074 [DEBUG] [Miner windows/3]Daemon file is available and correct
2021/05/05 06:56:34.848074 [DEBUG] [Miner windows/3]Removing unpack directory
2021/05/05 06:56:34.980417 [ERROR] Error fetching balance from backend: Get "balance/76a914a81e914aaea20b4b4d9476c084aea0e6d65ff7af88ac": unsupported protocol scheme ""
2021/05/05 06:56:34.980967 [INFO] Updating pending pool payout...
2021/05/05 06:56:35.854509 [DEBUG] [Miner windows/3](Re)creating unpack directory
2021/05/05 06:56:36.087195 [DEBUG] AvailableGPUs called
2021/05/05 06:56:36.088338 [DEBUG] Launching C:\Users\Petr\AppData\Roaming\vertcoin-ocm\miners\unpacked-e5af5ab19154f6ee57db22645a43200336e8017865c71505ae669af19243449e\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\Petr\AppData\Roaming\vertcoin-ocm\verthash-miner-tmp.conf]
2021/05/05 06:56:36.170401 [DEBUG] [VerthashMiner] [2021-05-05 06:56:36] INFO  Found 1 OpenCL devices.
2021/05/05 06:56:36.171466 [DEBUG] [VerthashMiner] [2021-05-05 06:56:36] WARN  Failed to initialize CUDA. error code: 35
2021/05/05 06:56:36.171466 [DEBUG] [VerthashMiner] [2021-05-05 06:56:36] WARN  CUDA devices will be unavailable.
2021/05/05 06:56:36.173576 [DEBUG] [VerthashMiner] [2021-05-05 06:56:36] INFO  Configuration file: (C:\Users\Petr\AppData\Roaming\vertcoin-ocm\verthash-miner-tmp.conf) has been generated.
2021/05/05 06:56:36.196757 [DEBUG] Launching C:\Users\Petr\AppData\Roaming\vertcoin-ocm\miners\unpacked-e5af5ab19154f6ee57db22645a43200336e8017865c71505ae669af19243449e\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--conf C:\Users\Petr\AppData\Roaming\vertcoin-ocm\verthash-miner.conf]
2021/05/05 06:56:36.274204 [DEBUG] [VerthashMiner] [2021-05-05 06:56:36] INFO  Found 1 OpenCL devices.
2021/05/05 06:56:36.275273 [DEBUG] [VerthashMiner] [2021-05-05 06:56:36] WARN  Failed to initialize CUDA. error code: 35
2021/05/05 06:56:36.275273 [DEBUG] [VerthashMiner] [2021-05-05 06:56:36] WARN  CUDA devices will be unavailable.
2021/05/05 06:56:36.275788 [DEBUG] [VerthashMiner] [2021-05-05 06:56:36] INFO  Using a configuration file (C:\Users\Petr\AppData\Roaming\vertcoin-ocm\verthash-miner.conf)
2021/05/05 06:56:36.275788 [DEBUG] [VerthashMiner] [2021-05-05 06:56:36] INFO  Loading verthash data file...
2021/05/05 06:56:37.077921 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] INFO  Verthash data file has been loaded succesfully!
2021/05/05 06:56:37.077921 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] WARN  Verthash data file verification stage is disabled!
2021/05/05 06:56:37.077921 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] INFO  Using protocol: Stratum.
2021/05/05 06:56:37.078438 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] WARN  Failed to get a "CoinbaseAddress" option inside "Connection" section. Setting to ""
2021/05/05 06:56:37.078438 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] WARN  Failed to get a "CoinbaseSignature" option inside "Connection" section. Setting to ""
2021/05/05 06:56:37.078950 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] WARN  Failed to get a "SSLCertificateFileName" option inside "Connection" section. Setting to ""
2021/05/05 06:56:37.078950 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] WARN  Failed to get a "Proxy" option inside "Connection" section. Setting to ""
2021/05/05 06:56:37.079469 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] WARN  Failed to get a "Redirect" option inside "Connection" section. Setting to "true"
2021/05/05 06:56:37.079469 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] WARN  Failed to get a "LongPoll" option inside "Connection" section. Setting to "true"
2021/05/05 06:56:37.079983 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] WARN  Failed to get a "LongPollTimeout" option inside "Connection" section. Setting to "0"
2021/05/05 06:56:37.079983 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] WARN  Failed to get a "Scantime" option inside "Connection" section. Setting to "5"
2021/05/05 06:56:37.079983 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] WARN  Failed to get a "Retries" option inside "Connection" section. Setting to "-1"
2021/05/05 06:56:37.080500 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] WARN  Failed to get a "RetryPause" option inside "Connection" section. Setting to "5"
2021/05/05 06:56:37.080500 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] WARN  Failed to get a "ProtocolDump" option inside "Connection" section. Setting to "false"
2021/05/05 06:56:37.081012 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] INFO  Miner has been successfully configured! (Errors: 0, Warnings: 12)
2021/05/05 06:56:37.081012 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] WARN  Found 0 configured workers. Exiting...
2021/05/05 06:56:37.213422 [INFO] Miner [VerthashMiner.exe] stopped running.
2021/05/05 06:56:37.213422 [INFO] Restarting miner [VerthashMiner.exe]
2021/05/05 06:56:37.215218 [DEBUG] Launching C:\Users\Petr\AppData\Roaming\vertcoin-ocm\miners\unpacked-e5af5ab19154f6ee57db22645a43200336e8017865c71505ae669af19243449e\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--conf C:\Users\Petr\AppData\Roaming\vertcoin-ocm\verthash-miner.conf]
2021/05/05 06:56:37.308353 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] INFO  Found 1 OpenCL devices.
2021/05/05 06:56:37.309398 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] WARN  Failed to initialize CUDA. error code: 35
2021/05/05 06:56:37.309398 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] WARN  CUDA devices will be unavailable.
2021/05/05 06:56:37.309917 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] INFO  Using a configuration file (C:\Users\Petr\AppData\Roaming\vertcoin-ocm\verthash-miner.conf)
2021/05/05 06:56:37.310431 [DEBUG] [VerthashMiner] [2021-05-05 06:56:37] INFO  Loading verthash data file...
2021/05/05 06:56:38.106245 [DEBUG] [VerthashMiner] [2021-05-05 06:56:38] INFO  Verthash data file has been loaded succesfully!
2021/05/05 06:56:38.106245 [DEBUG] [VerthashMiner] [2021-05-05 06:56:38] WARN  Verthash data file verification stage is disabled!
2021/05/05 06:56:38.106245 [DEBUG] [VerthashMiner] [2021-05-05 06:56:38] INFO  Using protocol: Stratum.
2021/05/05 06:56:38.106760 [DEBUG] [VerthashMiner] [2021-05-05 06:56:38] WARN  Failed to get a "CoinbaseAddress" option inside "Connection" section. Setting to ""
2021/05/05 06:56:38.106760 [DEBUG] [VerthashMiner] [2021-05-05 06:56:38] WARN  Failed to get a "CoinbaseSignature" option inside "Connection" section. Setting to ""
2021/05/05 06:56:38.106760 [DEBUG] [VerthashMiner] [2021-05-05 06:56:38] WARN  Failed to get a "SSLCertificateFileName" option inside "Connection" section. Setting to ""
2021/05/05 06:56:38.107280 [DEBUG] [VerthashMiner] [2021-05-05 06:56:38] WARN  Failed to get a "Proxy" option inside "Connection" section. Setting to ""
2021/05/05 06:56:38.107280 [DEBUG] [VerthashMiner] [2021-05-05 06:56:38] WARN  Failed to get a "Redirect" option inside "Connection" section. Setting to "true"
2021/05/05 06:56:38.107827 [DEBUG] [VerthashMiner] [2021-05-05 06:56:38] WARN  Failed to get a "LongPoll" option inside "Connection" section. Setting to "true"
2021/05/05 06:56:38.107827 [DEBUG] [VerthashMiner] [2021-05-05 06:56:38] WARN  Failed to get a "LongPollTimeout" option inside "Connection" section. Setting to "0"
2021/05/05 06:56:38.107827 [DEBUG] [VerthashMiner] [2021-05-05 06:56:38] WARN  Failed to get a "Scantime" option inside "Connection" section. Setting to "5"
2021/05/05 06:56:38.108338 [DEBUG] [VerthashMiner] [2021-05-05 06:56:38] WARN  Failed to get a "Retries" option inside "Connection" section. Setting to "-1"
2021/05/05 06:56:38.108338 [DEBUG] [VerthashMiner] [2021-05-05 06:56:38] WARN  Failed to get a "RetryPause" option inside "Connection" section. Setting to "5"
2021/05/05 06:56:38.108338 [DEBUG] [VerthashMiner] [2021-05-05 06:56:38] WARN  Failed to get a "ProtocolDump" option inside "Connection" section. Setting to "false"
2021/05/05 06:56:38.108851 [DEBUG] [VerthashMiner] [2021-05-05 06:56:38] INFO  Miner has been successfully configured! (Errors: 0, Warnings: 12)
2021/05/05 06:56:38.108851 [DEBUG] [VerthashMiner] [2021-05-05 06:56:38] WARN  Found 0 configured workers. Exiting...
2021/05/05 06:56:39.222687 [INFO] Miner [VerthashMiner.exe] stopped running.
2021/05/05 06:56:39.222687 [INFO] Restarting miner [VerthashMiner.exe]
2021/05/05 06:56:39.226853 [DEBUG] Launching C:\Users\Petr\AppData\Roaming\vertcoin-ocm\miners\unpacked-e5af5ab19154f6ee57db22645a43200336e8017865c71505ae669af19243449e\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--conf C:\Users\Petr\AppData\Roaming\vertcoin-ocm\verthash-miner.conf]
2021/05/05 06:56:39.346669 [DEBUG] [VerthashMiner] [2021-05-05 06:56:39] INFO  Found 1 OpenCL devices.
2021/05/05 06:56:39.348281 [DEBUG] [VerthashMiner] [2021-05-05 06:56:39] WARN  Failed to initialize CUDA. error code: 35
2021/05/05 06:56:39.348281 [DEBUG] [VerthashMiner] [2021-05-05 06:56:39] WARN  CUDA devices will be unavailable.
2021/05/05 06:56:39.348794 [DEBUG] [VerthashMiner] [2021-05-05 06:56:39] INFO  Using a configuration file (C:\Users\Petr\AppData\Roaming\vertcoin-ocm\verthash-miner.conf)
2021/05/05 06:56:39.348794 [DEBUG] [VerthashMiner] [2021-05-05 06:56:39] INFO  Loading verthash data file...
2021/05/05 06:56:40.117874 [DEBUG] [VerthashMiner] [2021-05-05 06:56:40] INFO  Verthash data file has been loaded succesfully!
2021/05/05 06:56:40.117874 [DEBUG] [VerthashMiner] [2021-05-05 06:56:40] WARN  Verthash data file verification stage is disabled!
2021/05/05 06:56:40.117874 [DEBUG] [VerthashMiner] [2021-05-05 06:56:40] INFO  Using protocol: Stratum.
2021/05/05 06:56:40.117874 [DEBUG] [VerthashMiner] [2021-05-05 06:56:40] WARN  Failed to get a "CoinbaseAddress" option inside "Connection" section. Setting to ""
2021/05/05 06:56:40.118394 [DEBUG] [VerthashMiner] [2021-05-05 06:56:40] WARN  Failed to get a "CoinbaseSignature" option inside "Connection" section. Setting to ""
2021/05/05 06:56:40.118394 [DEBUG] [VerthashMiner] [2021-05-05 06:56:40] WARN  Failed to get a "SSLCertificateFileName" option inside "Connection" section. Setting to ""
2021/05/05 06:56:40.118907 [DEBUG] [VerthashMiner] [2021-05-05 06:56:40] WARN  Failed to get a "Proxy" option inside "Connection" section. Setting to ""
2021/05/05 06:56:40.118907 [DEBUG] [VerthashMiner] [2021-05-05 06:56:40] WARN  Failed to get a "Redirect" option inside "Connection" section. Setting to "true"
2021/05/05 06:56:40.118907 [DEBUG] [VerthashMiner] [2021-05-05 06:56:40] WARN  Failed to get a "LongPoll" option inside "Connection" section. Setting to "true"
2021/05/05 06:56:40.119419 [DEBUG] [VerthashMiner] [2021-05-05 06:56:40] WARN  Failed to get a "LongPollTimeout" option inside "Connection" section. Setting to "0"
2021/05/05 06:56:40.119419 [DEBUG] [VerthashMiner] [2021-05-05 06:56:40] WARN  Failed to get a "Scantime" option inside "Connection" section. Setting to "5"
2021/05/05 06:56:40.119932 [DEBUG] [VerthashMiner] [2021-05-05 06:56:40] WARN  Failed to get a "Retries" option inside "Connection" section. Setting to "-1"
2021/05/05 06:56:40.119932 [DEBUG] [VerthashMiner] [2021-05-05 06:56:40] WARN  Failed to get a "RetryPause" option inside "Connection" section. Setting to "5"
2021/05/05 06:56:40.119932 [DEBUG] [VerthashMiner] [2021-05-05 06:56:40] WARN  Failed to get a "ProtocolDump" option inside "Connection" section. Setting to "false"
2021/05/05 06:56:40.120437 [DEBUG] [VerthashMiner] [2021-05-05 06:56:40] INFO  Miner has been successfully configured! (Errors: 0, Warnings: 12)
2021/05/05 06:56:40.120437 [DEBUG] [VerthashMiner] [2021-05-05 06:56:40] WARN  Found 0 configured workers. Exiting...
2021/05/05 06:56:41.245702 [INFO] Miner [VerthashMiner.exe] stopped running.
2021/05/05 06:56:41.245702 [INFO] Restarting miner [VerthashMiner.exe]
2021/05/05 06:56:41.249828 [DEBUG] Launching C:\Users\Petr\AppData\Roaming\vertcoin-ocm\miners\unpacked-e5af5ab19154f6ee57db22645a43200336e8017865c71505ae669af19243449e\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--conf C:\Users\Petr\AppData\Roaming\vertcoin-ocm\verthash-miner.conf]
2021/05/05 06:56:41.450177 [DEBUG] [VerthashMiner] [2021-05-05 06:56:41] INFO  Found 1 OpenCL devices.
2021/05/05 06:56:41.451817 [DEBUG] [VerthashMiner] [2021-05-05 06:56:41] WARN  Failed to initialize CUDA. error code: 35
2021/05/05 06:56:41.452336 [DEBUG] [VerthashMiner] [2021-05-05 06:56:41] WARN  CUDA devices will be unavailable.
2021/05/05 06:56:41.452858 [DEBUG] [VerthashMiner] [2021-05-05 06:56:41] INFO  Using a configuration file (C:\Users\Petr\AppData\Roaming\vertcoin-ocm\verthash-miner.conf)
2021/05/05 06:56:41.452858 [DEBUG] [VerthashMiner] [2021-05-05 06:56:41] INFO  Loading verthash data file...
2021/05/05 06:56:42.111725 [DEBUG] [VerthashMiner] [2021-05-05 06:56:42] INFO  Verthash data file has been loaded succesfully!
2021/05/05 06:56:42.111725 [DEBUG] [VerthashMiner] [2021-05-05 06:56:42] WARN  Verthash data file verification stage is disabled!
2021/05/05 06:56:42.111725 [DEBUG] [VerthashMiner] [2021-05-05 06:56:42] INFO  Using protocol: Stratum.
2021/05/05 06:56:42.111725 [DEBUG] [VerthashMiner] [2021-05-05 06:56:42] WARN  Failed to get a "CoinbaseAddress" option inside "Connection" section. Setting to ""
2021/05/05 06:56:42.112242 [DEBUG] [VerthashMiner] [2021-05-05 06:56:42] WARN  Failed to get a "CoinbaseSignature" option inside "Connection" section. Setting to ""
2021/05/05 06:56:42.112242 [DEBUG] [VerthashMiner] [2021-05-05 06:56:42] WARN  Failed to get a "SSLCertificateFileName" option inside "Connection" section. Setting to ""
2021/05/05 06:56:42.112754 [DEBUG] [VerthashMiner] [2021-05-05 06:56:42] WARN  Failed to get a "Proxy" option inside "Connection" section. Setting to ""
2021/05/05 06:56:42.112754 [DEBUG] [VerthashMiner] [2021-05-05 06:56:42] WARN  Failed to get a "Redirect" option inside "Connection" section. Setting to "true"
2021/05/05 06:56:42.112754 [DEBUG] [VerthashMiner] [2021-05-05 06:56:42] WARN  Failed to get a "LongPoll" option inside "Connection" section. Setting to "true"
2021/05/05 06:56:42.113268 [DEBUG] [VerthashMiner] [2021-05-05 06:56:42] WARN  Failed to get a "LongPollTimeout" option inside "Connection" section. Setting to "0"
2021/05/05 06:56:42.113268 [DEBUG] [VerthashMiner] [2021-05-05 06:56:42] WARN  Failed to get a "Scantime" option inside "Connection" section. Setting to "5"
2021/05/05 06:56:42.113780 [DEBUG] [VerthashMiner] [2021-05-05 06:56:42] WARN  Failed to get a "Retries" option inside "Connection" section. Setting to "-1"
2021/05/05 06:56:42.113780 [DEBUG] [VerthashMiner] [2021-05-05 06:56:42] WARN  Failed to get a "RetryPause" option inside "Connection" section. Setting to "5"
2021/05/05 06:56:42.113780 [DEBUG] [VerthashMiner] [2021-05-05 06:56:42] WARN  Failed to get a "ProtocolDump" option inside "Connection" section. Setting to "false"
2021/05/05 06:56:42.114291 [DEBUG] [VerthashMiner] [2021-05-05 06:56:42] INFO  Miner has been successfully configured! (Errors: 0, Warnings: 12)
2021/05/05 06:56:42.114291 [DEBUG] [VerthashMiner] [2021-05-05 06:56:42] WARN  Found 0 configured workers. Exiting...
2021/05/05 06:56:42.258385 [INFO] Miner [VerthashMiner.exe] stopped running.
2021/05/05 06:56:42.258429 [INFO] Miner [VerthashMiner.exe] is rapidly failing, not restarting it.
2021/05/05 06:56:42.258967 [INFO] Stopping mining process...
2021/05/05 06:56:42.258967 [INFO] Stopped monitoring thread

**Comment by vertiond** [comment]
Mobile graphics chips are not supported.
