### ISSUE TITLE
Checks failed: Failure to configure VerthashMiner.exe: exit status 3221225781

### ISSUE THREAD

**Issue by pn0007** [vertcoin-project/one-click-miner-vnext#345]
Checks failed: Failure to configure VerthashMiner.exe: exit status 3221225781

 cpu

**Comment by decart-hub** [comment]
Same. Tried excluding in defender, tried disabling defender completely, didn't help.

**Comment by vertiond** [comment]
Please check FAQ
https://github.com/vertcoin-project/one-click-miner-vnext#faq
