### ISSUE TITLE
How To FIX Vertcoin One Click Miner Failed To Configure verthashminer.exe for windows 8.1

### ISSUE THREAD

**Issue by sohailshaikh333** [vertcoin-project/one-click-miner-vnext#356]

**Comment by vertiond** [comment]
https://github.com/vertcoin-project/one-click-miner-vnext#i-have-an-error-message-that-reads-failure-to-configure
If the issue is native to Windows 8, then there won't be any help as this software is built and serviced exclusively for Windows 10.
