### ISSUE TITLE
Error [VerthashMiner.exe] is rapidly failing, not restarting it

### ISSUE THREAD

**Issue by maxx4072** [vertcoin-project/one-click-miner-vnext#360]
Unable to mine 

  Miner [VerthashMiner.exe] is rapidly failing, not restarting it

every time

vertcoin-ocm-2.1-beta2-windows-x64.zip

Windows 10 H20 Dell T 3610 64 gb ram, Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz   3.60 GHz

NA

See debug file 
[debug.log](https://github.com/vertcoin-project/one-click-miner-vnext/files/6467807/debug.log)
![error 1](https://user-images.githubusercontent.com/71197400/118014586-5ff33880-b321-11eb-9413-db9a991e1b5a.png)

Its an old vid card is my guess GTX 650 TI Boost sc I had laying around 

Thank you!

**Comment by maxx4072** [comment]
I also tried numerous versions of verthasminer.exe  with window defended disable firewall antivirus added folder and file exclusions also.

**Comment by maxx4072** [comment]
2021/05/13 07:33:51.795362 [DEBUG] [VerthashMiner] [2021-05-13 07:33:51] INFO  Found 1 OpenCL devices.
2021/05/13 07:33:51.808916 [DEBUG] [VerthashMiner] [2021-05-13 07:33:51] WARN  Unsupported SM 3.0 device GeForce GTX 650 Ti BOOST has been transfered to the OpenCL backend
2021/05/13 07:33:51.809421 [DEBUG] [VerthashMiner] [2021-05-13 07:33:51] WARN  To use this device on CUDA backend, software must be compiled with CUDA 10.2 or lower!
2021/05/13 07:33:51.809436 [DEBUG] [VerthashMiner] [2021-05-13 07:33:51] INFO  Found 0 CUDA devices
2021/05/13 07:33:51.809954 [DEBUG] [VerthashMiner] [2021-05-13 07:33:51] INFO  Using a configuration file (C:\Users\root\AppData\Roaming\vertcoin-ocm\verthash-miner.conf)
2021/05/13 07:33:51.809954 [DEBUG] [VerthashMiner] [2021-05-13 07:33:51] INFO  Loading verthash data file...
2021/05/13 07:33:52.313237 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] INFO  Verthash data file has been loaded succesfully!
2021/05/13 07:33:52.313237 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] WARN  Verthash data file verification stage is disabled!
2021/05/13 07:33:52.313237 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] INFO  Using protocol: Stratum.
2021/05/13 07:33:52.313237 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] WARN  Failed to get a "CoinbaseAddress" option inside "Connection" section. Setting to ""
2021/05/13 07:33:52.313237 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] WARN  Failed to get a "CoinbaseSignature" option inside "Connection" section. Setting to ""
2021/05/13 07:33:52.313237 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] WARN  Failed to get a "SSLCertificateFileName" option inside "Connection" section. Setting to ""
2021/05/13 07:33:52.313237 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] WARN  Failed to get a "Proxy" option inside "Connection" section. Setting to ""
2021/05/13 07:33:52.313237 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] WARN  Failed to get a "Redirect" option inside "Connection" section. Setting to "true"
2021/05/13 07:33:52.313237 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] WARN  Failed to get a "LongPoll" option inside "Connection" section. Setting to "true"
2021/05/13 07:33:52.313237 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] WARN  Failed to get a "LongPollTimeout" option inside "Connection" section. Setting to "0"
2021/05/13 07:33:52.313237 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] WARN  Failed to get a "Scantime" option inside "Connection" section. Setting to "5"
2021/05/13 07:33:52.313237 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] WARN  Failed to get a "Retries" option inside "Connection" section. Setting to "-1"
2021/05/13 07:33:52.313237 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] WARN  Failed to get a "RetryPause" option inside "Connection" section. Setting to "5"
2021/05/13 07:33:52.313237 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] WARN  Failed to get a "ProtocolDump" option inside "Connection" section. Setting to "false"
2021/05/13 07:33:52.313237 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] INFO  Miner has been successfully configured! (Errors: 0, Warnings: 12)
2021/05/13 07:33:52.323241 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] INFO  Configured 1(CL) and 0(CUDA) workers
2021/05/13 07:33:52.327418 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] DEBUG Found 1 NVML device
2021/05/13 07:33:52.341624 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] INFO  1 miner threads started, using Verthash algorithm.
2021/05/13 07:33:52.341624 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] INFO  Starting Stratum on stratum+tcp://vtc.suprnova.cc:1776
2021/05/13 07:33:52.528428 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] ERROR cl_device(0):Failed to copy Verthash data to the GPU memory. error code: -4
2021/05/13 07:33:52.528428 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] INFO  cl_device(0):Exiting worker thread id(0)...
2021/05/13 07:33:52.538493 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] INFO  All worker threads have been exited.
2021/05/13 07:33:52.538493 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] INFO  WorkIO thread has been finished.
2021/05/13 07:33:52.538493 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] INFO  Waiting for worker threads to exit...
2021/05/13 07:33:52.538493 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] ERROR stratum_recv_line failed to parse a newline-terminated string
2021/05/13 07:33:52.538493 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] INFO  Waiting for stratum thread to exit...
2021/05/13 07:33:52.538493 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] ERROR ...retry after 5 seconds
2021/05/13 07:33:52.558566 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] DEBUG Stratum thread exit
2021/05/13 07:33:52.558566 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] INFO  Freeing allocated memory...
2021/05/13 07:33:52.603057 [DEBUG] [VerthashMiner] [2021-05-13 07:33:52] INFO  Application has been exited gracefully.
2021/05/13 07:33:52.729137 [INFO] Miner [VerthashMiner.exe] stopped running.
2021/05/13 07:33:52.729137 [INFO] Restarting miner [VerthashMiner.exe]

**Comment by vertiond** [comment]
It seems this card is too old and I haven't seen anyone else get one to work.  It would be an issue with the upstream [VerthashMiner](https://github.com/CryptoGraphics/VerthashMiner) anyway.
