### ISSUE TITLE
Vertcoin one-click-miner not using GPU

### ISSUE THREAD

**Issue by jninjadude** [vertcoin-project/one-click-miner-vnext#369]
When I run the one-click-miner it doesnt use my GPU. It either is using my cpu or something else. My hashrate is around 20kh/s. If i click the "use integrated graphics" it will use my integrated graphics which gives me a hashrate of about 60 kh/s. I have tried changing my graphic settings to use my gpu when running the application. I have a geforce gtx 960M with 4 gb. 

 I expected it to use the best graphics I have availible or 

 The program runs perfectly, i just have no options to select graphics to use expect integrated graphics.

 click to run the program. 

 beta 2 latest version

 windows 10 

 Im sorry I dont have any more info. I just run it and it just uses my integrated graphics or something else entirely. It just doesnt find my gpu.

**Comment by vertiond** [comment]
Mobiles graphics chips do not seem to be supported by VerthashMiner.  You would submit an issue to this repo: https://github.com/CryptoGraphics/VerthashMiner
