### ISSUE TITLE
Always getting about 500kH/s even with my 2070 Nvidia GPU

### ISSUE THREAD

**Issue by Panto9** [vertcoin-project/one-click-miner-vnext#372]
I expected hashrates in the mega, but getting in kilo

Hashrates are always between 300 to 520 kH/s

Always

v2.1-beta2-7f826b5

Windows 10, Nvidia 2070 Super with MAx Q Design (Lenovo Legion 7)

**Comment by KforG** [comment]
You can not compare hashrates across algorithms. Vertcoin is using the Verthash algorithm.

Around 500 kH/s is the expected hashrate for that GPU on this algorithm.
