### ISSUE TITLE
One Click Miner vNext 2.1-beta2 Check Fails

### ISSUE THREAD

**Issue by QuackPewDuck** [vertcoin-project/one-click-miner-vnext#373]
It does not install correctly. Debug does not stop running.

I should be able to install the click on miner. The last version worked fine.

It does not install correctly. Debug does not stop running.
![OneClickMiner](https://user-images.githubusercontent.com/85125854/120222465-fa9eb300-c20d-11eb-9ddc-42bd49d5ad64.PNG)

This happens every time.

One Click Miner vNext 2.1-beta2 

Windows

![OneClickMiner](https://user-images.githubusercontent.com/85125854/120222673-5406e200-c20e-11eb-82c4-48b0ee0a0bd4.PNG)

**Comment by KforG** [comment]
This error usually occurs when the user's antivirus removes/interferes with the miner. You may need to add an exclusion for `%appdata%\vertcoin-ocm`

**Comment by QuackPewDuck** [comment]
I did the most basic IT solution to fix it. Restart PC. LOL :).
