### ISSUE TITLE
Failure to configure Verhashminer.exe: exit status 3221225781

### ISSUE THREAD

**Issue by nvnt-in** [vertcoin-project/one-click-miner-vnext#375]

**Comment by nvnt-in** [comment]
[debug.log](https://github.com/vertcoin-project/one-click-miner-vnext/files/6586316/debug.log)

**Comment by nvnt-in** [comment]
Please help, even after reboot issue not fixed

**Comment by nvnt-in** [comment]
This seems to be software dependencies issue. Could some please tell we what is the software dependency for Vertcoin one click miner. As i googled and seems that some dll is missing, but not sure which application dll file is missing

**Comment by KforG** [comment]
> GPU [NVIDIA GeForce GT 435M]

This is your problem. Your GPU does not live up to the minimum requirements as stated by the readme.
