### ISSUE TITLE
Pool Payment

### ISSUE THREAD

**Issue by smyrna355** [vertcoin-project/one-click-miner-vnext#381]
Vertcoin Pool payment that I scraped is not coming
 I want payment made

![vertcoin_error](https://user-images.githubusercontent.com/86128771/122609891-66df3a80-d087-11eb-8437-3b068fa97865.JPG)

-->

**Comment by KforG** [comment]
You have not reached the minimum payout of the pool yet. You can see it on both the pool's front page and miner dashboard (Click the green link).

**Comment by smyrna355** [comment]
Thank you for the information @KforG
