### ISSUE TITLE
Checks Failed

### ISSUE THREAD

**Issue by Dasipoint** [vertcoin-project/one-click-miner-vnext#383]

**Comment by Dasipoint** [comment]
I have just installed the vertcoin miner and every time I start it, I get a checks failed notification. It then tells me to go to settings and click the debug option and save it. I do this but still get the same,"checks failed" message.

**Comment by vertiond** [comment]
Please refer first to the [FAQ](https://github.com/vertcoin-project/one-click-miner-vnext#i-have-an-error-message-that-reads-failure-to-configure)
