### ISSUE TITLE
VTC miner not earning estimated amount 

### ISSUE THREAD

**Issue by micmisiewicz** [vertcoin-project/one-click-miner-vnext#384]
VTC one-click miner estimated mining is between 1.7 VTC and 2.1 VTC in 24h and real-world earning over 24h was only 0.4 VTC 

Be nice to get near 1.5 VTC per 24 h

 the issue is ongoing

win 10 gtx 1080 ti

**Comment by vertiond** [comment]
The 'estimated' is simply a calculation based on your hash rate and the current difficulty.  Each pool has a different structure for payouts but over time you will see that estimation being more accurate.  I would give it 72 hours to judge rather than simply 24 hours.
