### ISSUE TITLE
Mobile app to manage rig hardware usage

### ISSUE THREAD

**Issue by starcheek** [vertcoin-project/one-click-miner-vnext#393]
Hi!

I came up with an idea that there could be One Click Miner mobile app  which could allow user to monitor and control mining rigs (which are connected to OCM) hardware usage, live temperature etc, addresses and other parameters. Basically remote control for OCM.
I think it could be an cool thing which could help a lot of people who are uncertain when they leave their rigs unsupervised.
A similar example of this is [here](https://play.google.com/store/apps/details?id=com.jldev.ethmonitoring&hl=en&gl=US). 

Let me know what you think and if it has support, I would like to participate in contribution.

**Comment by vertiond** [comment]
This sounds cool but isn't in the scope of this specific project repository.  I would recommend taking this idea to the community and if you find someone willing to do the work, initiating a proposal for funding on https://ccs.vertcoin.io
