### ISSUE TITLE
Checks Failed Error that I can't troubleshoot

### ISSUE THREAD

**Issue by thejiggler101** [vertcoin-project/one-click-miner-vnext#394]
So I downloaded the program on my laptop (I already use it problem free on my desktop) and I have received this error
![image](https://user-images.githubusercontent.com/81394096/125552676-d4501292-3f22-4833-b245-f98f5fa94fe0.png)

More screenshots of the file path:
When I'm running the program
![image](https://user-images.githubusercontent.com/81394096/125552805-d8b623d5-d9fa-4e9d-b544-847ca11d22bd.png)

When I'm not running the program
![image](https://user-images.githubusercontent.com/81394096/125552960-6e88c979-7e15-40d6-b976-b52ff0d3feee.png)

**Comment by KforG** [comment]
Your antivirus is removing the miner. You might need to exclude the miner which is located in `%appdata%\vertcoin-ocm`.

Also, there's a new release out.
