### ISSUE TITLE
failure to configure verthashminer.exe exit status 3221225477

### ISSUE THREAD

**Issue by adilbhatofficial** [vertcoin-project/one-click-miner-vnext#396]
Hi

I try to install vertcoin miner but everytime it says this error ? i added it to windows security exclusions but still same issue 

failure to configure verthashminer.exe exit status 3221225477

ANY HELPS Would be appreciated

**Comment by KforG** [comment]
You may need to exclude the miner which is located in `%appdata%\vertcoin-ocm` instead.

**Comment by adilbhatofficial** [comment]
I did that as well but still same issue i attached some screenshots to see if i did all perfect and have all things i need to mine.

Thanks for helping me , looking for support on this issue :)

https://prnt.sc/1bglmeo
https://prnt.sc/1bglt2i
https://prnt.sc/1bglvgy
https://prnt.sc/1bglxj1
https://prnt.sc/1bgm05x
https://prnt.sc/1bgm2f5
https://prnt.sc/1bgm5iu

**Comment by KforG** [comment]
You don't have any other GPU than the integrated one in your intel processor? It's only on specific generations of CPU's that the integrated mining works.
