### ISSUE TITLE
Missing key value pairs in a few of the frontend/src/i18n/*.json files

### ISSUE THREAD

**Issue by baxter2** [vertcoin-project/one-click-miner-vnext#40]
`es.json`,  `hr.json`,  `sl.json` and `sv.json` are all missing  `obj["generic"]["close"]` and `obj["welcome"]["alreadyrunning"]`

**Comment by gertjaap** [comment]
Need help from the translators here:

@Thatmanontheright  (Spanish, Slovenian)
@Robban1980 (Swedish)

Hungarian: ?

**Comment by Thatmanontheright** [comment]
Submitted Es
