### ISSUE TITLE
False positive with Kaspersky

### ISSUE THREAD

**Issue by dipievil** [vertcoin-project/one-click-miner-vnext#401]
False positive with anti-virus software.

No Trojan alert

Trojan alert.

[https://i.imgur.com/gk95xQv.png](https://i.imgur.com/gk95xQv.png)

Just unpacking the rar with a Win 10 running kapersky.

Version vNext 2.0 Final downloaded from GitHub.

Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz  16 GB Ram / NVIDIA GTX 1050 TI

**Comment by vertiond** [comment]
Yeah, that's to be expected.  Cryptocurrency miners are frequently flagged as malware by all sorts of antivirus software.
