### ISSUE TITLE
Lost coins when sent to wallet

### ISSUE THREAD

**Issue by mhanby1** [vertcoin-project/one-click-miner-vnext#409]
I tried for the first time today to send VTC from the OCM to a Coinomi wallet.  I set up the wallet, pasted the address into OCM along with the OCM password, and sent the entire balance, as this was the only option I had (about 371 VTC).  OCM said that all coins were sent in 10 different transactions, but only 2 of them showed up in my coinomi wallet, totaling about 70 VTC.  Where did the 8 other transactions and 300 VTC go?  It has been about 12 hours now.

OCM v2.0-rc12-e88c4e4

When I clicked on the numbered transaction links on OCM, it took me to an "insight" page that said "transaction not found"

The log surrounding the time that the coins were sent is included.
The 2 transactions that did go through are:
b96db15a95b25d664a0d56fa0742440b15c810d071dd534a1b177f1881e4b502
2108fc7e8450dc700b197928e2d141f3d96fd7908fc5370b65624486cefb3b53
they appear to be the first 2 out of 10

**Comment by Kuy88** [comment]
Good
