### ISSUE TITLE
Earnings

### ISSUE THREAD

**Issue by RyRyGitHub** [vertcoin-project/one-click-miner-vnext#415]
expected earning and actual earnings are wildly different
 the two to be at least somewhat close and not several decimal places different. 

OCM V2.1

GPU Window 10 GForce RTX

**Comment by vertiond** [comment]
What is your hashrate?

**Comment by RyRyGitHub** [comment]
Anywhere from 263MH/s to 1GH/sThe estimated VTC per 24hrs varies from 65 to >500 and often in the thousands for extended periods of time.  Yet the actual rewards are like 0.03.   Can you help correct this? Sent from Mail for Windows From: vertionSent: Friday, August 27, 2021 9:22 PMTo: vertcoin-project/one-click-miner-vnextCc: RyRyGitHub; AuthorSubject: Re: [vertcoin-project/one-click-miner-vnext] Earnings (#415) What is your hashrate?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pupreti** [comment]
@RyRyGitHub are you from the future and have a killer future GPU that you are getting 1GH/s while mining?
Currently, the total network hash rate is 3GH/s.

Bro, can I get that GPU from you? I can make a killing out of it.

**Comment by RyRyGitHub** [comment]
Haha. 
I swear that is what it was reading on the display. Of course I check this morning and it’s not but this is a photo of this morning’s output which still doesn’t reflect the actual rewards.

**Comment by vertiond** [comment]
You hash rate indicates that something is wrong on your end and is usually caused by too high of overclock.  Reboot your computer and dial it down.  I don't know what your GPU is but when you see a large hash rate far above say 2 MH/s, then it actually isn't mining anything at all.
