### ISSUE TITLE
Uninstalling OCM

### ISSUE THREAD

**Issue by DentFuse** [vertcoin-project/one-click-miner-vnext#416]
Hi, 

Sorry if this is kind of a stupid question, but how do I delete the OCM and all related files such as the Verthash generated? I'd downloaded the exe file and ran it. I had 222Gbs free before mining began and 217Gbs after. The data file in %appdata% was only about 1-2Gbs so I was wondering if the OCM has stored some other stuff somewhere else.

Thanks

**Comment by KforG** [comment]
Besides the OCM executable, OCM only stores data in `%appdata%\vertcoin-ocm`.

**Comment by DentFuse** [comment]
Alright thanks. It should be mentioned somewhere in the ReadMe so that people who don't know about `%appdata%` can delete it  too.
