### ISSUE TITLE
Vertcoin debugging problem

### ISSUE THREAD

**Issue by srikanth74482** [vertcoin-project/one-click-miner-vnext#418]
vertcoin one or more of your miner binaries are showing rapid failures 

Vertcoin doesn't start in begging

It's always showing one or more of your miner binaries are showing rapid failure even I checked in debugging and tested for check in testnet for 30mins to 50 mins but the problem doesn't solved
Please help to get vertcoin mining

https://user-images.githubusercontent.com/66345494/132488535-35f5ade7-bc65-478d-89a4-5559d3c3dfb2.mp4

My system was windows 10 laptop with 2GB vram of intel graphics family and 4GB ram

**Comment by vertiond** [comment]
Your hardware is not supported. https://github.com/vertcoin-project/one-click-miner-vnext#which-gpus-are-supported
