### ISSUE TITLE
OCM showing ~+NAN and my balance showing zero

### ISSUE THREAD

**Issue by dibgit** [vertcoin-project/one-click-miner-vnext#423]

**Comment by TheKaese** [comment]
Currently experiencing this.. Anyone have any ideas?

**Comment by dibgit** [comment]
Personally I don't think OCM is a very good idea for a long term miner.
Now I am using
VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner-0.7.2-CUDA11-windows

It needed a bit of configuration and to run the bat file. but it has better
control on the VTC address.

It runs adequately well.

Thanks & Regards,
Dibyendu.

**Comment by dfoefle** [comment]
Same here. My other pc has balance available, but can't send coins due to 'sending.backend_failure'

**Comment by KforG** [comment]
@dfoefle @TheKaese 
One of OCM's backend servers is temporarily down. It'll be fixed soon. Your coins are safe and mining isn't impacted.
