### ISSUE TITLE
Miner software reported no compatible GPUs

### ISSUE THREAD

**Issue by Nacho1122** [vertcoin-project/one-click-miner-vnext#426]
Apparently there is a GPU compatibility issue, this started happening at 00:37 on 10/14/21.
 start to miner.

 https://imgur.com/RxTFL82

 When starting the miner software

 https://github.com/vertcoin-project/one-click-miner-vnext/releases/tag/2.1-beta3

 Windows 10/ AMD Radeon R9 280x

 -

**Comment by jdmaguire** [comment]
Uninstalled all NVidia drivers and installed the latest. Odd.

**Comment by Leofury77** [comment]
Hi, yes I'm NEW here NOT in General though.
I'm having SAME issue.
I have PowerColor 6900XT Ultimate "no compatible GPUs detected"....
I uninstalled using AMD cleanup Utility, RE installed WHQL driver......SAME ERROR
any suggestions, directions, FIXES?
Thank you

**Comment by KforG** [comment]
It's most often due to antivirus. You may need to add an exclusion to `%appdata%\vertcoin-ocm`
