### ISSUE TITLE
Spendabale Balance is "0" on my OCM

### ISSUE THREAD

**Issue by botamihai** [vertcoin-project/one-click-miner-vnext#434]
Yesterday everything was fine, but today when i started the OCM my Spendable Balance is 0 and my expected earnings are "~+Inf".

**Comment by moval13hint10h** [comment]
Same problem here. When going to "Send coins" it says "backend_failure". I suspect some backend services supporting the one click miner is down.

**Comment by moval13hint10h** [comment]
In my debug log: 2021/11/04 01:31:45.857759 [ERROR] Error fetching balance from backend: invalid character 'I' looking for beginning of value

**Comment by botamihai** [comment]
Thank you for the clarification!
