### ISSUE TITLE
i am not getting vtc

### ISSUE THREAD

**Issue by Sealios** [vertcoin-project/one-click-miner-vnext#441]
i have been mining for the last 5 hours and still havent gotten 0.000001 vtc

![Desktop Screenshot 2021 11 22 - 20 31 31 56](https://user-images.githubusercontent.com/94879029/142959051-db535342-d8f6-4a70-95ac-17ea087af951.png)

 Well it just wont start mining i guesse i=even tho i turned it on 

 The newest one

 Window 64x  Gpu rtx 3060

 Pls fix or give me a reason why this is hapaning

**Comment by KforG** [comment]
Spendable balance is when the pool has paid you. For the coins to go into spendable balance they'll first need to:
Confirm (100 blocks * 2.5 min ≈ 4 hours).
You need to meet the pool's minimum payout, in this case, 0.1 VTC.
The pool needs to find blocks, this should also not be a problem with this pool pool finds one out of five/six blocks.

Click the green link in the middle of the application, it'll bring you to your miner dashboard on the pool.
