### ISSUE TITLE
Mining still at Zerro?

### ISSUE THREAD

**Issue by StueyUnger** [vertcoin-project/one-click-miner-vnext#452]
Miner shows nothing
I did not expect nothing after a few hrs on and off the past few days

The Mining stats are zero 0

Judt open the program

**Comment by KforG** [comment]
Sounds like some antivirus/firewall/router blocking the connection to the pool.

**Comment by StueyUnger** [comment]
I have  Exceptions put in for Defender

**Comment by vertiond** [comment]
Check if your router has 2-way IPS enabled.  You may have to disable that.
