### ISSUE TITLE
Expected earnings halved and nothing added to balance for over 24 hrs

### ISSUE THREAD

**Issue by silvernations** [vertcoin-project/one-click-miner-vnext#453]
So I did some clocking adjustments yesterday and got everything running optimally for my gpu but it was short lived. My earnings is now cut in half but hash rate remains the same and I haven't logged any earnings in over 24 hrs. 

I've had this issue before but learned 2 versions of the miner were running simultaneously and everything returned to normal once I shut off the auto start and made sure only one miner was open. I've tried solving it this way multiple times without any success. 

Version I'm currently using is 2.1-beta4. GPU is a GTX 1650. 

Any help is much appreciated.

Thank you!

**Comment by KforG** [comment]
Vertcoin recently had its second halving, meaning the block reward is cut from 25 VTC to 12.5 VTC.

Your missing payout will most likely be because you haven't reached the pool's minimum payout yet. You can check this out by clicking the green link in OCM, to get to the pools miner dashboard.

**Comment by silvernations** [comment]
It appears you are right. Unfortunate coincidence lol

Thank you!
