### ISSUE TITLE
no me acuerdo la contraseña

### ISSUE THREAD

**Issue by sergiodinapoli12** [vertcoin-project/one-click-miner-vnext#454]
no me acuerdo de la contraseña 
![Sin título](https://user-images.githubusercontent.com/95982882/145691234-2e484600-c944-4cce-aafb-1ca44ab67702.jpg)

**Comment by vertiond** [comment]
Estableció una contraseña cuando ejecutó OCM por primera vez. Debes recordar tu contraseña para enviar monedas. Restablezca su billetera eliminando `key file.hex` en`% appdata% \ vertcoin-ocm`.

**Comment by sergiodinapoli12** [comment]
Listo gracias 

Enviado desde mi iPhone
