### ISSUE TITLE
Nothing Solved

### ISSUE THREAD

**Issue by StueyUnger** [vertcoin-project/one-click-miner-vnext#455]
Cannot use OCM

I expected to be mining Vertcoin, Seems simply download and run.
No, nothing but problems running by many people and I don't see any answers other than the same repetitive 
actions that do nothing or just answering with more questions,  Does this thing actually work?

**Comment by vertiond** [comment]
Read the FAQ and post a more detailed issue next time.

**Comment by StueyUnger** [comment]
See?  Exactly what I said. 
Reply....Read FAQ and blog and blobs and blah fucking blahNo answer..figure shit out yourselvesMore Detail?For what ? To waste more time to get a non answerIf something is this screwy and difficult to set up why bother?
   On Saturday, December 11, 2021, 02:44:52 PM PST, vertion ***@***.***> wrote:  
 
 


Closed #455.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
