### ISSUE TITLE
Vertcoin on windows 10 64bit i am unable to paste receive wallet address in my send screen on vert miner please help

### ISSUE THREAD

**Issue by Bigdaddy1680** [vertcoin-project/one-click-miner-vnext#457]

**Comment by KforG** [comment]
Are you trying to use the mouse? The keyboard shortcut should work.

**Comment by Bigdaddy1680** [comment]
I Pasted Recive Address. But Now i get an error message. I have
attached error message to the email as well as my current balance. Please
help.

**Comment by KforG** [comment]
Github doesn't show files attached to emails. So I can't see it.

**Comment by Bigdaddy1680** [comment]
ok the text in the window when i try to send coins to my coinomi wallet is
this

Failed to send your coins

sending.backend_failier

My vertcoin spendable balance is $5.51.

**Comment by KforG** [comment]
The backend servers were being migrated to other servers around that time, might've been that. Could also just be a temporary outage.
Try again, if it doesn't work I have a tool that you can extract the private key to your wallet with.
