### ISSUE TITLE
Not MINING

### ISSUE THREAD

**Issue by balinbolon** [vertcoin-project/one-click-miner-vnext#459]
Mining Stuck in ~+INFVTC

to present the estimated income: ~+.01VTC

![image](https://user-images.githubusercontent.com/77517414/146828201-c4b99838-d3ef-4dcb-b706-e622157bfe4a.png)

after simultaneously work with Telegram, Discord and 32 Google Tabs

v2.1-beta4-000fc4e

Windows 10 Pro 21H1/RX 550 2GB

**Comment by KforG** [comment]
When you're getting zero kH/s it's usually because something is blocking that connection, either firewall or antivirus.

Some ASUS routers also block the connection if you're using the default setting.
