### ISSUE TITLE
Failure to configure VerthasMiner : exit status 127

### ISSUE THREAD

**Issue by MatteoFlorea** [vertcoin-project/one-click-miner-vnext#463]
I installed ocm and I get the error "Failure to configure VerthasMiner : exit status 127"

![Screenshot_20211229_172550](https://user-images.githubusercontent.com/58531976/147688093-b5212985-7643-41b2-9d37-39dfca82e2db.png)

Os: Endeavour Os (linux-zen kernal)
De: Kde Plasma
Gpu: Gtx 1660 ti

Debug File: [debug.log](https://github.com/vertcoin-project/one-click-miner-vnext/files/7789986/debug.log)

**Comment by KforG** [comment]
Do you have the appropriate Nvidia drivers installed for your GPU?

**Comment by MatteoFlorea** [comment]
> 

Yeah I got the nvidia proprietary drivers

**Comment by KforG** [comment]
Sorry for the late answer.

I'm not sure what is causing your issue, since OCM recognizes your GPU. Although for some reason it seems to check essesively if you have mining with integrated graphics enabled. What happens if you enable that?

**Comment by MatteoFlorea** [comment]
> Sorry for the late answer.
> 
> I'm not sure what is causing your issue, since OCM recognizes your GPU. Although for some reason it seems to check essesively if you have mining with integrated graphics enabled. What happens if you enable that?

Nothing, same problem

**Comment by MSamiMiM** [comment]
Hello
I have the same problem even though I tried all the options. Is there a solution?

**Comment by KforG** [comment]
I don't have a solution for @MatteoFlorea, other than to try using Verthashminer directly and see if that works. Linux OCM install are often harder to debug issues with.

@MSamiMiM are you on Windows or Linux? If you're on Linux, try reinstalling/installing GPU drivers.
If windows, you might need to create an exception in your antivirus for `%appdata%\vertcoin-ocm`

**Comment by vertiond** [comment]
They're on `Endeavour Os (linux-zen kernal)`. There's been similar issues with other random Linux operating systems and I believe it all has to do with installing drivers properly with OpenCL support on the user side. I'm going to close these types of issues from now on.
