### ISSUE TITLE
exit status 3221225477 - Won't start mining.

### ISSUE THREAD

**Issue by kaboddy** [vertcoin-project/one-click-miner-vnext#464]
Ran fine for weeks.  Today though...

Checks failed.  
exit status 3221225477

Restarting doesn't help.

OCM v2.1-beta4-000fc4e

Win10Pro
nvidia 1550 super and 960
I did update nvidia drivers a day ago - not sure if it's related.  Version 497.29.

Avast AV (free) updated as well ... Again, excludes in place but just mentioning.

Log file:
2021/12/30 08:52:23.513388 OCM v2.1-beta4-000fc4e Started up
2021/12/30 08:52:23.515002 [ERROR] Error in getSetting(testnet): not found
2021/12/30 08:52:23.515505 [ERROR] Error in getSetting(testnet): not found
2021/12/30 08:52:25.531102 [ERROR] Unable to fetch node information
%!(EXTRA string=Get "http://127.0.0.1:9171/local_stats": dial tcp 127.0.0.1:9171: connectex: No connection could be made because the target machine actively refused it.)
2021/12/30 08:52:25.531102 [INFO] No local node detected, selecting other public nodes
2021/12/30 08:52:26.894137 [INFO] p2proxy.vertcoin.org: 141.968ms 
2021/12/30 08:52:28.106118 [INFO] mindcraftblocks.com: 32.62265ms 
2021/12/30 08:52:29.333192 [INFO] vtc-fl.javerity.com: 67.5001ms 
2021/12/30 08:52:30.570646 [INFO] vtc-ca.javerity.com: 86.83885ms 
2021/12/30 08:52:31.827121 [INFO] vtc.p2pminers.nl: 126.1244ms 
2021/12/30 08:52:32.973483 [INFO] p2p-usa.xyz: 32.4723ms 
2021/12/30 08:52:34.293126 [INFO] p2p-ekb.xyz: 188.3396ms 
2021/12/30 08:52:35.636874 [INFO] asia.p2p-spb.xyz: 213.13745ms 
2021/12/30 08:52:36.893344 [INFO] p2p-spb.xyz: 142.1827ms 
2021/12/30 08:52:38.202908 [INFO] p2p-south.xyz: 183.50975ms 
2021/12/30 08:52:39.571375 [INFO] siberia.mine.nu: 217.8648ms 
2021/12/30 08:52:41.665371 [INFO] boofpool.ddns.net: 0s 
2021/12/30 08:52:43.077283 [INFO] vtc-brn.webhop.me: 213.0042ms 
2021/12/30 08:52:43.474191 [INFO] boofpool.ddns.net selected, fulfilled all requirements
2021/12/30 08:52:43.474702 [ERROR] Error in getSetting(testnet): not found
2021/12/30 08:52:43.625019 [INFO] User IETF is en-US
2021/12/30 08:52:43.625019 [INFO] Matched tag is en-u-rg-uszzzz
2021/12/30 08:52:43.625019 [INFO] Returning locale en
2021/12/30 08:52:43.655409 [ERROR] Error in getSetting(testnet): not found
2021/12/30 08:52:43.669288 [INFO] Checking wallet..
2021/12/30 08:52:43.669798 [INFO] Initializing wallet blahblah
2021/12/30 08:52:43.670308 [INFO] Wallet initialized: 1
2021/12/30 08:52:43.875381 [DEBUG] GPU [NVIDIA GeForce GTX 1660 SUPER] matched regex [.*NVIDIA.*]
2021/12/30 08:52:43.875381 [DEBUG] GPU [NVIDIA GeForce GTX 960] matched regex [.*NVIDIA.*]
2021/12/30 08:52:43.891225 [ERROR] Error in getSetting(testnet): not found
2021/12/30 08:52:43.891225 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/12/30 08:52:43.891225 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/12/30 08:52:43.891225 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/12/30 08:52:43.891225 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/12/30 08:52:43.891225 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/12/30 08:52:43.891225 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/12/30 08:52:43.891225 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/12/30 08:52:43.891225 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/12/30 08:52:43.891225 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/12/30 08:52:43.891225 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/12/30 08:52:43.891225 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/12/30 08:52:43.891225 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/12/30 08:52:43.891225 [DEBUG] [Miner windows/2]Daemon file already exists
2021/12/30 08:52:43.894801 [DEBUG] [Miner windows/2]Daemon file is available and correct
2021/12/30 08:52:43.894801 [DEBUG] [Miner windows/2]Removing unpack directory
2021/12/30 08:52:44.909503 [DEBUG] [Miner windows/2](Re)creating unpack directory
2021/12/30 08:52:48.312438 [DEBUG] Launching C:\Users\blahblah\vertcoin-ocm\miners\unpacked-blahblah\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\blahblah\Roaming\vertcoin-ocm\verthash-miner-tmpl.conf]
2021/12/30 08:52:48.418313 [DEBUG] [VerthashMiner] [2021-12-30 08:52:48] INFO  Found 0 OpenCL devices.
2021/12/30 08:52:48.449510 [DEBUG] [VerthashMiner] [2021-12-30 08:52:48] INFO  Found 2 CUDA devices
2021/12/30 08:52:48.450037 [DEBUG] [VerthashMiner] [2021-12-30 08:52:48] INFO  Configuration file: (C:\Users\blahblah\Roaming\vertcoin-ocm\verthash-miner-tmpl.conf) has been generated.
2021/12/30 08:52:48.478253 [DEBUG]Entering device block
2021/12/30 08:52:48.478253 [DEBUG]Exiting device block
2021/12/30 08:52:48.478253 [DEBUG]{0  false  }
2021/12/30 08:52:48.478770 [DEBUG]Entering device block
2021/12/30 08:52:48.478770 [DEBUG]Exiting device block
2021/12/30 08:52:48.478770 [DEBUG]{0  false NVIDIA GeForce GTX 1660 SUPER }
2021/12/30 08:52:48.478770 [DEBUG] AvailableGPUs called
2021/12/30 08:52:48.479795 [DEBUG] Launching C:\Users\blahblah\Roaming\vertcoin-ocm\miners\unpacked-blahblah\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\blahblah\Roaming\vertcoin-ocm\verthash-miner-tmp.conf]
2021/12/30 08:52:48.571974 [DEBUG] [VerthashMiner] [2021-12-30 08:52:48] INFO  Found 0 OpenCL devices.
2021/12/30 08:52:48.601506 [DEBUG] [VerthashMiner] [2021-12-30 08:52:48] INFO  Found 2 CUDA devices
2021/12/30 08:52:48.602030 [DEBUG] [VerthashMiner] [2021-12-30 08:52:48] INFO  Configuration file: (C:\Users\blahblah\Roaming\vertcoin-ocm\verthash-miner-tmp.conf) has been generated.
2021/12/30 08:52:48.661175 [INFO] Starting mining process...
2021/12/30 08:52:48.661691 [DEBUG] [Miner windows/2]Daemon file already exists
2021/12/30 08:52:48.664825 [DEBUG] [Miner windows/2]Daemon file is available and correct
2021/12/30 08:52:48.664825 [DEBUG] [Miner windows/2]Removing unpack directory
2021/12/30 08:52:49.070585 [DEBUG] Nethash: blahblah
2021/12/30 08:52:49.081077 [INFO] Updating pending pool payout...
2021/12/30 08:52:49.367076 [INFO] Updating pending pool payout...
2021/12/30 08:52:49.673231 [DEBUG] [Miner windows/2](Re)creating unpack directory
2021/12/30 08:52:49.698416 [DEBUG] AvailableGPUs called
2021/12/30 08:52:49.699436 [DEBUG] Launching C:\Users\blahblah\Roaming\vertcoin-ocm\miners\unpacked-blahblah\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\blahblah\Roaming\vertcoin-ocm\verthash-miner-tmp.conf]
2021/12/30 08:52:49.799614 [DEBUG] [VerthashMiner] [2021-12-30 08:52:49] INFO  Found 0 OpenCL devices.
2021/12/30 08:52:49.829124 [DEBUG] [VerthashMiner] [2021-12-30 08:52:49] INFO  Found 2 CUDA devices
2021/12/30 08:52:49.829638 [DEBUG] [VerthashMiner] [2021-12-30 08:52:49] INFO  Configuration file: (C:\Users\blahblah\Roaming\vertcoin-ocm\verthash-miner-tmp.conf) has been generated.
2021/12/30 08:52:49.850886 [DEBUG] Launching C:\Users\blahblah\Roaming\vertcoin-ocm\miners\unpacked-blahblah\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--conf C:\Users\blahblah\Roaming\vertcoin-ocm\verthash-miner.conf]
2021/12/30 08:52:49.944790 [DEBUG] [VerthashMiner] [2021-12-30 08:52:49] INFO  Found 0 OpenCL devices.
2021/12/30 08:52:49.972827 [DEBUG] [VerthashMiner] [2021-12-30 08:52:49] INFO  Found 2 CUDA devices
2021/12/30 08:52:49.973341 [DEBUG] [VerthashMiner] [2021-12-30 08:52:49] INFO  Using a configuration file (C:\Users\blahblah\Roaming\vertcoin-ocm\verthash-miner.conf)
2021/12/30 08:52:49.973341 [DEBUG] [VerthashMiner] [2021-12-30 08:52:49] INFO  Loading verthash data file...
2021/12/30 08:52:49.989371 [ERROR] Error in getSetting(testnet): not found
2021/12/30 08:52:50.399009 [DEBUG] [VerthashMiner] [2021-12-30 08:52:50] INFO  Verthash data file has been loaded succesfully!
2021/12/30 08:52:50.399009 [DEBUG] [VerthashMiner] [2021-12-30 08:52:50] WARN  Verthash data file verification stage is disabled!
2021/12/30 08:52:50.399009 [DEBUG] [VerthashMiner] [2021-12-30 08:52:50] INFO  Using protocol: Stratum.
2021/12/30 08:52:50.399522 [DEBUG] [VerthashMiner] [2021-12-30 08:52:50] WARN  Failed to get a "CoinbaseAddress" option inside "Connection" section. Setting to ""
2021/12/30 08:52:50.399522 [DEBUG] [VerthashMiner] [2021-12-30 08:52:50] WARN  Failed to get a "CoinbaseSignature" option inside "Connection" section. Setting to ""
2021/12/30 08:52:50.400036 [DEBUG] [VerthashMiner] [2021-12-30 08:52:50] WARN  Failed to get a "SSLCertificateFileName" option inside "Connection" section. Setting to ""
2021/12/30 08:52:50.400554 [DEBUG] [VerthashMiner] [2021-12-30 08:52:50] WARN  Failed to get a "Proxy" option inside "Connection" section. Setting to ""
2021/12/30 08:52:50.400554 [DEBUG] [VerthashMiner] [2021-12-30 08:52:50] WARN  Failed to get a "Redirect" option inside "Connection" section. Setting to "true"
2021/12/30 08:52:50.401072 [DEBUG] [VerthashMiner] [2021-12-30 08:52:50] WARN  Failed to get a "LongPoll" option inside "Connection" section. Setting to "true"
2021/12/30 08:52:50.401584 [DEBUG] [VerthashMiner] [2021-12-30 08:52:50] WARN  Failed to get a "LongPollTimeout" option inside "Connection" section. Setting to "0"
2021/12/30 08:52:50.401584 [DEBUG] [VerthashMiner] [2021-12-30 08:52:50] WARN  Failed to get a "Scantime" option inside "Connection" section. Setting to "5"
2021/12/30 08:52:50.402094 [DEBUG] [VerthashMiner] [2021-12-30 08:52:50] WARN  Failed to get a "Retries" option inside "Connection" section. Setting to "-1"
2021/12/30 08:52:50.402094 [DEBUG] [VerthashMiner] [2021-12-30 08:52:50] WARN  Failed to get a "RetryPause" option inside "Connection" section. Setting to "5"
2021/12/30 08:52:50.402608 [DEBUG] [VerthashMiner] [2021-12-30 08:52:50] WARN  Failed to get a "ProtocolDump" option inside "Connection" section. Setting to "false"
2021/12/30 08:52:50.403120 [DEBUG] [VerthashMiner] [2021-12-30 08:52:50] INFO  Miner has been successfully configured! (Errors: 0, Warnings: 12)
2021/12/30 08:52:50.403120 [DEBUG] [VerthashMiner] [2021-12-30 08:52:50] INFO  Configured 0(CL) and 2(CUDA) workers
2021/12/30 08:52:50.410818 [DEBUG] [VerthashMiner] [2021-12-30 08:52:50] DEBUG Found 2 NVML devices
2021/12/30 08:52:50.448672 [DEBUG] [VerthashMiner] [2021-12-30 08:52:50] INFO  Starting Stratum on stratum+tcp://verthash.mine.zpool.ca:6144
2021/12/30 08:52:50.448672 [DEBUG] [VerthashMiner] [2021-12-30 08:52:50] INFO  2 miner threads started, using Verthash algorithm.
2021/12/30 08:52:50.719953 [DEBUG] [VerthashMiner] [2021-12-30 08:52:50] INFO  Stratum difficulty set to 0.02
2021/12/30 08:52:51.310759 [ERROR] Error in miner: exit status 3221225477
2021/12/30 08:52:51.877869 [INFO] Miner [VerthashMiner.exe] stopped running.
2021/12/30 08:52:51.877869 [INFO] Restarting miner [VerthashMiner.exe]
2021/12/30 08:52:51.878887 [DEBUG] Launching C:\Users\blahblah\Roaming\vertcoin-ocm\miners\unpacked-blahblah\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--conf C:\Users\blahblah\Roaming\vertcoin-ocm\verthash-miner.conf]
2021/12/30 08:52:51.970437 [DEBUG] [VerthashMiner] [2021-12-30 08:52:51] INFO  Found 0 OpenCL devices.
2021/12/30 08:52:51.996751 [DEBUG] [VerthashMiner] [2021-12-30 08:52:51] INFO  Found 2 CUDA devices
2021/12/30 08:52:51.997260 [DEBUG] [VerthashMiner] [2021-12-30 08:52:51] INFO  Using a configuration file (C:\Users\blahblah\Roaming\vertcoin-ocm\verthash-miner.conf)
2021/12/30 08:52:51.997260 [DEBUG] [VerthashMiner] [2021-12-30 08:52:51] INFO  Loading verthash data file...
2021/12/30 08:52:52.391486 [DEBUG] [VerthashMiner] [2021-12-30 08:52:52] INFO  Verthash data file has been loaded succesfully!
2021/12/30 08:52:52.391486 [DEBUG] [VerthashMiner] [2021-12-30 08:52:52] WARN  Verthash data file verification stage is disabled!
2021/12/30 08:52:52.391486 [DEBUG] [VerthashMiner] [2021-12-30 08:52:52] INFO  Using protocol: Stratum.
2021/12/30 08:52:52.392003 [DEBUG] [VerthashMiner] [2021-12-30 08:52:52] WARN  Failed to get a "CoinbaseAddress" option inside "Connection" section. Setting to ""
2021/12/30 08:52:52.392516 [DEBUG] [VerthashMiner] [2021-12-30 08:52:52] WARN  Failed to get a "CoinbaseSignature" option inside "Connection" section. Setting to ""
2021/12/30 08:52:52.392516 [DEBUG] [VerthashMiner] [2021-12-30 08:52:52] WARN  Failed to get a "SSLCertificateFileName" option inside "Connection" section. Setting to ""
2021/12/30 08:52:52.393032 [DEBUG] [VerthashMiner] [2021-12-30 08:52:52] WARN  Failed to get a "Proxy" option inside "Connection" section. Setting to ""
2021/12/30 08:52:52.393032 [DEBUG] [VerthashMiner] [2021-12-30 08:52:52] WARN  Failed to get a "Redirect" option inside "Connection" section. Setting to "true"
2021/12/30 08:52:52.393543 [DEBUG] [VerthashMiner] [2021-12-30 08:52:52] WARN  Failed to get a "LongPoll" option inside "Connection" section. Setting to "true"
2021/12/30 08:52:52.394057 [DEBUG] [VerthashMiner] [2021-12-30 08:52:52] WARN  Failed to get a "LongPollTimeout" option inside "Connection" section. Setting to "0"
2021/12/30 08:52:52.394057 [DEBUG] [VerthashMiner] [2021-12-30 08:52:52] WARN  Failed to get a "Scantime" option inside "Connection" section. Setting to "5"
2021/12/30 08:52:52.394569 [DEBUG] [VerthashMiner] [2021-12-30 08:52:52] WARN  Failed to get a "Retries" option inside "Connection" section. Setting to "-1"
2021/12/30 08:52:52.394569 [DEBUG] [VerthashMiner] [2021-12-30 08:52:52] WARN  Failed to get a "RetryPause" option inside "Connection" section. Setting to "5"
2021/12/30 08:52:52.395082 [DEBUG] [VerthashMiner] [2021-12-30 08:52:52] WARN  Failed to get a "ProtocolDump" option inside "Connection" section. Setting to "false"
2021/12/30 08:52:52.395082 [DEBUG] [VerthashMiner] [2021-12-30 08:52:52] INFO  Miner has been successfully configured! (Errors: 0, Warnings: 12)
2021/12/30 08:52:52.395593 [DEBUG] [VerthashMiner] [2021-12-30 08:52:52] INFO  Configured 0(CL) and 2(CUDA) workers
2021/12/30 08:52:52.402302 [DEBUG] [VerthashMiner] [2021-12-30 08:52:52] DEBUG Found 2 NVML devices
2021/12/30 08:52:52.437148 [DEBUG] [VerthashMiner] [2021-12-30 08:52:52] INFO  Starting Stratum on stratum+tcp://verthash.mine.zpool.ca:6144
2021/12/30 08:52:52.437148 [DEBUG] [VerthashMiner] [2021-12-30 08:52:52] INFO  2 miner threads started, using Verthash algorithm.
2021/12/30 08:52:52.628409 [DEBUG] [VerthashMiner] [2021-12-30 08:52:52] INFO  Stratum difficulty set to 0.02
2021/12/30 08:52:53.240413 [ERROR] Error in miner: exit status 3221225477
2021/12/30 08:52:53.903067 [INFO] Miner [VerthashMiner.exe] stopped running.
2021/12/30 08:52:53.903067 [INFO] Restarting miner [VerthashMiner.exe]
2021/12/30 08:52:53.903583 [DEBUG] Launching C:\Users\blahblah\Roaming\vertcoin-ocm\miners\unpacked-blahblah\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--conf C:\Users\blahblah\Roaming\vertcoin-ocm\verthash-miner.conf]
2021/12/30 08:52:53.991816 [DEBUG] [VerthashMiner] [2021-12-30 08:52:53] INFO  Found 0 OpenCL devices.
2021/12/30 08:52:54.018330 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] INFO  Found 2 CUDA devices
2021/12/30 08:52:54.018843 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] INFO  Using a configuration file (C:\Users\blahblah\Roaming\vertcoin-ocm\verthash-miner.conf)
2021/12/30 08:52:54.018843 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] INFO  Loading verthash data file...
2021/12/30 08:52:54.400072 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] INFO  Verthash data file has been loaded succesfully!
2021/12/30 08:52:54.400072 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] WARN  Verthash data file verification stage is disabled!
2021/12/30 08:52:54.400072 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] INFO  Using protocol: Stratum.
2021/12/30 08:52:54.400601 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] WARN  Failed to get a "CoinbaseAddress" option inside "Connection" section. Setting to ""
2021/12/30 08:52:54.400601 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] WARN  Failed to get a "CoinbaseSignature" option inside "Connection" section. Setting to ""
2021/12/30 08:52:54.401114 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] WARN  Failed to get a "SSLCertificateFileName" option inside "Connection" section. Setting to ""
2021/12/30 08:52:54.401114 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] WARN  Failed to get a "Proxy" option inside "Connection" section. Setting to ""
2021/12/30 08:52:54.401635 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] WARN  Failed to get a "Redirect" option inside "Connection" section. Setting to "true"
2021/12/30 08:52:54.401635 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] WARN  Failed to get a "LongPoll" option inside "Connection" section. Setting to "true"
2021/12/30 08:52:54.402149 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] WARN  Failed to get a "LongPollTimeout" option inside "Connection" section. Setting to "0"
2021/12/30 08:52:54.402149 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] WARN  Failed to get a "Scantime" option inside "Connection" section. Setting to "5"
2021/12/30 08:52:54.402662 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] WARN  Failed to get a "Retries" option inside "Connection" section. Setting to "-1"
2021/12/30 08:52:54.402662 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] WARN  Failed to get a "RetryPause" option inside "Connection" section. Setting to "5"
2021/12/30 08:52:54.403176 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] WARN  Failed to get a "ProtocolDump" option inside "Connection" section. Setting to "false"
2021/12/30 08:52:54.403176 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] INFO  Miner has been successfully configured! (Errors: 0, Warnings: 12)
2021/12/30 08:52:54.403688 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] INFO  Configured 0(CL) and 2(CUDA) workers
2021/12/30 08:52:54.409883 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] DEBUG Found 2 NVML devices
2021/12/30 08:52:54.443206 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] INFO  Starting Stratum on stratum+tcp://verthash.mine.zpool.ca:6144
2021/12/30 08:52:54.443206 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] INFO  2 miner threads started, using Verthash algorithm.
2021/12/30 08:52:54.613458 [DEBUG] [VerthashMiner] [2021-12-30 08:52:54] INFO  Stratum difficulty set to 0.02
2021/12/30 08:52:55.231151 [ERROR] Error in miner: exit status 3221225477
2021/12/30 08:52:55.918323 [INFO] Miner [VerthashMiner.exe] stopped running.
2021/12/30 08:52:55.918323 [INFO] Restarting miner [VerthashMiner.exe]
2021/12/30 08:52:55.919349 [DEBUG] Launching C:\Users\blahblah\Roaming\vertcoin-ocm\miners\unpacked-blahblah\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--conf C:\Users\blahblah\Roaming\vertcoin-ocm\verthash-miner.conf]
2021/12/30 08:52:56.006797 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] INFO  Found 0 OpenCL devices.
2021/12/30 08:52:56.032687 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] INFO  Found 2 CUDA devices
2021/12/30 08:52:56.033210 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] INFO  Using a configuration file (C:\Users\blahblah\Roaming\vertcoin-ocm\verthash-miner.conf)
2021/12/30 08:52:56.033210 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] INFO  Loading verthash data file...
2021/12/30 08:52:56.412022 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] INFO  Verthash data file has been loaded succesfully!
2021/12/30 08:52:56.412022 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] WARN  Verthash data file verification stage is disabled!
2021/12/30 08:52:56.412022 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] INFO  Using protocol: Stratum.
2021/12/30 08:52:56.412022 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] WARN  Failed to get a "CoinbaseAddress" option inside "Connection" section. Setting to ""
2021/12/30 08:52:56.412922 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] WARN  Failed to get a "CoinbaseSignature" option inside "Connection" section. Setting to ""
2021/12/30 08:52:56.413435 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] WARN  Failed to get a "SSLCertificateFileName" option inside "Connection" section. Setting to ""
2021/12/30 08:52:56.413435 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] WARN  Failed to get a "Proxy" option inside "Connection" section. Setting to ""
2021/12/30 08:52:56.413946 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] WARN  Failed to get a "Redirect" option inside "Connection" section. Setting to "true"
2021/12/30 08:52:56.413946 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] WARN  Failed to get a "LongPoll" option inside "Connection" section. Setting to "true"
2021/12/30 08:52:56.414459 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] WARN  Failed to get a "LongPollTimeout" option inside "Connection" section. Setting to "0"
2021/12/30 08:52:56.414459 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] WARN  Failed to get a "Scantime" option inside "Connection" section. Setting to "5"
2021/12/30 08:52:56.414971 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] WARN  Failed to get a "Retries" option inside "Connection" section. Setting to "-1"
2021/12/30 08:52:56.414971 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] WARN  Failed to get a "RetryPause" option inside "Connection" section. Setting to "5"
2021/12/30 08:52:56.415483 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] WARN  Failed to get a "ProtocolDump" option inside "Connection" section. Setting to "false"
2021/12/30 08:52:56.415483 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] INFO  Miner has been successfully configured! (Errors: 0, Warnings: 12)
2021/12/30 08:52:56.415483 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] INFO  Configured 0(CL) and 2(CUDA) workers
2021/12/30 08:52:56.422148 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] DEBUG Found 2 NVML devices
2021/12/30 08:52:56.457905 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] INFO  Starting Stratum on stratum+tcp://verthash.mine.zpool.ca:6144
2021/12/30 08:52:56.457905 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] INFO  2 miner threads started, using Verthash algorithm.
2021/12/30 08:52:56.690890 [DEBUG] [VerthashMiner] [2021-12-30 08:52:56] INFO  Stratum difficulty set to 0.02
2021/12/30 08:52:57.260520 [ERROR] Error in miner: exit status 3221225477
2021/12/30 08:52:57.936185 [INFO] Miner [VerthashMiner.exe] stopped running.
2021/12/30 08:52:57.936185 [INFO] Miner [VerthashMiner.exe] is rapidly failing, not restarting it.
2021/12/30 08:52:57.936185 [INFO] Stopped monitoring thread
2021/12/30 08:52:57.936185 [INFO] Stopping mining process...
2021/12/30 08:52:58.682872 [ERROR] Error in getSetting(testnet): not found
2021/12/30 08:53:03.221262 [INFO] Stopping mining process...

![2021-12-30 08_48_49-vertcoin-ocm](https://user-images.githubusercontent.com/69687422/147757699-f5eeef15-bf00-4c69-83ab-c982c5c5e7d6.png)

**Comment by KforG** [comment]
If the error started to occur after the driver update, you should try and revert back to see if that fixes it.

The error usually occurs when the user has an incompatible GPU or extremely old drivers. You don't seem to fall into any of those categories though.

**Comment by kaboddy** [comment]
Thanks for the reply!
It randomly started working an hour or so later, then it just stayed working.  I didn't change anything...  Might have been the pool I was in?

**Comment by KforG** [comment]
Could be, most likely not although a couple of months ago both Zpool and Zergpool had many people coming in with that error, then it just stopped.

Idk, it's working now at least.
