### ISSUE TITLE
Vertcoin Checks Failure

### ISSUE THREAD

**Issue by mihai-travel** [vertcoin-project/one-click-miner-vnext#466]
Hi there,

I have an issue with my one-click Vertcoin Miner : each and every time I try to start mining, it tells me the "Miner Software reported no compatible GPUs". I tried to look it up and to find solutions but the ones I applied do not appear to have helped. I try to mine on Windows 10 using a computer having a NVIDEA Geforce GTX 1080 (I saw I was OK for mining). What can I do ?

Thank you in advance

**Comment by KforG** [comment]
Generally this error occurs when the miner located in `%appdata%\vertcoin-ocm` is being blocked by antivirus. You may need to create an exception for that.
