### ISSUE TITLE
Miner won't working - "Checks failed: Failure to configure VerthashMiner: exit status 1"

### ISSUE THREAD

**Issue by oti4500** [vertcoin-project/one-click-miner-vnext#470]
Miner won't working - "Checks failed: Failure to configure VerthashMiner: exit status 1"

"Checks failed: Failure to configure VerthashMiner: exit status 1"

Just open the software via terminal (sudo)

Source: Github

Mesa Intel® UHD Graphics 630 (CFL GT2) (currently choosed)
Have, but not used Geforce 1660ti

Ubuntu (Pop!_OS) 20.04 LTS

1st:

2022/01/17 18:01:22 [ERROR] Error writing tracking state: open /root/.vertcoin-ocm/tracking: no such file or directory
2022/01/17 18:01:22 [INFO] Creating data directory

2022/01/17 18:01:22.030164 OCM v2.1-beta4-000fc4e Started up
2022/01/17 18:01:22.031242 [ERROR] Error in getSetting(testnet): not found
2022/01/17 18:01:22.031276 [ERROR] Error in getSetting(testnet): not found
2022/01/17 18:01:22.031836 [ERROR] Unable to fetch node information
%!(EXTRA string=Get "http://127.0.0.1:9171/local_stats": dial tcp 127.0.0.1:9171: connect: connection refused)
2022/01/17 18:01:22.031882 [INFO] No local node detected, selecting other public nodes
2022/01/17 18:01:23.410676 [INFO] p2proxy.vertcoin.org: 57.582969ms 
2022/01/17 18:01:24.769111 [INFO] mindcraftblocks.com: 179.554501ms 
2022/01/17 18:01:26.322201 [INFO] vtc-fl.javerity.com: 374.354575ms 
2022/01/17 18:01:27.724861 [INFO] vtc-ca.javerity.com: 352.474909ms 
2022/01/17 18:01:29.065398 [INFO] vtc.p2pminers.nl: 71.735297ms 
2022/01/17 18:01:30.673021 [INFO] p2p-usa.xyz: 189.339116ms 
2022/01/17 18:01:32.038627 [INFO] p2p-ekb.xyz: 153.267888ms 
2022/01/17 18:01:33.654082 [INFO] asia.p2p-spb.xyz: 450.561347ms 
2022/01/17 18:01:34.931877 [INFO] p2p-spb.xyz: 84.819039ms 
2022/01/17 18:01:36.450044 [INFO] p2p-south.xyz: 202.567952ms 
2022/01/17 18:01:37.853804 [INFO] siberia.mine.nu: 90.656242ms 
2022/01/17 18:01:40.023101 [INFO] boofpool.ddns.net: 0s 
2022/01/17 18:01:41.486324 [INFO] vtc-brn.webhop.me: 228.963361ms 
2022/01/17 18:01:42.213994 [INFO] boofpool.ddns.net selected, fulfilled all requirements
2022/01/17 18:01:42.214622 [ERROR] Error in getSetting(pool): not found
2022/01/17 18:01:42.214817 [ERROR] Error in getSetting(testnet): not found
2022/01/17 18:01:42.215167 [INFO] Error reading keyfile: open /root/.vertcoin-ocm/keyfile.hex: no such file or directory
2022/01/17 18:01:42.215897 [ERROR] Error in getSetting(testnet): not found
2022/01/17 18:01:42.216218 [INFO] Error reading keyfile: open /root/.vertcoin-ocm/keyfile.hex: no such file or directory
2022/01/17 18:01:42.216421 [ERROR] Error in getSetting(testnet): not found
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
Control
2022/01/17 18:01:42.749048 [INFO] User IETF is en-US
2022/01/17 18:01:42.749128 [INFO] Matched tag is en-u-rg-uszzzz
2022/01/17 18:01:42.749150 [INFO] Returning locale en
2022/01/17 18:01:42.783929 [ERROR] Error in getSetting(testnet): not found
2022/01/17 18:01:42.809559 [INFO] Checking wallet..
2022/01/17 18:01:42.809616 [INFO] Error reading keyfile: open /root/.vertcoin-ocm/keyfile.hex: no such file or directory
2022/01/17 18:01:42.809661 [INFO] Error reading keyfile: open /root/.vertcoin-ocm/keyfile.hex: no such file or directory
2022/01/17 18:01:42.809695 [INFO] Error reading keyfile: open /root/.vertcoin-ocm/keyfile.hex: no such file or directory
2022/01/17 18:01:42.809729 [INFO] Initializing wallet VrSwsBBq6TgsAyy8YQdes4we49o6KyiqFU
2022/01/17 18:01:42.810429 [INFO] Wallet initialized: 0
2022/01/17 18:01:47.787119 [INFO] Error reading keyfile: open /root/.vertcoin-ocm/keyfile.hex: no such file or directory
2022/01/17 18:01:52.794656 [INFO] Error reading keyfile: open /root/.vertcoin-ocm/keyfile.hex: no such file or directory
2022/01/17 18:01:54.237047 [INFO] Checking wallet..
2022/01/17 18:01:54.237149 [INFO] Initializing wallet VqXCbGVTkym3oq1kAjLN42qDuzez1zRvwV
2022/01/17 18:01:54.237217 [INFO] Wallet initialized: 1
2022/01/17 18:01:54.237251 [ERROR] Error in getSetting(testnet): not found
2022/01/17 18:01:54.445669 [DEBUG] GPU [Intel Corporation UHD Graphics 630 (Mobile)] matched regex [.*Intel.*]
2022/01/17 18:01:54.582896 [ERROR] Error in getSetting(testnet): not found
2022/01/17 18:01:54.582930 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2022/01/17 18:01:54.582975 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2022/01/17 18:01:54.583000 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2022/01/17 18:01:54.583016 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2022/01/17 18:01:54.583039 [DEBUG] Found compatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2022/01/17 18:01:54.583084 [ERROR] Error in getSetting(debugging): not found
2022/01/17 18:01:54.583101 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2022/01/17 18:01:54.583123 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2022/01/17 18:01:54.583146 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2022/01/17 18:01:54.583191 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2022/01/17 18:01:54.583214 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2022/01/17 18:01:54.583237 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2022/01/17 18:01:54.583259 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2022/01/17 18:01:54.583331 [DEBUG] [Miner linux/3]Binary not found, downloading...
2022/01/17 18:01:56.737227 [DEBUG] [Miner linux/3]Daemon file downloaded
2022/01/17 18:01:56.749080 [DEBUG] [Miner linux/3]Daemon file is available and correct
2022/01/17 18:01:56.749128 [DEBUG] [Miner linux/3](Re)creating unpack directory
2022/01/17 18:10:16.001810 [ERROR] Error in getSetting(enableIntegrated): not found
2022/01/17 18:10:16.003908 [DEBUG] Launching /root/.vertcoin-ocm/miners/unpacked-a7c3e6b0a7a937eb9e9d88de24a16a7b13f518d858fffd07694a21bc724d9a8c/VerthashMiner-0.7.2-CUDA11-linux/VerthashMiner [--gen-conf /root/.vertcoin-ocm/verthash-miner-tmpl.conf]
2022/01/17 18:10:16.654090 [ERROR] Error in getSetting(testnet): not found
2022/01/17 18:10:43.362771 [ERROR] Error in getSetting(debugging): not found
2022/01/17 18:10:43.364159 [ERROR] Error in getSetting(testnet): not found
2022/01/17 18:10:43.365507 [ERROR] Error in getSetting(testnet): not found
2022/01/17 18:10:43.798598 [ERROR] Error in getSetting(enableIntegrated): not found
2022/01/17 18:10:52.466914 [INFO] Stopping mining process...
2022/01/17 18:10:52.467070 [ERROR] Error stopping miner: VerthashMiner os: process already finished
2022/01/17 18:10:53.929537 [ERROR] Error in getSetting(testnet): not found
2022/01/17 18:10:53.929665 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2022/01/17 18:10:53.929712 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2022/01/17 18:10:53.929760 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2022/01/17 18:10:53.929794 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2022/01/17 18:10:53.929850 [DEBUG] Found compatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2022/01/17 18:10:53.929907 [ERROR] Error in getSetting(debugging): not found
2022/01/17 18:10:53.929954 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2022/01/17 18:10:53.930002 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2022/01/17 18:10:53.930049 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2022/01/17 18:10:53.930083 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2022/01/17 18:10:53.930117 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2022/01/17 18:10:53.930151 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2022/01/17 18:10:53.930198 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2022/01/17 18:10:53.930280 [DEBUG] [Miner linux/3]Daemon file already exists
2022/01/17 18:10:53.973810 [DEBUG] [Miner linux/3]Daemon file is available and correct
2022/01/17 18:10:53.973869 [DEBUG] [Miner linux/3]Removing unpack directory
2022/01/17 18:10:54.975729 [DEBUG] [Miner linux/3](Re)creating unpack directory
2022/01/17 18:11:01.377555 [ERROR] Error in getSetting(enableIntegrated): not found
2022/01/17 18:11:01.378535 [DEBUG] Launching /root/.vertcoin-ocm/miners/unpacked-a7c3e6b0a7a937eb9e9d88de24a16a7b13f518d858fffd07694a21bc724d9a8c/VerthashMiner-0.7.2-CUDA11-linux/VerthashMiner [--gen-conf /root/.vertcoin-ocm/verthash-miner-tmpl.conf]
2022/01/17 18:11:02.066367 [ERROR] Error in getSetting(testnet): not found
2022/01/17 18:11:18.709597 [ERROR] Error in getSetting(debugging): not found
2022/01/17 18:11:18.711869 [ERROR] Error in getSetting(testnet): not found
2022/01/17 18:11:18.714145 [ERROR] Error in getSetting(testnet): not found
2022/01/17 18:11:22.380931 [ERROR] Error in getSetting(enableIntegrated): not found
2022/01/17 18:11:25.709421 [INFO] Stopping mining process...
2022/01/17 18:11:25.709491 [ERROR] Error stopping miner: VerthashMiner os: process already finished

2nd

2022/01/17 18:11:32.869671 OCM v2.1-beta4-000fc4e Started up
2022/01/17 18:11:32.870265 [ERROR] Error in getSetting(testnet): not found
2022/01/17 18:11:32.870322 [ERROR] Error in getSetting(testnet): not found
2022/01/17 18:11:32.870935 [ERROR] Unable to fetch node information
%!(EXTRA string=Get "http://127.0.0.1:9171/local_stats": dial tcp 127.0.0.1:9171: connect: connection refused)
2022/01/17 18:11:32.870982 [INFO] No local node detected, selecting other public nodes
2022/01/17 18:11:34.406672 [INFO] p2proxy.vertcoin.org: 65.872444ms 
2022/01/17 18:11:35.897821 [INFO] mindcraftblocks.com: 328.977193ms 
2022/01/17 18:11:37.239142 [INFO] vtc-fl.javerity.com: 179.270542ms 
2022/01/17 18:11:38.997878 [INFO] vtc-ca.javerity.com: 481.883405ms 
2022/01/17 18:11:40.239397 [INFO] vtc.p2pminers.nl: 80.262563ms 
2022/01/17 18:11:42.334935 [INFO] p2p-usa.xyz: 147.393723ms 
2022/01/17 18:11:43.602905 [INFO] p2p-ekb.xyz: 110.647959ms 
2022/01/17 18:11:45.130606 [INFO] asia.p2p-spb.xyz: 464.577707ms 
2022/01/17 18:11:46.413729 [INFO] p2p-spb.xyz: 105.909037ms 
2022/01/17 18:11:47.785980 [INFO] p2p-south.xyz: 165.101965ms 
2022/01/17 18:11:49.063751 [INFO] siberia.mine.nu: 96.790904ms 
2022/01/17 18:11:51.137814 [INFO] boofpool.ddns.net: 0s 
2022/01/17 18:11:52.487437 [INFO] vtc-brn.webhop.me: 219.500721ms 
2022/01/17 18:11:57.947487 [INFO] boofpool.ddns.net selected, fulfilled all requirements
2022/01/17 18:11:57.947715 [ERROR] Error in getSetting(testnet): not found
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
Control
2022/01/17 18:11:58.407659 [INFO] User IETF is en-US
2022/01/17 18:11:58.407738 [INFO] Matched tag is en-u-rg-uszzzz
2022/01/17 18:11:58.407761 [INFO] Returning locale en
2022/01/17 18:11:58.428792 [ERROR] Error in getSetting(testnet): not found
2022/01/17 18:11:58.451149 [INFO] Checking wallet..
2022/01/17 18:11:58.451295 [INFO] Initializing wallet VqXCbGVTkym3oq1kAjLN42qDuzez1zRvwV
2022/01/17 18:11:58.451374 [INFO] Wallet initialized: 1
2022/01/17 18:11:58.669668 [DEBUG] GPU [Intel Corporation UHD Graphics 630 (Mobile)] matched regex [.*Intel.*]
2022/01/17 18:11:58.714836 [ERROR] Error in getSetting(testnet): not found
2022/01/17 18:11:58.714896 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2022/01/17 18:11:58.714919 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2022/01/17 18:11:58.714964 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2022/01/17 18:11:58.714987 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2022/01/17 18:11:58.715010 [DEBUG] Found compatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2022/01/17 18:11:58.715032 [ERROR] Error in getSetting(debugging): not found
2022/01/17 18:11:58.715078 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2022/01/17 18:11:58.715100 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2022/01/17 18:11:58.715123 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2022/01/17 18:11:58.715146 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2022/01/17 18:11:58.715191 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2022/01/17 18:11:58.715214 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2022/01/17 18:11:58.715248 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2022/01/17 18:11:58.715304 [DEBUG] [Miner linux/3]Daemon file already exists
2022/01/17 18:11:58.730348 [DEBUG] [Miner linux/3]Daemon file is available and correct
2022/01/17 18:11:58.730393 [DEBUG] [Miner linux/3]Removing unpack directory
2022/01/17 18:11:59.734773 [DEBUG] [Miner linux/3](Re)creating unpack directory
2022/01/17 18:12:03.450955 [ERROR] Error in getSetting(enableIntegrated): not found
2022/01/17 18:12:03.451175 [DEBUG] Launching /root/.vertcoin-ocm/miners/unpacked-a7c3e6b0a7a937eb9e9d88de24a16a7b13f518d858fffd07694a21bc724d9a8c/VerthashMiner-0.7.2-CUDA11-linux/VerthashMiner [--gen-conf /root/.vertcoin-ocm/verthash-miner-tmpl.conf]
2022/01/17 18:12:04.131093 [ERROR] Error in getSetting(testnet): not found
2022/01/17 18:12:06.497456 [ERROR] Error in getSetting(testnet): not found
2022/01/17 18:12:06.497501 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2022/01/17 18:12:06.497523 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2022/01/17 18:12:06.497546 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2022/01/17 18:12:06.497591 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2022/01/17 18:12:06.497614 [DEBUG] Found compatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2022/01/17 18:12:06.497637 [ERROR] Error in getSetting(debugging): not found
2022/01/17 18:12:06.497659 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2022/01/17 18:12:06.497705 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2022/01/17 18:12:06.497728 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2022/01/17 18:12:06.497750 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2022/01/17 18:12:06.497773 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2022/01/17 18:12:06.497818 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2022/01/17 18:12:06.497841 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2022/01/17 18:12:06.497875 [DEBUG] [Miner linux/3]Daemon file already exists
2022/01/17 18:12:06.516616 [DEBUG] [Miner linux/3]Daemon file is available and correct
2022/01/17 18:12:06.516663 [DEBUG] [Miner linux/3]Removing unpack directory
2022/01/17 18:12:07.518845 [DEBUG] [Miner linux/3](Re)creating unpack directory
2022/01/17 18:12:14.315332 [ERROR] Error in getSetting(enableIntegrated): not found
2022/01/17 18:12:14.315519 [DEBUG] Launching /root/.vertcoin-ocm/miners/unpacked-a7c3e6b0a7a937eb9e9d88de24a16a7b13f518d858fffd07694a21bc724d9a8c/VerthashMiner-0.7.2-CUDA11-linux/VerthashMiner [--gen-conf /root/.vertcoin-ocm/verthash-miner-tmpl.conf]

sudo $HOME/.vertcoin-ocm on Linux

-->

**Comment by KforG** [comment]
Seems like the OCM doesn't detect your dedicated GPU, do you have the appropriate drivers installed for it?

It does detect your integrated GPU, and will likely be able to start if you tick the box in settings for mining with the IGPU.
