### ISSUE TITLE
Performance reduced with Beta 4

### ISSUE THREAD

**Issue by ggbce** [vertcoin-project/one-click-miner-vnext#471]
I was using OCM Beta 3 since many months and I was able to produce almost the same mining day after days. Since few weeks a Beta 4 version is available, I installed it on my computer but the mining is really more hard. The kH/s still identical, but the predictive benifit on 24 hours had dropped by 50% !!!

Why a newer OCM version cannot give the same result or better ? For the moment, I still using the old Beta 3 that give me a better result.

Just run Beta 3 and Beta 4 to compare

v2.1-beta3 for Windows (compiled by VertCoin) or v2.1-beta4 for Windows (compiled by VertCoin)

Windows 10 (21H1), Intel Core i5 Gen 8th

**Comment by KforG** [comment]
> Updated earnings calculation to account for halving (thanks @vertiond )

That is from the release notes of Beta 4. You aren't making more per day using the older version, the newer version has simply updated the function that calculates the earnings. You will be making the exact same VTC per day no matter what version you're using.
