### ISSUE TITLE
Checks failed: Could not find compatible miner binaries

### ISSUE THREAD

**Issue by JamesKing2022** [vertcoin-project/one-click-miner-vnext#474]

**Comment by JamesKing2022** [comment]
Does anyone know how I can fix this problem. Thanks

**Comment by KforG** [comment]
If your GPU is compatible then it's usually because the antivirus is removing them from `%appdata%\vertcoin-ocm`

**Comment by Sachrian88** [comment]
3N1P2rDthVX2wPPSQ5nUutkqSPqtShcL8m
