### ISSUE TITLE
Immediate stop after starting

### ISSUE THREAD

**Issue by ZZZzziiiiiiiizzZZZ** [vertcoin-project/one-click-miner-vnext#480]
"Checks failed:

One or more of your miner binaries are showing rapid failures (immediately stop after starting). Please enable deugging...
"

OCM has been working on my PC for months. Then one day, this error and nothing has been able to get it back up and working again. 

Immediate crash seconds after mining in progress screen appears

Was using an older version when crashing began. Downloaded latest to see if this would resolve issue, but does not. Now running "OCM v2.1-beta4-000fc4e"

Windows 10 PC

"
Found compatible binary
Found incompatible binary

...
[Miner windows/1]Daemon file already exists
...
INFO  Found 1 OpenCL devices.
WARN  Failed to initialize CUDA. error code: 35
WARN  CUDA devices will be unavailable.
...
Error in miner: exit status 1
Miner [VerthashMiner.exe] stopped running.
Miner [VerthashMiner.exe] is rapidly failing, not restarting it.
"

**Comment by KforG** [comment]
There isn't that much information to go by here but I'll throw out some common reasons for that error.
1. Did you recently update GPU drivers or windows?
2. I assume you have a AMD GPU, if you don't something is wrong with your Nvidia driver.
3. Is your GPU overclocked/underclocked? If it is, try running it without.
4. In very rare cases antivirus will interfere with the miner, you may have to create/remake exceptions for `%appdata%\vertcoin-ocm`

**Comment by ZZZzziiiiiiiizzZZZ** [comment]
figured it out... my VPN was causing the problem, had to add the OCM executable to the Split-Tunneling option and now it works again... ty
