### ISSUE TITLE
New OCM 2.0 - Shutoff Unexpectedly

### ISSUE THREAD

**Issue by MaxZero101** [vertcoin-project/one-click-miner-vnext#485]
R OCM shutoff unexpectedly.
 For the OCM to continue operating.

 Went to a red coded phrase, some file was missing, seems to appear in my attached log file. Was not able to screenshot or take better notes at the time.

I have no idea, it just shutoff unexpectedly, never saw this before with all previous OCM versions.

The most current, 2.0 stable version from around March 4, 2022.

Windows 10, Radeon RX 570 Series

N/A (Windows 10)

None that I am aware of.

[debug.log](https://github.com/vertcoin-project/one-click-miner-vnext/files/8202551/debug.log)

**Comment by KforG** [comment]
So this was a one time thing? It's working as expected now?
It seems to be a random crash, which can be introduced for a variety of reasons. A bit like whenever a browser freezes up etc.

Also you should really just be running the latest beta, see patch notes, it will overall provide a better experience, and it's as stable as the newest final release.

**Comment by MaxZero101** [comment]
It seems to have happened that one time. I'm was and am still using the latest version that had come out. I believe it is the beta. Sometimes the GitHub versions get confusing, at least to me anyway.

**Comment by MaxZero101** [comment]
![image](https://user-images.githubusercontent.com/74627989/158645841-c6867fa4-379b-4113-b26f-f648b700d438.png)

The error came up again and I was able to screenshot this pic of it.

**Comment by KforG** [comment]
That message is typical when the antivirus is trying to remove the miner. 
You may need to create/recreate an antivirus exclusion for `%appdata%\vertcoin-ocm`

>  I'm was and am still using the latest version that had come out.
You aren't in that picture. You can just click the `Update available` button to download the newest version.

**Comment by MaxZero101** [comment]
I didn't think it necessary to have my face in the pic. 😂
