### ISSUE TITLE
Upon launching OCM, following error message posts "Checks failed: could not find compatible miner binaries". 

### ISSUE THREAD

**Issue by VioletBlue007** [vertcoin-project/one-click-miner-vnext#489]

**Comment by VioletBlue007** [comment]
OCM launches with an error message "checks failed: could not find compatible miner binaries"
What is this error? How do I fix this?

Initial conditions:

Vertcoin Core running
nVidia Geforce RTX 3070 (8GB) - supposed to be compatible
Windows 10
All drives up to date, including GPU

Thanks
V

**Comment by KforG** [comment]
This is almost always due to antiviruses removing the miner from `%appdata%\vertcoin-ocm\miners\`
