### ISSUE TITLE
Spanish Translation for Vertcoin OCM

### ISSUE THREAD

**Issue by GYULevande** [vertcoin-project/one-click-miner-vnext#496]
"verthash" : "Verificando / creando el archivo de data Verthash..."
"pending_payout_info_unavailable" : "Por favor espera por la información de pago pendiente",
"active_pool" : "Piscina activa",
"pool_fee" : "comisión",
"copy_address" : "Copia la dirección de tu billetera",
"payout_information" : "Ver información de pagos"
"sign_failed" : "Incapaz de firmar transacción. Revisa tu contraseña.",

"enable_integrated" : "Minar en gráficos integrados",
"enable_integrated_sub" : "El minado usará gráficos integrados si es posible",
"testnet":"Modo de red de prueba",
"testnet_sub":"Activa el modo de red de prueba. No minarás monedas reales.",
"pool": "Piscina de minado"

**Comment by vertiond** [comment]
Please make a pull request.
