### ISSUE TITLE
Hello, One Click Miner is not recognizing my mining Gpu, Only my display Gpu. Any ideas as to what might be the problem? Thankyou

### ISSUE THREAD

**Issue by Lukus101** [vertcoin-project/one-click-miner-vnext#503]

**Comment by KforG** [comment]
What GPUs do you have?
Which one does OCM recognize?

**Comment by Lukus101** [comment]
Hello,

I have 1 Nvidia Pny cmp 70hx minIng GPU.
OCM requires Nvidia GPU to have compute power 3.0 or higher.
Kind Regards
Luke

**Comment by KforG** [comment]
Does it start mining with the other GPU, or does it display some kind of error message?

**Comment by KforG** [comment]
It should definitely not be 70 MH/s. That is for another algorithm, Ethash probably. The RTX 3090, probably the fastest GPU currently on the market gets around 2 MH/s when overclocked properly.

If you get 1.5 MH/s it's most like mining with all available GPUs. If you want to check what GPUs are recognized and being utilized, turn on miner output in OCM's settings, let it run for a bit, and then take a look at the debug.log file located at `%appdata%\vertcoin-ocm\debug.log`.

**Comment by KforG** [comment]
No worries, you too.
