### ISSUE TITLE
one click miner failure

### ISSUE THREAD

**Issue by shineandre** [vertcoin-project/one-click-miner-vnext#510]
no failure

failed to execute @99

same results evrytime i try

tried the latest and the previous version same error

windows 10

failure to configure status 3221225785

**Comment by KforG** [comment]
Is your GPU compatible?

If it is compatible it sounds like your antivirus is detecting the miner as a virus. You may need to exclude `%appdata%\vertcoin-ocm` from your antivirus for the miner to function.
