### ISSUE TITLE
"Miner software reported no compatible GPUs" when it was working fine hours earlier on the same PC

### ISSUE THREAD

**Issue by MaxZero101** [vertcoin-project/one-click-miner-vnext#511]
Received error: "Miner software reported no compatible GPUs" I know this is not true as I had just been mining with it several hours before this happened on the newly downloaded miner.

 For the miner to work 

![image](https://user-images.githubusercontent.com/74627989/174235173-40e4ce90-7167-48d3-ad8a-3f089790e978.png)

 I just need to start the OCM.

 
![image](https://user-images.githubusercontent.com/74627989/174235299-490fb2ff-4519-4a44-96a4-80eb19fa8abe.png)

 Windows 10 /  Radeon RX 570 series

2022/06/16 20:37:10.553755 OCM v2.0-218788a Started up
2022/06/16 20:37:10.553755 OCM v2.0-218788a Started up
2022/06/16 20:37:10.555756 [INFO] Error reading keyfile: open C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2022/06/16 20:37:10.555756 [INFO] Error reading keyfile: open C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2022/06/16 20:37:10.555756 [INFO] Error reading keyfile: open C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2022/06/16 20:37:10.555756 [INFO] Error reading keyfile: open C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2022/06/17 00:43:24.427744 OCM v2.1-beta4-000fc4e Started up
2022/06/17 00:43:24.433831 [ERROR] Error in getSetting(testnet): not found
2022/06/17 00:43:24.433831 [ERROR] Error in getSetting(testnet): not found
2022/06/17 00:43:26.490036 [ERROR] Unable to fetch node information
%!(EXTRA string=Get "http://127.0.0.1:9171/local_stats": dial tcp 127.0.0.1:9171: connectex: No connection could be made because the target machine actively refused it.)
2022/06/17 00:43:26.490036 [INFO] No local node detected, selecting other public nodes
2022/06/17 00:43:28.250927 [INFO] p2proxy.vertcoin.org: 117.40435ms 
2022/06/17 00:43:29.517168 [INFO] mindcraftblocks.com: 50.9877ms 
2022/06/17 00:43:30.809901 [INFO] vtc-fl.javerity.com: 67.0264ms 
2022/06/17 00:43:32.080164 [INFO] vtc-ca.javerity.com: 70.59865ms 
2022/06/17 00:43:32.152185 [WARN]Error: Check if you are connected to the internet
2022/06/17 00:43:32.152185 [WARN]lookup vtc.p2pminers.nl: no such host
2022/06/17 00:43:32.152185 [WARN] Nodes could not be pinged, selecting random node
2022/06/17 00:43:32.152185 [INFO] vtc.p2pminers.nl has been randomly selected
2022/06/17 00:43:32.152185 [INFO] Error reading keyfile: open C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2022/06/17 00:43:32.152185 [ERROR] Error in getSetting(testnet): not found
2022/06/17 00:44:19.091654 OCM v2.1-beta4-000fc4e Started up
2022/06/17 00:44:19.093654 [ERROR] Error in getSetting(testnet): not found
2022/06/17 00:44:19.093654 [ERROR] Error in getSetting(testnet): not found
2022/06/17 00:44:21.142717 [ERROR] Unable to fetch node information
%!(EXTRA string=Get "http://127.0.0.1:9171/local_stats": dial tcp 127.0.0.1:9171: connectex: No connection could be made because the target machine actively refused it.)
2022/06/17 00:44:21.142717 [INFO] No local node detected, selecting other public nodes
2022/06/17 00:44:22.597932 [INFO] p2proxy.vertcoin.org: 116.5945ms 
2022/06/17 00:44:23.749817 [INFO] mindcraftblocks.com: 37.91965ms 
2022/06/17 00:44:24.954359 [INFO] vtc-fl.javerity.com: 77.0072ms 
2022/06/17 00:44:26.135006 [INFO] vtc-ca.javerity.com: 70.41695ms 
2022/06/17 00:44:26.188167 [WARN]Error: Check if you are connected to the internet
2022/06/17 00:44:26.188167 [WARN]lookup vtc.p2pminers.nl: no such host
2022/06/17 00:44:26.188167 [WARN] Nodes could not be pinged, selecting random node
2022/06/17 00:44:26.188167 [INFO] vtc-ca.javerity.com has been randomly selected
2022/06/17 00:44:26.188167 [INFO] Error reading keyfile: open C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2022/06/17 00:44:26.188167 [ERROR] Error in getSetting(testnet): not found
2022/06/17 00:44:26.431861 [INFO] User IETF is en-US
2022/06/17 00:44:26.431861 [INFO] Matched tag is en-u-rg-uszzzz
2022/06/17 00:44:26.431861 [INFO] Returning locale en
2022/06/17 00:44:26.487509 [ERROR] Error in getSetting(testnet): not found
2022/06/17 00:44:26.541522 [INFO] Checking wallet..
2022/06/17 00:44:26.542034 [INFO] Error reading keyfile: open C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2022/06/17 00:44:26.542034 [INFO] Error reading keyfile: open C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2022/06/17 00:44:26.542034 [INFO] Error reading keyfile: open C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2022/06/17 00:44:26.542034 [INFO] Initializing wallet VrSwsBBq6TgsAyy8YQdes4we49o6KyiqFU
2022/06/17 00:44:26.542546 [INFO] Wallet initialized: 0
2022/06/17 00:44:31.501494 [INFO] Error reading keyfile: open C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2022/06/17 00:44:36.501117 [INFO] Error reading keyfile: open C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2022/06/17 00:44:41.506924 [INFO] Error reading keyfile: open C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2022/06/17 00:44:46.510186 [INFO] Error reading keyfile: open C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2022/06/17 00:44:51.520432 [INFO] Error reading keyfile: open C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2022/06/17 00:44:56.530970 [INFO] Error reading keyfile: open C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2022/06/17 00:45:01.541735 [INFO] Error reading keyfile: open C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2022/06/17 00:45:06.457402 [INFO] Checking wallet..
2022/06/17 00:45:06.461506 [INFO] Initializing wallet Vshm89qhRL2rhUz4a6ofAz8Ub3NbUhjmSm
2022/06/17 00:45:06.462018 [INFO] Wallet initialized: 1
2022/06/17 00:45:06.462018 [ERROR] Error in getSetting(testnet): not found
2022/06/17 00:45:06.758871 [DEBUG] GPU [Radeon RX 570 Series] matched regex [.*Radeon.*]
2022/06/17 00:45:06.973799 [ERROR] Error in getSetting(testnet): not found
2022/06/17 00:45:06.973799 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2022/06/17 00:45:06.973799 [ERROR] Error in getSetting(debugging): not found
2022/06/17 00:45:06.973799 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2022/06/17 00:45:06.973799 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2022/06/17 00:45:06.973799 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2022/06/17 00:45:06.973799 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2022/06/17 00:45:06.973799 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2022/06/17 00:45:06.973799 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2022/06/17 00:45:06.973799 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2022/06/17 00:45:06.973799 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2022/06/17 00:45:06.973799 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2022/06/17 00:45:06.973799 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2022/06/17 00:45:06.973799 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2022/06/17 00:45:06.974313 [DEBUG] [Miner windows/1]Binary not found, downloading...
2022/06/17 00:45:08.893718 [DEBUG] [Miner windows/1]Daemon file downloaded
2022/06/17 00:45:08.904525 [DEBUG] [Miner windows/1]Daemon file is available and correct
2022/06/17 00:45:08.904525 [DEBUG] [Miner windows/1](Re)creating unpack directory
2022/06/17 00:58:03.479996 [ERROR] Error in getSetting(enableIntegrated): not found
2022/06/17 00:58:03.481528 [DEBUG] Launching C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\miners\unpacked-e5af5ab19154f6ee57db22645a43200336e8017865c71505ae669af19243449e\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\verthash-miner-tmpl.conf]
2022/06/17 00:58:04.609220 [DEBUG]Entering device block
2022/06/17 00:58:04.609737 [DEBUG]Exiting device block
2022/06/17 00:58:04.609737 [DEBUG]{0  false  }
2022/06/17 00:58:04.609737 [DEBUG]Entering device block
2022/06/17 00:58:04.609737 [DEBUG]Exiting device block
2022/06/17 00:58:04.609737 [DEBUG]{0  false  }
2022/06/17 00:58:04.609737 [DEBUG] AvailableGPUs called
2022/06/17 00:58:04.610769 [DEBUG] Launching C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\miners\unpacked-e5af5ab19154f6ee57db22645a43200336e8017865c71505ae669af19243449e\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\verthash-miner-tmp.conf]
2022/06/17 00:58:05.427221 [ERROR] Error in getSetting(testnet): not found
2022/06/17 00:58:35.137032 [ERROR] Error in getSetting(testnet): not found
2022/06/17 00:58:35.137032 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2022/06/17 00:58:35.137032 [ERROR] Error in getSetting(debugging): not found
2022/06/17 00:58:35.137032 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2022/06/17 00:58:35.137032 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2022/06/17 00:58:35.137032 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2022/06/17 00:58:35.137032 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2022/06/17 00:58:35.137032 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2022/06/17 00:58:35.137032 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2022/06/17 00:58:35.137032 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2022/06/17 00:58:35.137032 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2022/06/17 00:58:35.137032 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2022/06/17 00:58:35.137032 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2022/06/17 00:58:35.137032 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2022/06/17 00:58:35.137032 [DEBUG] [Miner windows/1]Daemon file already exists
2022/06/17 00:58:35.141167 [DEBUG] [Miner windows/1]Daemon file is available and correct
2022/06/17 00:58:35.141167 [DEBUG] [Miner windows/1]Removing unpack directory
2022/06/17 00:58:36.155257 [DEBUG] [Miner windows/1](Re)creating unpack directory
2022/06/17 00:58:40.440535 [ERROR] Error in getSetting(enableIntegrated): not found
2022/06/17 00:58:40.441536 [DEBUG] Launching C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\miners\unpacked-e5af5ab19154f6ee57db22645a43200336e8017865c71505ae669af19243449e\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\verthash-miner-tmpl.conf]
2022/06/17 00:58:40.686359 [DEBUG]Entering device block
2022/06/17 00:58:40.686359 [DEBUG]Exiting device block
2022/06/17 00:58:40.686359 [DEBUG]{0  false  }
2022/06/17 00:58:40.686359 [DEBUG]Entering device block
2022/06/17 00:58:40.686875 [DEBUG]Exiting device block
2022/06/17 00:58:40.686875 [DEBUG]{0  false  }
2022/06/17 00:58:40.686875 [DEBUG] AvailableGPUs called
2022/06/17 00:58:40.687908 [DEBUG] Launching C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\miners\unpacked-e5af5ab19154f6ee57db22645a43200336e8017865c71505ae669af19243449e\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\c_hau\AppData\Roaming\vertcoin-ocm\verthash-miner-tmp.conf]

**Comment by KforG** [comment]
This error usually appears when your antivirus is removing the miner binaries located in `%appdata%\vertcoin-ocm`. You may need to create/recreate an antivirus exception for that folder.

**Comment by MaxZero101** [comment]
Funny thing, I started the OCM up just recently and it worked fine. Very strange.
