### ISSUE TITLE
v2.1 beta3 mines faster than v2.1 beta4?

### ISSUE THREAD

**Issue by marcohern** [vertcoin-project/one-click-miner-vnext#517]
So, yeah, it would appear that while running v2.1 beta3 for what must have been weeks. Meanwhile, the mining rate was increasing. I though it must be that the difficulty is decreasing, probably due to the crypto coin crash of 2022.

But then, I upgraded to one-click-miner v2.1 beta4 and... the mining rate lowered by half. Seemingly back to pre crash days. 

I expected that it mine just as fast as it did recently. I guess not.

the versions in dispute are v2.1 beta3, which apparently mines 2 times faster than v2.1 beta4 (latest as of writing).

I have 
AMD Ryzen 7 3700K
32 GB RAM
NVidia RTX 3080
Windows 10
using Supernova.cc pool
![vtcm-21beta3](https://user-images.githubusercontent.com/5376517/182272060-8bd7c9fc-8e8c-4a06-bb6a-d8eaa26c4b4e.png)
![vtcm-21beta4](https://user-images.githubusercontent.com/5376517/182272062-5218f114-2036-4cd5-ad8a-4cdfa5f894ee.png)

**Comment by marcohern** [comment]
so um... im gonna stick to version 2.1beta3 for now...  for uhm... science... or whatever... yeah...

**Comment by KforG** [comment]
From the change list included in the 2.1-beta4 release:

- > Updated earnings calculation to account for halving (thanks @vertiond )

You aren't seeing "faster" mining, but rather an incorrect expected earnings calculation.
