### ISSUE TITLE
I cant cashout my mined vertcoin.

### ISSUE THREAD

**Issue by Kickingadustballwonderingforathousandy** [vertcoin-project/one-click-miner-vnext#518]
When i tried to cashout my mined vertcoins from one click miner, I received an error message and I was never able to get my coins.
 I expected to be able to cashout my mined vertcoins.

 When I Tried to cashout from one click miner I was met with an error message. Even though i mined the pool minimum cashout amount.

I would have to create a new vertcoin one click miner account. Mine the minimum amount of vertcoin for my pool and attempt to cashout.

 14

 I have an hp desktop. At the time of the incident I was mining with a nvidia gt 710 graphics card.

 Say , what?

Not really. I Just wish someone would tell me why i cant cashout out of vertcoin one click miner. I thought I did everything right. My email address is minordetourhaterscantstopme@gmail.com

**Comment by KforG** [comment]
Have you confirmed that the coins did not arrive in the destination address anyway? This is sometimes the case, even when an error message is displayed.

Did you confirm that the coins were in your OCM wallet, and not still held by the pool?

**Comment by Kickingadustballwonderingforathousandy** [comment]
ive tried many things. Every version ive downloaded of vertcoin one click miner, it seems defective. I cant cashout my coins from any of them. Could it be hackers? The only thing i could try new is getting the proper wallet, thats the one thing I havent tried you know the ocm one? I tried multiple things multiple times with an exodus wallet and I always got the error message and couldnt cash out. Its a shame too because I got so frustrated with mining in general last night(cudo miner) that i trashed and disposed of my amd radeon rx 560 graphics card. Cudominer doesnt pay for jack. It was an expensive card. Maybe it just wasnt meant to be. You literally responded to my question 12 hours after i trashed my only graphics card. Thanks alot. haha just teasing, well sort of.

**Comment by vertiond** [comment]
Make sure the address you send to starts with `V`, `3`, or `vtc1` - your email address won't work.  Exodus doesn't support Vertcoin.  Download [Vertcoin-Core](https://github.com/vertcoin-project/vertcoin-core/releases/tag/0.18.0), [Electrum](https://github.com/vertcoin-project/electrum/releases/tag/v4.2.2) or a mobile wallet that supports Vertcoin like Coinomi.
