### ISSUE TITLE
vertcoin-ocm

### ISSUE THREAD

**Issue by nikolai197** [vertcoin-project/one-click-miner-vnext#520]
Здравствуйте я хотел бы узнать куда делись мои vertcoin было 25 VTC стало 0 я не переводил
![Снимок экрана (24)](https://user-images.githubusercontent.com/113203575/189411815-65d87617-ebdf-485b-a7f3-d289ad60a403.png)

**Comment by KforG** [comment]
Backend servers have some temporary issues.

Your coins are safe.
