### ISSUE TITLE
I just paused and then started the miner and suddenly all my balance is gone!!!!

### ISSUE THREAD

**Issue by marcohern** [vertcoin-project/one-click-miner-vnext#521]
I was mining, stopped the miner, I usually stop the miner to play a game, and then when im done playing I would start the miner.

The behavior I expected after starting the miner was Certainly not that the balance would be zero.

Instead, what actually happened was that the balance was gone!

Reproduce this? I have been mining for days, accumulated 30vtc and now it is gone! what the hell??? reproduce this?!?!? are you kidding me?!?!?!

v2.1-beta4-000fc4e

I am Running Windows 10 with an EVGA RTX 3080 (12Gb). Im using the **suprnova.cc** pool.

**Comment by sohaib2002** [comment]
https://discord.com/channels/365207777406091266/365255650080456715/1018330160912678932

**Comment by KforG** [comment]
The coins are still there. The backend server that checks coin balances is down atm. You can click 'copy address' to the right of 'spendable balance' and enter it into a block explorer like insight.vertcoin.org and view your balance there.

Mining isn't affected.
