### ISSUE TITLE
my spendable balance cleared.

### ISSUE THREAD

**Issue by kylett92** [vertcoin-project/one-click-miner-vnext#523]
I had about 90 vertcoin ready to transfer, when i went to transfer to my wallet an error came up in the send coins tab "sending.backend_failure" when i went to go back to the spendable balance my coins have disappeared and are not in my wallet either.

**Comment by KforG** [comment]
Same answer as the multiple previous issues:

> They're still there. The backend server that checks coin balances is down atm. You can click 'copy address' to the right of 'spendable balance' and enter it into a block explorer like insight.vertcoin.org and view your balance there.
