### ISSUE TITLE
VTC missing in wallet

### ISSUE THREAD

**Issue by Milmick** [vertcoin-project/one-click-miner-vnext#524]
Hello,

During a loss of connection, my computer "mined" in a vacuum. After restarting the device the next day, all my VTCs were gone from my miner.

I expected to be able to recover my mining VTC and not lose them again...

A loss of connection for a whole night, the restart to completely erase my wallet.

I don't really have a reliable way but this is the second time it's happened to me...
1) Launch the miner and mine for a few hours or even half a day
2) Have a loss of internet connection and leave the miner running
3) Close the miner restart the computer after recovering the internet connection
4) Relaunch the miner and have nothing left in the wallet

I am using OCM v2.1-beta4-000fc4e found on official GITHUB.

My computer is a Windows 10 with an AMD R9 270X 2GB graphics card, Intel Core I5-4590K and 16GB Ram.

I share my debug file with you.

I thank you in advance.

[debug.log](https://github.com/vertcoin-project/one-click-miner-vnext/files/9543646/debug.log)

**Comment by KforG** [comment]
This happened when the backend server that loads your wallet balance was temporarily down. It very likely has something to do with that.
