### ISSUE TITLE
Earning

### ISSUE THREAD

**Issue by AcaFaca** [vertcoin-project/one-click-miner-vnext#526]
I was mining 3 VTC in 24h, now is 0.6, what's happen?? https://ibb.co/58S10k8

**Comment by KforG** [comment]
Network hashrate has increased significantly the past couple days. Simply put, the mining rewards are spread much thinner between miners.

**Comment by KforG** [comment]
You should also update to the newest version to get an accurate earnings estimation.

**Comment by flybd5** [comment]
Looks like all the ethertrash moved over to vertcoin now that their GPU's are worthless over there. Maybe the value of vertcoin will finally start rising again.

**Comment by AcaFaca** [comment]
It doesn't pay to mining VTC now, maybe I must do update, if you've done an update tell me if it's different with you?

**Comment by AcaFaca** [comment]
> Looks like all the ethertrash moved over to vertcoin now that their GPU's are worthless over there. Maybe the value of vertcoin will finally start rising again.

It doesn't pay to mining VTC now, maybe I must do update, if you've done an update tell me if it's different with you?

**Comment by flybd5** [comment]
Mining vertcoin now is a long term bet. It's cheap to do and it could turn into a goldmine.
