### ISSUE TITLE
Earnings drop to near zero randomly (hashrate remains the same)

### ISSUE THREAD

**Issue by VioletBlue007** [vertcoin-project/one-click-miner-vnext#528]
For the same hashrate, the earnings wildly fluctuate, sometimes even going to zero or near zero. My GPU is working at full capacity and the earnings should reflect that. They used to, but in the last week or so they have been extremely low (perhaps due to old Ethereum POW miners moving to other coins?). 

The earnings to be at similar levels for the same hashrate.

It seems that the new earnings are much lower than before, about 20-30% of what they used to be. 

OCM v2.1-beta4-000fc4e - downloaded from here. 

Windows 10, nVidia GeForce RTX 3070 Laptop GPU (1GB RAM)

**Comment by KforG** [comment]
Network difficulty has increased significantly the past two weeks, and it is thus expected that your earnings drop because of that.
