### ISSUE TITLE
Note on translation bounty program

### ISSUE THREAD

**Issue by gertjaap** [vertcoin-project/one-click-miner-vnext#53]
Thanks to everyone that contributed translations. I'm closing the bounty program for all but German and Russian, and any currently open pull requests. More languages might be added to this list later, but it's no longer unrestricted. We have enough languages and they all need iterative work in future releases. If you haven't yet received your bounty - tag me!

**Comment by Gesundeslicht** [comment]
Do you still need support for German translation?
