### ISSUE TITLE
OCM Wallet Password

### ISSUE THREAD

**Issue by AcaFaca** [vertcoin-project/one-click-miner-vnext#530]
How to find or reset OCM Wallet Password?

**Comment by KforG** [comment]
There is no way to recover a wallet without the password. Backup your `keyfile.hex` from `%appdata%\vertcoin-ocm` in case you remember it. Delete `keyfile.hex` and restart OCM in order to generate a new wallet.

**Comment by AcaFaca** [comment]
> There is no way to recover a wallet without the password. Backup your `keyfile.hex` from `%appdata%\vertcoin-ocm` in case you remember it. Delete `keyfile.hex` and restart OCM in order to generate a new wallet.

I can't send coins without password this is problem, what will happen with mined Vertcoin when I generate a new wallet??

**Comment by KforG** [comment]
No you can't send the mined coins. Unless you remember your password later and restore access using the backed up keyfile.hex, those coins are effectively lost.

When generating a new wallet you'll start from scratch.
