### ISSUE TITLE
My rtx 3070 is mining like 1/2 of a 1050ti

### ISSUE THREAD

**Issue by nermain** [vertcoin-project/one-click-miner-vnext#550]
What the title is
 I expected to gain ~1.4 VTC per day

 it is happening rn 

 the beta version OCM v2.2-beta1-cda2154

 manli 3070 lhr

 In 3 days instead of mining 1.4VTC per day it's actually mining 0.1VTC per day while 1050TI in the other room gets 0.24/day, idk why it's happening, but it's the past 3 days I haven't done anything weird, afterburner is the same like weeks agowhen I started, I tried with out the undervoltage and nothing. All this time mining it actually is burning 128W/hr so IDK what it's doing, kinda weird.

**Comment by vertiond** [comment]
Use the Vertcoin discord/reddit for help regarding tuning.
