### ISSUE TITLE
Moving coins from core wallet

### ISSUE THREAD

**Issue by 3sixtymining** [vertcoin-project/one-click-miner-vnext#551]
When I try to move coins from core wallet I get a error message " sending.backend_failure". Please assist.

**Comment by koraycoding** [comment]
> When I try to move coins from core wallet I get a error message " sending.backend_failure". Please assist.

You don't have to send your coins from core wallet. Vertcoin has an it's own electrum client so export your private key from your wallet and import into electrum. Your coins will be ready to send in a minute.

**Comment by vertiond** [comment]
I believe this may have been related to the backend server being down which is resolved now.
