### ISSUE TITLE
OCM did not prompt me to set a password.

### ISSUE THREAD

**Issue by EJLouieB** [vertcoin-project/one-click-miner-vnext#556]
Just downloaded the "latest" release. generated files fine, then started mining. Then I remembered it should have prompted me to set a password, and I cannot figure out how to set one so that I can actually spend the coins?

https://github.com/vertcoin-project/one-click-miner-vnext/releases/download/2.1/vertcoin-ocm-2.1-windows-x64.zip

 Win 10, 1070, P-106 100

**Comment by vertiond** [comment]
That means an encrypted keyfile exists in the AppData folder already. Delete `%AppData%\vertcoin-ocm\keyfile.hex` and restart.
