### ISSUE TITLE
About mining rate

### ISSUE THREAD

**Issue by sankalpbhore** [vertcoin-project/one-click-miner-vnext#561]
I am using One click miner at my Laptop, which is consist of an GTX 1650 graphics card in it,
the problem i am facing is , i am not getting enough speed for mining as my graphics card also not being used 10%

I expect that I should get more speed than that as i am getting only 196 kh/s rate right now..

I am using OCM v 2.2

GPU

%APPDATA%\vertcoin-ocm on Windows

![image](https://user-images.githubusercontent.com/124596154/217007624-0e32e5af-0022-4a32-bac4-38b30a9d2f28.png)

**Comment by KforG** [comment]
That is about the expected performance for that GPU on the Verthash algorithm. You might squeeze additional performance out of it by overclocking the GPU.

When looking at GPU usage you need to specifically look at CUDA usage, and not any other metric.
