### ISSUE TITLE
Miner reports failure to send coins to wallet but coins arrive.

### ISSUE THREAD

**Issue by flybd5** [vertcoin-project/one-click-miner-vnext#569]
Attempting to send coins to my wallets reports failure but coins arrive.

Success message.

Coins arrived. Miner still thinks it has the coins.

![image](https://user-images.githubusercontent.com/6594563/224459853-67fb4c8c-e70b-4799-a66d-81edc1790a30.png)

This has happened the last three times I have tried to send my coins. The coins arrive but the miner reports failure.

2.2-beta1-cda2154 from github

Win 10, 2060 GPU

[debug.log](https://github.com/vertcoin-project/one-click-miner-vnext/files/10947375/debug.log)

**Comment by egginabucket** [comment]
Also experiencing this intermittently.
