### ISSUE TITLE
Zergpool 0.3% fee

### ISSUE THREAD

**Issue by realsetvin** [vertcoin-project/one-click-miner-vnext#575]
Zergpool has created a special code which you can apply to your program. Include "refcode=newminerbonus" (without quotes) into the mining software and anyone who uses it will get access to 0.3% fees if they choose to select zergpool.

**Comment by KforG** [comment]
Is this going to be a permanent thing? And can people use the refcode 'forever'?

I assume this will be set in the password field. That can be done here: https://github.com/vertcoin-project/one-click-miner-vnext/blob/cda2154a76f6c0480a549c12c762e0f6955cbdc0/pools/zergpool.go#L45

Feel free to create a PR for it.

**Comment by KforG** [comment]
If it's permanent the fee can also be changed https://github.com/vertcoin-project/one-click-miner-vnext/blob/cda2154a76f6c0480a549c12c762e0f6955cbdc0/pools/zergpool.go#L57

**Comment by vertiond** [comment]
I think we should leave this to the Zergpool operators to update here if they choose to. Please ask them to make a PR.
