### ISSUE TITLE
Wrong

### ISSUE THREAD

**Issue by casbtosint** [vertcoin-project/one-click-miner-vnext#578]
![photo_2023-09-12_05-38-55](https://github.com/vertcoin-project/one-click-miner-vnext/assets/130416360/8bf9e655-6b32-4404-8cf5-a18549580bca)

**Comment by KforG** [comment]
When launching the program you need to let it generate the verthash.dat file to completion before closing down OCM. This may take a while depending on the performance of your computer.

When you click the green button, it should start to regenerate the file.
