### ISSUE TITLE
Where can we exchange Vertcoin?

### ISSUE THREAD

**Issue by solar1pv** [vertcoin-project/one-click-miner-vnext#585]
Where can i exchange Vertcoin?
What can I purchase with Vertcoin?

Where can I spend Vertcoin?

How can I exchange Vertcoin for Bitcoin?

One Click Miner OCM v2.1-000fc4e.  where did you get it: Vercoin one click miner

What type of machine are you observing the error on: (Windows/ AMD)

**Comment by KforG** [comment]
This page is for issues related to the Vertcoin One Click Miner, not for questions about Vertcoin.

I would suggest you either look at the Vertcoin website(s) and/or join the Vertcoin discord for these questions.
