### ISSUE TITLE
Adding my P2Pool node to the OCM p2pool json list

### ISSUE THREAD

**Issue by CADMonkey21** [vertcoin-project/one-click-miner-vnext#586]
What is the process for getting a new P2Pool node added to the OCM nodes list? Below is the code that needs to be added to the P2Pool json file. I'm not a programmer so please check my entries. I simply would like this node added as I plan to maintain this p2pool full node. Thank you!

    // ... (existing entries)
    {
        "Hostname": "vtc-ut.myangelprints.com",
        "Stratum":  "stratum+tcp://vtc-ut.myangelprints.com:9171",
        "URL":      "http://vtc-ut.myangelprints.com:9171/static/"
    }
]

**Comment by KforG** [comment]
Please open a PR.

See the existing PR #558 for any doubts about the formatting.
