### ISSUE TITLE
Payout disappeared into thin air,

### ISSUE THREAD

**Issue by flybd5** [vertcoin-project/one-click-miner-vnext#587]

**Comment by KforG** [comment]
You need to provide more details than this if you want help.

We can't debug your issue with nothing to go on.

**Comment by flybd5** [comment]
I tried to do that but when I tried to post my reply with the debug log, it disappeared. Poof. Nothing. I am not in the mood to waste 20 min of my time again. It was much easier to report the issue to Zergpool.
