### ISSUE TITLE
Miner not working, please help

### ISSUE THREAD

**Issue by Napes7** [vertcoin-project/one-click-miner-vnext#594]
Windows 11

Miner will not detect GPU, says it is mining, but sits there with 0 VTC and 0 expected earnings.

Other miners work fine on my pc.

can someone please help?

**Comment by KforG** [comment]
This error can occur for a few reasons:
1. Antivirus/firewall is blocking the connection to the pool. You'll need to find out how to allow it through, make sure to also have an exception made in your antivirus for `%appdata%\vertcoin-ocm`.
2. If you're using an ASUS router it's likely blocking the connection with its "AIProtection" feature that blocks 2-way IPS. Disabling this likely will allow the connection to go through.
3. Your DNS is acting weird, changing it to an alternative one may help.
4. The GPU is being limited by the miner when temperatures exceed 79 degrees Celsius.

**Comment by Napes7** [comment]
Hey thanks KforG.  Tried all those options, nothing seems to work.   Is there any foolproof Youtube video out there for a noob like me?

**Comment by KforG** [comment]
Have you tried using a different pool? You can select another in the settings tab.

**Comment by KforG** [comment]
Closed due to inactivity
