### ISSUE TITLE
GPU not detected

### ISSUE THREAD

**Issue by pypro485** [vertcoin-project/one-click-miner-vnext#624]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read [Common issues and fixes](https://github.com/vertcoin-project/one-click-miner-vnext/issues/618)?.

- [X] Yes / Not relevant

### Current behaviour

When I open my Vertcoin Ocm i see a screen that says, "No Compatible GPUs detecated GPUs found" I have a 4070ti and that is supported and i have been running the ocm for a long time and i never got this error.

![Screenshot 2024-03-22 173523](https://github.com/vertcoin-project/one-click-miner-vnext/assets/107079353/287db486-331d-46a9-af79-958a39a0e189)

### Expected behaviour

I expect the ocm to run and start mining vertcoin

### Steps to reproduce

Run the latest version of the ocm

### Relevant log output

2024/03/22 16:54:41.883313 OCM v2.2-0-g27859cb Started up
2024/03/22 16:54:41.884853 [ERROR] Error in getSetting(testnet): not found
2024/03/22 16:54:41.884853 [ERROR] Error in getSetting(pool): not found
2024/03/22 16:54:41.884853 [ERROR] Error in getSetting(testnet): not found
2024/03/22 16:54:41.884853 [INFO] Finding best P2Pool node...
2024/03/22 16:54:41.884853 [ERROR] Error in getSetting(testnet): not found
2024/03/22 16:54:41.884853 [INFO] Error reading keyfile: open C:\Users\somen\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2024/03/22 16:54:41.884853 [ERROR] Error in getSetting(testnet): not found
2024/03/22 16:54:41.885392 [INFO] Error reading keyfile: open C:\Users\somen\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2024/03/22 16:54:41.885392 [ERROR] Error in getSetting(testnet): not found
2024/03/22 16:54:41.885392 [INFO] No local node detected, selecting other public nodes
2024/03/22 16:54:42.001099 [INFO] User IETF is en-US
2024/03/22 16:54:42.001605 [INFO] Matched tag is en-u-rg-uszzzz
2024/03/22 16:54:42.001605 [INFO] Returning locale en
2024/03/22 16:54:42.016914 [ERROR] Error in getSetting(testnet): not found
2024/03/22 16:54:42.037343 [INFO] Checking wallet..
2024/03/22 16:54:42.037343 [INFO] Error reading keyfile: open C:\Users\somen\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2024/03/22 16:54:42.037343 [INFO] Error reading keyfile: open C:\Users\somen\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2024/03/22 16:54:42.037343 [INFO] Error reading keyfile: open C:\Users\somen\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2024/03/22 16:54:42.037343 [INFO] Initializing wallet VrSwsBBq6TgsAyy8YQdes4we49o6KyiqFU
2024/03/22 16:54:42.037850 [INFO] Wallet initialized: 0
2024/03/22 16:54:42.114666 [INFO] Using backend: https://ocmbackend.mindcraftblocks.com/
2024/03/22 16:54:43.035890 [INFO] mindcraftblocks.com: 27.78935ms 
2024/03/22 16:54:43.054544 [INFO] p2p-usa.xyz: 40.2474ms 
2024/03/22 16:54:43.088495 [INFO] vtc-fl.javerity.com: 58.5011ms 
2024/03/22 16:54:43.120211 [INFO] vtc-ca.javerity.com: 92.29345ms 
2024/03/22 16:54:43.145229 [INFO] p2p-spb.xyz: 123.8159ms 
2024/03/22 16:54:43.163582 [INFO] p2p-ekb.xyz: 148.74905ms 
2024/03/22 16:54:43.172363 [INFO] p2p-south.xyz: 166.5705ms 
2024/03/22 16:54:43.208461 [INFO] boofpool.ddns.net: 117.24155ms 
2024/03/22 16:54:43.253778 [INFO] vtc-brn.webhop.me: 156.12475ms 
2024/03/22 16:54:44.028051 [INFO] vtc-ut.myangelprints.com: 0s 
2024/03/22 16:54:44.082303 [INFO] mindcraftblocks.com selected, fulfilled all requirements
2024/03/22 16:54:44.082303 [INFO] Found best P2Pool node: http://mindcraftblocks.com:9171/
2024/03/22 16:54:47.017892 [INFO] Error reading keyfile: open C:\Users\somen\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2024/03/22 16:54:52.034230 [INFO] Error reading keyfile: open C:\Users\somen\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2024/03/22 16:54:57.049576 [INFO] Error reading keyfile: open C:\Users\somen\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2024/03/22 16:54:59.304522 [INFO] Checking wallet..
2024/03/22 16:54:59.312518 [INFO] Initializing wallet VfNSgJVEyZNTxD86JK88DEbk7LHxLkYuDB
2024/03/22 16:54:59.312518 [INFO] Wallet initialized: 1
2024/03/22 16:54:59.312518 [ERROR] Error in getSetting(testnet): not found
2024/03/22 16:54:59.408932 [ERROR] Error in getSetting(testnet): not found
2024/03/22 16:55:07.404990 [INFO] Stopping mining process...
2024/03/22 16:55:16.700011 OCM v2.2-0-g27859cb Started up
2024/03/22 16:55:16.701582 [ERROR] Error in getSetting(testnet): not found
2024/03/22 16:55:16.701582 [ERROR] Error in getSetting(testnet): not found
2024/03/22 16:55:16.701582 [INFO] Finding best P2Pool node...
2024/03/22 16:55:16.701582 [ERROR] Error in getSetting(testnet): not found
2024/03/22 16:55:16.702108 [INFO] No local node detected, selecting other public nodes
2024/03/22 16:55:29.138495 OCM v2.2-0-g27859cb Started up
2024/03/22 16:55:29.139560 [ERROR] Error in getSetting(testnet): not found
2024/03/22 16:55:29.139560 [INFO] Finding best P2Pool node...
2024/03/22 16:55:29.139560 [ERROR] Error in getSetting(testnet): not found
2024/03/22 16:55:29.139560 [ERROR] Error in getSetting(testnet): not found
2024/03/22 16:55:29.139560 [INFO] No local node detected, selecting other public nodes
2024/03/22 16:55:31.904643 OCM v2.2-0-g27859cb Started up
2024/03/22 16:55:31.905702 [ERROR] Error in getSetting(testnet): not found
2024/03/22 16:55:31.905702 [INFO] Finding best P2Pool node...
2024/03/22 16:55:31.905702 [ERROR] Error in getSetting(testnet): not found
2024/03/22 16:55:31.906217 [ERROR] Error in getSetting(testnet): not found
2024/03/22 16:55:31.906217 [INFO] No local node detected, selecting other public nodes
2024/03/22 16:55:31.968495 [INFO] Using backend: https://ocmbackend.javerity.com/
2024/03/22 16:55:32.014608 [INFO] User IETF is en-US
2024/03/22 16:55:32.014608 [INFO] Matched tag is en-u-rg-uszzzz
2024/03/22 16:55:32.014608 [INFO] Returning locale en
2024/03/22 16:55:32.029271 [ERROR] Error in getSetting(testnet): not found
2024/03/22 16:55:32.046899 [INFO] Checking wallet..
2024/03/22 16:55:32.046899 [INFO] Initializing wallet VfNSgJVEyZNTxD86JK88DEbk7LHxLkYuDB
2024/03/22 16:55:32.046899 [INFO] Wallet initialized: 1
2024/03/22 16:55:32.061480 [ERROR] Error in getSetting(testnet): not found
2024/03/22 16:55:33.003670 [INFO] mindcraftblocks.com: 27.17045ms 
2024/03/22 16:55:33.021708 [INFO] p2p-usa.xyz: 39.60945ms 
2024/03/22 16:55:33.054032 [INFO] vtc-fl.javerity.com: 57.7369ms 
2024/03/22 16:55:33.079884 [INFO] vtc-ca.javerity.com: 90.79545ms 
2024/03/22 16:55:33.087924 [INFO] boofpool.ddns.net: 112.1255ms 
2024/03/22 16:55:33.112112 [INFO] p2p-spb.xyz: 123.10195ms 
2024/03/22 16:55:33.123052 [INFO] p2p-ekb.xyz: 147.69275ms 
2024/03/22 16:55:33.131474 [INFO] vtc-brn.webhop.me: 158.3051ms 
2024/03/22 16:55:33.199397 [INFO] p2p-south.xyz: 166.9097ms 
2024/03/22 16:55:33.997979 [INFO] vtc-ut.myangelprints.com: 0s 
2024/03/22 16:55:34.042921 [INFO] mindcraftblocks.com selected, fulfilled all requirements
2024/03/22 16:55:34.042921 [INFO] Found best P2Pool node: http://mindcraftblocks.com:9171/
2024/03/22 17:00:14.868260 [INFO] Stopping mining process...
2024/03/22 17:15:10.651448 OCM v2.2-beta1-cda2154 Started up
2024/03/22 17:15:10.652449 [ERROR] Error in getSetting(testnet): not found
2024/03/22 17:15:10.652449 [ERROR] Error in getSetting(testnet): not found
2024/03/22 17:15:12.667648 [INFO] No local node detected, selecting other public nodes
2024/03/22 17:15:14.077756 [INFO] mindcraftblocks.com: 21.9481ms 
2024/03/22 17:15:15.255273 [INFO] vtc-fl.javerity.com: 60.4018ms 
2024/03/22 17:15:16.452696 [INFO] vtc-ca.javerity.com: 85.9718ms 
2024/03/22 17:15:17.605163 [INFO] p2p-usa.xyz: 34.05565ms 
2024/03/22 17:15:18.868275 [INFO] p2p-ekb.xyz: 143.84865ms 
2024/03/22 17:15:20.114294 [INFO] p2p-spb.xyz: 123.08335ms 
2024/03/22 17:15:21.394534 [INFO] p2p-south.xyz: 161.7424ms 
2024/03/22 17:15:23.516692 [INFO] boofpool.ddns.net: 115.7782ms 
2024/03/22 17:15:25.716669 [INFO] vtc-ut.myangelprints.com: 0s 
2024/03/22 17:15:27.039362 [INFO] vtc-brn.webhop.me: 156.08835ms 
2024/03/22 17:15:27.109541 [INFO] mindcraftblocks.com selected, fulfilled all requirements
2024/03/22 17:15:27.109541 [ERROR] Error in getSetting(testnet): not found
2024/03/22 17:15:27.246986 [INFO] User IETF is en-US
2024/03/22 17:15:27.246986 [INFO] Matched tag is en-u-rg-uszzzz
2024/03/22 17:15:27.246986 [INFO] Returning locale en
2024/03/22 17:15:27.261583 [ERROR] Error in getSetting(testnet): not found
2024/03/22 17:15:27.283158 [INFO] Checking wallet..
2024/03/22 17:15:27.283158 [INFO] Initializing wallet VfNSgJVEyZNTxD86JK88DEbk7LHxLkYuDB
2024/03/22 17:15:27.283676 [INFO] Wallet initialized: 1
2024/03/22 17:15:27.496213 [ERROR] Error in getSetting(testnet): not found
2024/03/22 17:15:34.813525 [ERROR] Error in getSetting(debugging): not found
2024/03/22 17:15:34.819297 [ERROR] Error in getSetting(testnet): not found
2024/03/22 17:15:34.819811 [ERROR] Error in getSetting(testnet): not found
2024/03/22 17:15:35.080473 [ERROR] Error in getSetting(enableIntegrated): not found
2024/03/22 17:15:42.145712 [INFO] Setting closed source to [%!b(bool=false)]
2024/03/22 17:15:42.150965 [INFO] Setting debugging to [%!b(bool=false)]
2024/03/22 17:15:42.180037 [ERROR] Error in getSetting(testnet): not found
2024/03/22 17:15:42.181667 [ERROR] Error in getSetting(testnet): not found
2024/03/22 17:15:42.181667 [INFO] Calling WalletInitialized
2024/03/22 17:15:42.181667 [INFO] Checking wallet..
2024/03/22 17:15:42.181667 [INFO] Initializing wallet VfNSgJVEyZNTxD86JK88DEbk7LHxLkYuDB
2024/03/22 17:15:42.182171 [INFO] Wallet initialized: 1
2024/03/22 17:15:42.182171 [INFO] Done!
2024/03/22 17:15:42.193775 [INFO] Stopping mining process...
2024/03/22 17:16:47.588899 [INFO] Stopping mining process...
2024/03/22 17:16:48.744433 [ERROR] Error in getSetting(testnet): not found
2024/03/22 17:17:36.270584 [INFO] Stopping mining process...
2024/03/22 17:17:36.291911 [ERROR] Error in getSetting(testnet): not found
2024/03/22 17:26:56.882618 [INFO] Stopping mining process...
2024/03/22 17:27:00.140445 OCM v2.2-0-g27859cb Started up
2024/03/22 17:27:00.148766 [ERROR] runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running, locked to thread]:
runtime/debug.Stack()
	C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x5e
main.main.func1()
	C:/Users/KG/Documents/GitHub/one-click-miner-vnext/main.go:36 +0x105
panic({0x13507a0?, 0x12cc2e0?})
	C:/Program Files/Go/src/runtime/panic.go:770 +0x132
github.com/tidwall/buntdb.(*Tx).lock(0x1000030dbb8?)
	C:/Users/KG/go/pkg/mod/github.com/tidwall/buntdb@v1.3.0/buntdb.go:1140 +0x1c
github.com/tidwall/buntdb.(*DB).Begin(0x0, 0x0)
	C:/Users/KG/go/pkg/mod/github.com/tidwall/buntdb@v1.3.0/buntdb.go:1117 +0x59
github.com/tidwall/buntdb.(*DB).managed(0xe5201e?, 0x0, 0xc00030dc78)
	C:/Users/KG/go/pkg/mod/github.com/tidwall/buntdb@v1.3.0/buntdb.go:989 +0x37
github.com/tidwall/buntdb.(*DB).View(...)
	C:/Users/KG/go/pkg/mod/github.com/tidwall/buntdb@v1.3.0/buntdb.go:1022
github.com/vertcoin-project/one-click-miner-vnext/backend.(*Backend).getSetting(0xc00030dd01?, {0x13e03ec, 0x7})
	C:/Users/KG/Documents/GitHub/one-click-miner-vnext/backend/settings.go:19 +0x7e
github.com/vertcoin-project/one-click-miner-vnext/backend.(*Backend).GetTestnet(...)
	C:/Users/KG/Documents/GitHub/one-click-miner-vnext/backend/settings.go:122
main.main()
	C:/Users/KG/Documents/GitHub/one-click-miner-vnext/main.go:99 +0x512

2024/03/22 17:27:50.961695 OCM v2.2-0-g27859cb Started up
2024/03/22 17:27:50.962723 [ERROR] Error in getSetting(testnet): not found
2024/03/22 17:27:50.962723 [INFO] Finding best P2Pool node...
2024/03/22 17:27:50.962723 [ERROR] Error in getSetting(testnet): not found
2024/03/22 17:27:50.962723 [ERROR] Error in getSetting(testnet): not found
2024/03/22 17:27:50.963745 [INFO] No local node detected, selecting other public nodes
2024/03/22 17:27:51.088018 [INFO] User IETF is en-US
2024/03/22 17:27:51.088018 [INFO] Matched tag is en-u-rg-uszzzz
2024/03/22 17:27:51.088018 [INFO] Returning locale en
2024/03/22 17:27:51.122129 [ERROR] Error in getSetting(testnet): not found
2024/03/22 17:27:51.122646 [INFO] Checking wallet..
2024/03/22 17:27:51.122646 [INFO] Initializing wallet VfNSgJVEyZNTxD86JK88DEbk7LHxLkYuDB
2024/03/22 17:27:51.123214 [INFO] Wallet initialized: 1
2024/03/22 17:27:51.133510 [ERROR] Error in getSetting(testnet): not found
2024/03/22 17:27:51.155933 [INFO] Using backend: https://ocmbackend.mindcraftblocks.com/
2024/03/22 17:27:52.098851 [INFO] p2p-usa.xyz: 36.8378ms 
2024/03/22 17:27:52.133852 [INFO] vtc-fl.javerity.com: 54.7194ms 
2024/03/22 17:27:52.155500 [INFO] vtc-ca.javerity.com: 90.39935ms 
2024/03/22 17:27:52.165413 [INFO] mindcraftblocks.com: 26.6177ms 
2024/03/22 17:27:52.183028 [INFO] p2p-spb.xyz: 121.40385ms 
2024/03/22 17:27:52.191120 [INFO] boofpool.ddns.net: 110.0609ms 
2024/03/22 17:27:52.209153 [INFO] p2p-ekb.xyz: 146.5577ms 
2024/03/22 17:27:52.245620 [INFO] p2p-south.xyz: 165.5058ms 
2024/03/22 17:27:52.320226 [INFO] vtc-brn.webhop.me: 157.2329ms 
2024/03/22 17:27:53.175447 [INFO] vtc-ut.myangelprints.com: 0s 
2024/03/22 17:27:53.226168 [INFO] mindcraftblocks.com selected, fulfilled all requirements
2024/03/22 17:27:53.226168 [INFO] Found best P2Pool node: http://mindcraftblocks.com:9171/

### How did you obtain Vertcoin OCM?

Pre-built binaries

### What version of Vertcoin OCM are you using?

One Click Miner vNext 2.2 Final

### Operating system and version

Windows 11

### Machine specifications

![Screenshot 2024-03-22 173326](https://github.com/vertcoin-project/one-click-miner-vnext/assets/107079353/6095f97a-25f6-426a-abc0-2e7471c8a21c)
![Screenshot 2024-03-22 173356](https://github.com/vertcoin-project/one-click-miner-vnext/assets/107079353/66f08110-5c2f-4d53-9d7e-769413444269)

**Comment by KforG** [comment]
This error is described in [Common issues and fixes](https://github.com/vertcoin-project/one-click-miner-vnext/issues/618) and is almost always causes by antivirus.

> This error may occur if your antivirus software detects the miner as a false positive and blocks it from starting. To resolve this issue, you might need to add an exception for the OCM's data directory in your antivirus settings.
Windows: %appdata%\vertcoin-ocm

If you already have exceptions in place try redoing them.

**Comment by susssssssssssss** [comment]
I did what you said but still it is giving me the same error and I even turned off windows defender

**Comment by KforG** [comment]
Antivirus or drivers, has always been the causes of this error if the GPU was compatible.

Given you've run this thing in the past, something must've changed in your environment. If you've recently updated GPU drivers, try downgrading them. There's not really any way for me to help you debug this.

**Comment by KforG** [comment]
Closed due to inactivity

**Comment by peeeto111** [comment]
Same problem GPU 3070 win 11 24H2 it worked on win 10, but I had to reinstall so after that I got this uncompatible message
