### ISSUE TITLE
no balances visible anymore?

### ISSUE THREAD

**Issue by buzztiaan** [vertcoin-project/one-click-miner-vnext#63]
2019/09/02 12:29:07.184437 [ERROR] Error fetching UTXOs from Insight: invalid character '<' looking for beginning of value

reported balance is now zero

**Comment by buzztiaan** [comment]
seems because insight.vertcoin.org is offline

**Comment by gertjaap** [comment]
Yep, that's the reason. Unfortunate, but making OCM easier to install comes at the price of relying on other services that can go down. I've reported the insight failure to @metalicjames who maintains it, hoping it'll be restored quickly.

Since this is not an issue for OCM itself, closing this.

**Comment by buzztiaan** [comment]
perfect, thanks for passing it forward
