### ISSUE TITLE
fail access error

### ISSUE THREAD

**Issue by dahaabz6** [vertcoin-project/one-click-miner-vnext#633]
please review the screenshot, I get this error most of the time and every time I get this error the app not starting until restore my OS.
![Screenshot 2024-07-27 020016](https://github.com/user-attachments/assets/ace66aef-d83d-4d61-9ffb-029a83d698e4)
![Screenshot 2024-07-27 020016](https://github.com/user-attachments/assets/8dce5c44-f1aa-47a0-b091-8a830231c85c)

**Comment by KforG** [comment]
Likely some issue with antivirus as described in #618
