### ISSUE TITLE
vertcoin oneclick miner stole my coins

### ISSUE THREAD

**Issue by babablacksheep7** [vertcoin-project/one-click-miner-vnext#69]
After 1 full month of mining coins your oneclick miner stole all my coins and balance says zero

**Comment by gertjaap** [comment]
The one-click miner uses the Insight block explorer to fetch the balance of the address you are mining to. There was a large reorg on the blockchain which made Insight have to reindex its block index, which is currently happening (You can see the progress on the top right of the [Insight homepage](http://insight.vertcoin.org/)). Once that reaches 100% i'm fairly sure your balance will be visible again.

**Comment by gertjaap** [comment]
Also, the one-click miner generates the private key for your wallet on your computer, and protects it with a password you enter into the application when storing it on your hard drive. The control of the mined coins is solely with you, and you should ensure you keep the wallet file safe by backing it up, to prevent causing any disaster happening to your PC to result in losing your coins.

I have no access to your keys or your coins, nor am I interesting in having that.

**Comment by babablacksheep7** [comment]
I want to apologize for my bad behavior in jumping to conclusions , by assuming the worst and making a rash accusation stemming from my lack of undertanding of how the miner works. I do offer a suggestion as many may be newbies like me. On the miner you have buttons for settings and wallet. You could please add a faq page explaining the hidden functions and descriptions of how this works behind the scenes as not seen from looking at GUI. Thankyou .
