### ISSUE TITLE
Nvidia Geforce MX250 / Integrated Intel 10th Gen Unmatched GPU

### ISSUE THREAD

**Issue by aeiouknown** [vertcoin-project/one-click-miner-vnext#71]
When loading OCM with latest Xubuntu, the software crashes

I expect the software to run

https://pastebin.com/LNA9AgPj

Every time

Beta5 binary

https://pastebin.com/SZfVv04i

Xubuntu 9.10 
Linux jetstream 5.3.0-27-generic #29-Ubuntu SMP Thu Jan 9 01:36:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

https://pastebin.com/ky84u5nD

**Comment by gertjaap** [comment]
The crash isn't GPU related. There's an error when sending tracking data (you could work around by opting out). I fixed the issue, and the fix will be part of a next release.
