### ISSUE TITLE
(Linux) No GPU's detected on Integrated Intel \ Nvidia GPU setup

### ISSUE THREAD

**Issue by aeiouknown** [vertcoin-project/one-click-miner-vnext#72]
No GPU's detected on Integrated Intel \ Nvidia GPU setup

https://pastebin.com/sNzFW595

Linux jetstream 5.3.0-27-generic #29-Ubuntu SMP Thu Jan 9 01:36:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Xubuntu 19.10, Eoan Ermine

https://pastebin.com/5EPPpY4w

**Comment by TipzTeam** [comment]
Same, but i have iGPU and AMD GPU

**Comment by WhitG** [comment]
![image](https://user-images.githubusercontent.com/26853422/74867723-cce47200-531a-11ea-899e-8f9ed16b27cd.png)
Checks failed. No compatible GPUs detected on HP Pavilion Windows 10.  Any help would be appreciated

**Comment by gertjaap** [comment]
Please try the updated release:

https://github.com/vertcoin-project/one-click-miner-vnext/releases/tag/1.0-rc1

@aeiouknown : Your GPU should now be detected

@TipzTeam @WhitG  please try with this new version and post a separate (new) issue with a screenshot of the GPU detection failing - i've added more information to that screen that should help localize your specific issue better. No two machines are the same, so we shouldn't merge every problem into the same issue - the reason for failed detection could be different per hardware platform (laptop / desktop), manufacturer, other hardware in the system, GPU and operating system.
