### ISSUE TITLE
'Save & Restart' button not accessible after checking box for 'Use closed-source miners'

### ISSUE THREAD

**Issue by Vertian** [vertcoin-project/one-click-miner-vnext#75]
![Screenshot from 2020-02-26 12-02-40](https://user-images.githubusercontent.com/35286924/75373527-18090280-5890-11ea-998a-2b587a921243.png)

This is on Windows, it seems like the qt window is fixed and the information section for the closed-source miners pushes the 'Save & Restart' button off the bottom edge.

**Comment by gertjaap** [comment]
Fixed in https://github.com/vertcoin-project/one-click-miner-vnext/commit/a31434c49580ae5747853a037eed3b45e7e92503

**Comment by gertjaap** [comment]
Resolved in https://github.com/vertcoin-project/one-click-miner-vnext/releases/tag/1.0-rc2 
If not, feel free to reopen the issue
