### ISSUE TITLE
Make a more friendly error notice for Insight being unavailable

### ISSUE THREAD

**Issue by gertjaap** [vertcoin-project/one-click-miner-vnext#77]
When Insight is unavailable, the OCM is unable to determine the amount of coins held, unable to calculate expected earnings (since it can't retrieve the network difficulty), nor spend any coins (since it can't fetch the unspent outputs to compose the transaction).

While this is a conscious design choice (the benefit being not having to run/install your own full node) it's very crippling. Usually, insight isn't down for prolongued periods of time - but still when Insight is down - the symptoms are worrying to users (it looks like the wallet is empty when it's really not).

So, it seems sensible to make a better error notice saying something along the lines of:

```
Due to the unavailability of the backend, we cannot display your balance or 
expected earnings right now. You can check your wallet balance by entering 
your address {X} into a working block explorer. Once the backend is available 
again, your balance will be visible
```

**Comment by vertiond** [comment]
Replaced Insight with ocm-backend.
