### ISSUE TITLE
No Compatible GPU Detected!

### ISSUE THREAD

**Issue by Shenron2020** [vertcoin-project/one-click-miner-vnext#79]
It Finds (Detects) the GPU. But Says it is incompatible.
I have a AMD Radeon Pro 5300M, I just need help trying to run this
I am also new to mining in general.

![IMG_2291](https://user-images.githubusercontent.com/40416209/79771580-d7ec5c00-82e3-11ea-8ba8-77b65b196a86.jpg)

**Comment by gertjaap** [comment]
Hey, thanks for reporting this issue. I've seen various problems with device detection over the past few months. I've revamped this system in a new Alpha 2.0 release. Would you be willing to test that out and let me know if it works for you or not? 

You can download the new release [here](https://github.com/vertcoin-project/one-click-miner-vnext/releases/tag/2.0-alpha1)

**Comment by gertjaap** [comment]
@Shenron2020 Could you let me know if you've managed to try the new alpha release and if it detects your GPU properly? If it still doesn't work, feel free to post the debug.log (which you can find in `%APPDATA%\vertcoin-ocm` on Windows and reopen the issue.

**Comment by Shenron2020** [comment]
The alpha version works.
