### ISSUE TITLE
Initial hashrate reporting

### ISSUE THREAD

**Issue by gertjaap** [vertcoin-project/one-click-miner-vnext#8]
Takes time for the miner to start reporting hashrate. It might make sense to show some animation/spinner or something to show the user the miner binaries are started, just waiting for the first hashrate report to be printed.

**Comment by mentalitycz** [comment]
whatever dynamic on first screen would be helpfull.... somthing like:

Estimating.   Estimating..   Estimating...

**Comment by gertjaap** [comment]
Included in Alpha 19
