### ISSUE TITLE
Not sending coins

### ISSUE THREAD

**Issue by SCIZOMAD** [vertcoin-project/one-click-miner-vnext#80]
not sending coins to wallet

It was sending coins but not efficiently and since new update it doesn't send coins at all

It says the coins are sent but they don't get sent

every time I try. It doesn't work

I am using the latest version from vertcoin.org

I have a windows 10os with a RTX280Ti

**Comment by gertjaap** [comment]
Could you post the contents of your debug.log for analysis? It's located in `%APPDATA%\vertcoin-ocm` on Windows

**Comment by SCIZO666** [comment]
> Could you post the contents of your debug.log for analysis? It's located in `%APPDATA%\vertcoin-ocm` on Windows

[debug.log](https://github.com/vertcoin-project/one-click-miner-vnext/files/4549457/debug.log)

**Comment by SCIZO666** [comment]
Good luck, trying to figure out what's wrong with it.

**Comment by gertjaap** [comment]
@SCIZOMAD Thanks for posting the log, but you've posted the debug.log to Vertcoin Core, which is not what I need. I'm assuming that you are sending the coins from the One-Click Miner to your wallet running in Vertcoin Core. 

If the One-Click Miner says a transaction is sent, it will also show you the link to the transaction on a block explorer. Can you see that transaction and/or post a link to it here?

Which address are you sending the coins to, is that an address that came from the Vertcoin Core wallet?

And again, the debug.log to the One-Click Miner is located in `%APPDATA%\vertcoin-ocm` (so not `%APPDATA%\vertcoin` like the one you posted above.

**Comment by SCIZOMAD** [comment]
I have attached the debug log you requested. I am pretty sure it is the right one, this time. I have also attached a screenshot of the wallet and one-click-miner, just after I tried to send the coins. It doesn't come up with a transaction link, but it says the coins are sent.

[debug.log](https://github.com/vertcoin-project/one-click-miner-vnext/files/4550023/debug.log)
![Screenshot (5)](https://user-images.githubusercontent.com/56139433/80566117-c95d1d80-8a24-11ea-8e48-83bab6e0427e.png)

**Comment by SCIZOMAD** [comment]
I hope this will help you.

**Comment by gertjaap** [comment]
@SCIZOMAD  Thanks, that's helpful and it's the correct log. 

What's the address you're trying to send to? The log file says `invalid_address` a few times. Maybe there's some whitespace (enter or space) coming with when you copy the address? Have you used the "Copy Address" button in the core wallet?

What I noticed is that the address is only checked when you type something in the address box. When going back after trying an invalid address it won't re-evaluate and allows pressing the send button, but it will not send (it will send zero transactions). I have fixed this in [this commit](https://github.com/vertcoin-project/one-click-miner-vnext/commit/26c3a0173b013160f8daa8d24ca421a270095d5c), which will be part of the next alpha release.

**Comment by SCIZOMAD** [comment]
Hey I managed to get my coins to the wallet but don’t really know what I did different I am sure I will work it out again. Hope what I provided helped you.
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


5 May 2020, 13:09 by notifications@github.com:
