### ISSUE TITLE
An error has occurred in the script on the page

### ISSUE THREAD

**Issue by ac0uk** [vertcoin-project/one-click-miner-vnext#82]
![image](https://user-images.githubusercontent.com/35997054/80601544-ddede580-8a25-11ea-8d31-5979cddaddc7.png)

Following on from https://github.com/vertcoin-project/one-click-miner-vnext/issues/55

Can't re-open the issue, but can confirm this is still happening on Windows 10.

Very reproducible, just enable / disabling Auto Start for example and pressing "Save and Restart" causes this error.

Happy to run a debug build if needed but nothing in the debug log currently.

**Comment by Zaurian-GH** [comment]
Having the same issue on Windows 10.

**Comment by vertiond** [comment]
@ac0uk Is this still reproducible?

**Comment by ac0uk** [comment]
@vertiond nope haven’t seen it in a while so will close
