### ISSUE TITLE
Noob here why nothing in my wallet?

### ISSUE THREAD

**Issue by Mcdulle** [vertcoin-project/one-click-miner-vnext#85]
A proclaimed revenue of 0.17VTC every 24u

0.17000000/(24*3600) =0.00000196/s

So why isn't the wallet increasing? (with refresh after30min)

 something in the wallet

n/a

latest from gitub winx64

n/a

**Comment by gertjaap** [comment]
The indicated number is the average per 24h. 

In mining, you're trying to find a number to match a certain target. Once you do, you are rewarded for finding it. It can take a while for you to find such a number.

So the rewards aren't linear per second. It can take an hour or so to find a valid share, especially given your low hashrate (a modern CPU does between 0.5-1.0 VTC per 24h).

Once you found a valid share you will see a "pending pool payout" under your balance. Once that reaches 0.1, it is paid to your wallet and you can spend it.

My advise would be to leave it open for 24h and see how far you got.

**Comment by gertjaap** [comment]
Closing this issue. Feel free to reopen if something's still wrong
