### ISSUE TITLE
How do you add pools on Linux client?

### ISSUE THREAD

**Issue by bicarbonate** [vertcoin-project/one-click-miner-vnext#86]
Total Mining/Vert noob here but I am successfulyl mining on Linux but after trying the Windows One-Click I'm wondering how you add nodes or pools in the Linux client?

**Comment by gertjaap** [comment]
You can't. The One-Click miner has built in support only for p2pool, and uses Vertcoin Insight as source for blockchain data. You can't add nodes or pools manually.
