### ISSUE TITLE
Bug with GPU check, can be bypassed if new update found

### ISSUE THREAD

**Issue by honguyenminh** [vertcoin-project/one-click-miner-vnext#90]
When a new update is found, normally there will be a bottom-line saying "Update available". Click it will show the update menu, but if clicked on Back, it should return to whatever screen was showing before.

Clicking "Update available" will still show the update menu, but if clicked on Back, it will return to the wallet and show the status of mining in process, it will all be bypassed and show the wallet, when it shouldn't be. Hit stop then start again will return error

100% of the time. Get an older version, click "Update available" if there's an update, click back to wallet, all other checks bypassed

Github Released version of 1.0.1

Windows 8.1/10
GPU not relevant

2020/09/03 09:25:29.190489 OCM v1.0.1-c182a96-dirty Started up
2020/09/03 09:25:29.560463 [INFO] User IETF is en-US
2020/09/03 09:25:29.560463 [INFO] Matched tag is en
2020/09/03 09:25:29.560463 [INFO] Returning locale en
2020/09/03 09:25:29.678544 [INFO] Checking wallet..
2020/09/03 09:25:29.678544 [INFO] Error reading keyfile: open C:\Users\hothikimlien\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2020/09/03 09:25:29.678544 [INFO] Error reading keyfile: open C:\Users\hothikimlien\AppData\Roaming\vertcoin-ocm\keyfile.hex: The system cannot find the file specified.
2020/09/03 09:25:29.678544 [INFO] Initializing wallet VrSwsBBq6TgsAyy8YQdes4we49o6KyiqFU
2020/09/03 09:25:29.679540 [INFO] Wallet initialized: 0
2020/09/03 09:25:35.071246 [INFO] Checking wallet..
2020/09/03 09:25:35.071246 [INFO] Initializing wallet VpNoCPJM2KSUcNtdJNZ4Sq61zqz6M4if4B
2020/09/03 09:25:35.072247 [INFO] Wallet initialized: 1
2020/09/03 09:25:35.239389 [DEBUG] Unmatched GPU: [Intel(R) HD Graphics 4000]
2020/09/03 09:27:16.410770 [INFO] Stopping mining process...
2020/09/03 09:27:16.444810 [INFO] Checking wallet..
2020/09/03 09:27:16.452802 [INFO] Initializing wallet VpNoCPJM2KSUcNtdJNZ4Sq61zqz6M4if4B
2020/09/03 09:27:16.452802 [INFO] Wallet initialized: 1
2020/09/03 09:27:22.468200 [INFO] Stopping mining process...

**Comment by gertjaap** [comment]
This should be fixed in alpha7
