### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by goednieuwsjournaalnl** [vertcoin-project/one-click-miner-vnext#93]
![vert](https://user-images.githubusercontent.com/75339911/100803505-900de580-342b-11eb-911f-636abefaaa75.jpg)
 Does not want to install. Tried the methods known to date,
 it to work ;)

 screenshot attached

 Works every time '_

 .6

 win10 i7-640m

![vert](https://user-images.githubusercontent.com/75339911/100803742-f7c43080-342b-11eb-9c36-ccd4b5be40a6.jpg)

**Comment by gertjaap** [comment]
This generally means your anti-virus is removing the miner binary the OCM extracted before it's able to start it. Preferably exclude the `vertcoin-ocm` data directory under `%APPDATA%` from Anti-Virus before running & retry.

**Comment by gertjaap** [comment]
If this doesn't solve the problem, feel free to reopen. Please post your `debug.log`  (it's in the `%APPDATA%\vertcoin-ocm` folder as well) for more info.
