### ISSUE TITLE
Faild to send coins

### ISSUE THREAD

**Issue by greig525** [vertcoin-project/one-click-miner-vnext#94]
Coins sent to my core wallet

Failed to send you coins. Unable to sign transaction. Check password.

every time

vertcoin-ocm-2.0-alpha6-windows-x64

windows 10

My password is correct.

**Comment by gertjaap** [comment]
Could you post the `debug.log` (If you enable debug logging in the settings, then look for the debug.log in `%APPDATA%\vertcoin-ocm`
